'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createWorkspaceAiInsightsRequest}=require('../lib/tenancy/workspace-ai-insights-request');
const {createMarketAiRequest}=require('../lib/tenancy/workspace-market-ai-request');
const {resolveTenantContext}=require('../lib/tenancy/context');
const tenant='a3452bca-e259-40ed-a93d-b8bcc5c1b9e0',origin='https://harin-cafe24-sync.vercel.app',headers={cookie:'harin_dashboard_session=a.b'};
const context=()=>resolveTenantContext({session:{id:'session',userId:'owner',expiresAt:'2099-01-01T00:00:00Z'},requestedTenantId:tenant},{now:()=>new Date(),findMembership:async()=>({userId:'owner',tenantId:tenant,status:'ACTIVE',role:'OWNER',version:1})});
test('CLOVA awaits request-scoped saved configuration after owner auth without generating',async()=>{const order=[];const h=createWorkspaceAiInsightsRequest({resolveContext:async()=>{order.push('auth');return context();},configuration:()=>({status:'WRONG'}),createService:async()=>{order.push('key');await Promise.resolve();return {configuration:()=>({status:'DISABLED',enabled:false,ready:false}),listRuns:async()=>[]};}});const r=await h(new Request(origin+'/api/moaon/businesses/'+tenant+'/insights/ai',{headers}));assert.equal(r.status,200);assert.equal((await r.json()).configuration.status,'DISABLED');assert.equal(order[0],'auth');assert.equal(order[1],'key');assert.ok(order.lastIndexOf('auth')>1);});
test('Gemini async saved config stays bounded and auth is rechecked after loading',async()=>{const order=[];const h=createMarketAiRequest({resolveContext:async()=>{order.push('auth');return context();},configuration:async()=>{order.push('key');await Promise.resolve();return {status:'DISABLED',enabled:false};},createService:()=>{throw Error('No generation');}});const r=await h(new Request(origin+'/api/moaon/businesses/'+tenant+'/market-ai',{headers}));assert.equal((await r.json()).configuration.status,'DISABLED');assert.equal(order[0],'auth');assert.ok(order.lastIndexOf('auth')>order.indexOf('key'));let reads=0;const denied=createMarketAiRequest({resolveContext:async()=>{throw Object.assign(Error(),{code:'AUTH_REQUIRED'});},configuration:async()=>{reads++;},createService:()=>{}});assert.equal((await denied(new Request(origin+'/api/moaon/businesses/'+tenant+'/market-ai',{headers}))).status,401);assert.equal(reads,0);const slow=createMarketAiRequest({resolveContext:context,configuration:()=>new Promise(()=>{}),createService:()=>{},timeoutMs:10});assert.equal((await slow(new Request(origin+'/api/moaon/businesses/'+tenant+'/market-ai',{headers}))).status,504);});
