'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {buildRequestBody,createGeneralGeminiClient,MODEL}=require('../lib/ai/general-gemini-client');
const {validChatInput,guardGeneralChatRequest}=require('../lib/tenancy/workspace-general-chat-request');
const {validCommand}=require('../desktop/general-chat-contract.cjs');
const {isAllowedRemoteRequest}=require('../desktop/connection-policy.cjs');
const input={requestId:'12345678-1234-4123-8123-123456789abc',conversationId:'22345678-1234-4123-8123-123456789abc',question:'여행 계획을 도와줘',reportIds:[],files:[]};
const config={MOAON_MARKET_AI_ENABLED:'true',GEMINI_API_KEY:'fixture',GEMINI_MODEL:MODEL,GEMINI_FREE_PROJECT_ID:'gen-lang-client-fixture',GEMINI_FREE_TIER_CONFIRMED:'true',GEMINI_DATA_POLICY_CONFIRMED:'true',GEMINI_FREE_PROJECT_CONFIRMED_AT:new Date().toISOString()};
test('general questions need no report and preserve multi-turn roles',()=>{const b=buildRequestBody({messages:[{role:'user',text:'여행 추천'},{role:'model',text:'가까운 곳은 어떨까요?'},{role:'user',text:'기차로 가고 싶어'}]});assert.equal(b.contents.length,3);assert.equal(b.contents[2].parts[0].text,'기차로 가고 싶어');assert.equal(b.generationConfig.responseMimeType,undefined);assert.ok(validChatInput(input));assert.ok(validCommand({operation:'GENERATE',input}));});
test('attachment is explicit and inline data stays in the user turn',()=>{const f={name:'note.txt',mimeType:'text/plain',data:Buffer.from('첨부 시험').toString('base64')};assert.ok(validChatInput({...input,files:[f]}));const b=buildRequestBody({messages:[{role:'user',text:'요약',files:[f]}],attachment:{period:{start:'2026-09-01'}}});assert.equal(b.contents[0].parts[0].inlineData.mimeType,'text/plain');assert.match(b.contents[0].parts[1].text,/2026-09-01/);assert.ok(!validChatInput({...input,files:[{...f,mimeType:'text/html'}]}));assert.ok(!validChatInput({...input,files:[{...f,data:'x'.repeat(3000000)}]}));assert.ok(!validChatInput({...input,question:'x'.repeat(4001)}));assert.ok(!validCommand({operation:'GENERATE',input:{...input,url:'https://evil.test'}}));});
test('fixed Gemini endpoint produces plain response, not CLOVA/report JSON',async()=>{let call;const client=createGeneralGeminiClient({env:config,fetchImpl:async(url,options)=>{call={url,options};return Response.json({candidates:[{finishReason:'STOP',content:{parts:[{text:'기차 여행 계획을 함께 세워볼게요.'}]}}],usageMetadata:{promptTokenCount:10,candidatesTokenCount:10}});}});const r=await client.generate({messages:[{role:'user',text:'여행 계획'}]});assert.equal(r.output,'기차 여행 계획을 함께 세워볼게요.');assert.match(call.url,/generativelanguage.googleapis.com/);assert.equal(call.options.headers['x-goog-api-key'],'fixture');assert.equal(JSON.parse(call.options.body).contents[0].parts[0].text,'여행 계획');});
test('free configuration and quota failures never fall back to another provider',async()=>{let calls=0;const client=createGeneralGeminiClient({env:{...config,GEMINI_FREE_TIER_CONFIRMED:'false'},fetchImpl:async()=>{calls++;}});await assert.rejects(client.generate({messages:[{role:'user',text:'hello'}]}),{code:'SETUP_REQUIRED'});assert.equal(calls,0);const limited=createGeneralGeminiClient({env:config,fetchImpl:async()=>Response.json({error:{status:'RESOURCE_EXHAUSTED'}},{status:429})});await assert.rejects(limited.generate({messages:[{role:'user',text:'hello'}]}),{code:'QUOTA_BLOCKED'});});
test('route rejects cross-origin writes and remote renderer access',()=>{const url='https://harin-cafe24-sync.vercel.app/api/moaon/businesses/a3452bca-e259-40ed-a93d-b8bcc5c1b9e0/general-chat';assert.equal(guardGeneralChatRequest(new Request(url,{method:'POST',headers:{origin:'https://evil.test','content-type':'application/json'},body:'{}'})).response.status,403);const permit={generalChatPermit:{url,method:'POST'}};assert.equal(isAllowedRemoteRequest({url,method:'POST',webContentsId:123},permit),false);});

const {createGeneralChatRequest}=require('../lib/tenancy/workspace-general-chat-request');
const {resolveTenantContext}=require('../lib/tenancy/context');
const tenant='a3452bca-e259-40ed-a93d-b8bcc5c1b9e0',url='https://harin-cafe24-sync.vercel.app/api/moaon/businesses/'+tenant+'/general-chat',headers={cookie:'harin_dashboard_session=a.b',origin:'https://harin-cafe24-sync.vercel.app','content-type':'application/json'};
const ctx=(id=tenant,session='session')=>resolveTenantContext({session:{id:session,userId:'owner',expiresAt:'2099-01-01T00:00:00Z'},requestedTenantId:id},{now:()=>new Date(),findMembership:async()=>({userId:'owner',tenantId:id,status:'ACTIVE',role:'OWNER',version:1})});
const req=(v=input,h=headers,method='POST')=>new Request(url,{method,headers:h,body:JSON.stringify(v)});
function setup(options={}){let calls=0;const handle=createGeneralChatRequest({resolveContext:()=>ctx(),createService:()=>({list:async()=>({turns:[],configuration:{}}),remove:async()=>({deleted:true}),generate:async()=>{calls++;return {turn:{answer:'일반 답변'}};}}),...options});return {handle,calls:()=>calls};}
test('general route is owner scoped, closed shape and session fenced',async()=>{const s=setup();assert.equal((await s.handle(new Request(url,{headers}))).status,200);assert.equal(s.calls(),0);assert.equal((await s.handle(req())).status,200);assert.equal(s.calls(),1);assert.equal((await s.handle(req({...input,extra:'field'}))).status,400);assert.equal((await s.handle(req(input,{'content-type':'application/json',origin:headers.origin}))).status,401);const other=setup({resolveContext:()=>ctx('12345678-1234-4123-8123-123456789abc')});assert.equal((await other.handle(req())).status,403);let n=0;const changed=setup({resolveContext:()=>ctx(tenant,++n===1?'before':'after')});assert.equal((await changed.handle(req())).status,409);assert.equal((await s.handle(req({conversationId:input.conversationId},headers,'DELETE'))).status,200);assert.equal((await s.handle(req({conversationId:input.conversationId,tenantId:tenant},headers,'DELETE'))).status,400);});
test('general request deadline discards late results',async()=>{const s=setup({timeoutMs:15,createService:()=>({generate:()=>new Promise(()=>{})})});assert.equal((await s.handle(req())).status,504);});

const {createGeneralChatService}=require('../lib/ai/general-chat-service');
function chatDb(initial=[]){const rows=[...initial],calls=[];return {rows,calls,rpc:async(name,args)=>{calls.push({name,args});return {data:name.endsWith('reserve')?{allowed:true}:true,error:null};},from(table){let operation='select',data,filters=[],limit=30;const q={select(){return q;},eq(k,v){filters.push([k,v]);return q;},order(){return q;},limit(n){limit=n;return q;},insert(v){operation='insert';data=v;return q;},delete(){operation='delete';return q;},then(resolve,reject){return Promise.resolve().then(()=>{if(table!=='moaon_general_chat_turns')throw Error('Unexpected table');const matches=rows.filter(r=>filters.every(([k,v])=>r[k]===v));if(operation==='insert'){rows.push(data);return {data:null,error:null};}if(operation==='delete'){for(const r of matches)rows.splice(rows.indexOf(r),1);return {data:matches.map(r=>({id:r.id})),error:null};}return {data:matches.slice(0,limit),error:null};}).then(resolve,reject);}};return q;}};}
test('history, generation and deletion stay actor/tenant scoped; files are not returned',async()=>{const other={id:input.requestId,tenant_id:tenant,actor_id:'someone-else',conversation_id:input.conversationId,question:'다른 사용자 비밀',answer:'비밀 답변',report_ids:[],files:[{name:'private.txt',data:'c2VjcmV0',mimeType:'text/plain'}],model:MODEL,created_at:new Date().toISOString()};const db=chatDb([other]);let received,attachments=0;const service=createGeneralChatService({db,accountId:'fixture',client:{configuration:()=>({enabled:true,ready:true}),generate:async args=>{received=args;return {output:'일반 대화 응답',model:MODEL,usage:{promptTokens:1,completionTokens:2}};}},assertCurrentContext:async()=>true,loadAttachment:async()=>{attachments++;return {scope:'NAVER_AD_REPORT'};}});const context={tenantId:tenant,actorId:'owner'};assert.deepEqual((await service.list(context)).turns,[]);const result=await service.generate(context,input,undefined,Date.now()+25000);assert.equal(received.messages.length,1);assert.equal(received.attachment,null);assert.equal(attachments,0);assert.equal(result.turn.answer,'일반 대화 응답');assert.equal((await service.list(context)).turns.length,1);assert.ok(!JSON.stringify(await service.list(context)).includes('c2VjcmV0'));await service.remove(context,input.conversationId);assert.equal(db.rows.length,1);assert.equal(db.rows[0].actor_id,'someone-else');});

test('general chat deploys beside the control database like existing AI routes',()=>{assert.deepEqual(require('../vercel.json').functions['app/api/moaon/businesses/*/general-chat/route.js'].regions,['sin1']);});

test('only explicitly allowed Gemini models are accepted and sent to the selected URL',async()=>{assert.ok(validChatInput({...input,model:'gemini-3.8-flash'}));assert.ok(!validChatInput({...input,model:'unapproved-pro'}));let url;const c=createGeneralGeminiClient({env:config,fetchImpl:async u=>{url=u;return Response.json({candidates:[{finishReason:'STOP',content:{parts:[{text:'확인'}]}}]});}});const r=await c.generate({model:'gemini-3.8-flash',messages:[{role:'user',text:'hello'}]});assert.ok(url.includes('/gemini-3.8-flash:'));assert.equal(r.model,'gemini-3.8-flash');});

test('thinking setting follows the selected model',()=>{for(const [model,level] of [['gemini-3.5-flash-lite','minimal'],['gemini-3.8-flash','low']])assert.equal(buildRequestBody({model,messages:[{role:'user',text:'hello'}]}).generationConfig.thinkingConfig.thinkingLevel,level);});
