'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {buildInsightSnapshot}=require('../lib/ai/insight-snapshot');
function fixture(){
 const report=(id,start,end,revenue,spend,conversions)=>({id,platform:'NAVER',report_type:'WEEKLY',period_start:start,period_end:end,created_at:'2026-09-14T00:00:00Z',summary_json:{naver:{revenue,ad_spend:spend,clicks:100,purchase_count:conversions},financial_trust:{status:'BLOCKED'},customer_name:'SECRET_CUSTOMER'}});
 const reports=[report('current','2026-09-07','2026-09-13',120000,30000,4),report('previous','2026-08-31','2026-09-06',100000,25000,2)];
 const basis={currency:'KRW',taxBasis:'FIXTURE_INCLUSIVE',adScope:'FIXTURE_ALL',aggregationDefinition:'FIXTURE_CONVERSION'};
 return {tenantId:'tenant-a',reports,now:'2026-09-14T03:00:00Z',sourceState:{sourceAsOf:'2026-09-14T02:00:00Z',reportBasis:{current:basis,previous:{...basis}}}};
}
test('actual weekly fields yield server percentage and weighted CVR delta without customer data',()=>{const s=buildInsightSnapshot(fixture());assert.equal(s.metrics.revenueChangePct.value,20);assert.equal(s.metrics.cvrChangePp.value,2);assert.equal(s.metrics.contributionProfit.value,null);assert.equal(s.dataClass,'INTERNAL_AGGREGATE');assert.ok(!JSON.stringify(s).includes('SECRET_CUSTOMER'));});
test('missing provenance allows historical metrics but blocks comparison and present recommendation',()=>{const f=fixture();f.sourceState={};const s=buildInsightSnapshot(f);assert.equal(s.metrics.revenue.value,120000);assert.equal(s.dataState,'PARTIAL');assert.equal(s.comparison.allowed,false);assert.equal(s.sourceAsOf,null);});
test('zero previous uses absolute delta while null and invalid values never become zero',()=>{for(const bad of [null,'',-1,Infinity,1e20,true]){const f=fixture();f.reports[0].summary_json.naver.revenue=bad;assert.equal(buildInsightSnapshot(f).metrics.revenue.value,null);}const f=fixture();f.reports[1].summary_json.naver.revenue=0;const s=buildInsightSnapshot(f);assert.equal(s.metrics.revenueChange.value,120000);assert.equal(s.metrics.revenueChangePct.value,null);});
test('overlap, unequal periods, different basis block comparison',()=>{for(const mutate of [f=>f.reports[1].period_end='2026-09-07',f=>f.reports[1].period_start='2026-09-01',f=>f.sourceState.reportBasis.previous.currency='USD']){const f=fixture();mutate(f);assert.equal(buildInsightSnapshot(f).comparison.allowed,false);}});
test('other channel, tenant and open period are rejected',()=>{for(const mutate of [f=>f.reports[0].platform='COUPANG',f=>f.reports[0].tenant_id='tenant-b',f=>f.reports[0].period_end='2026-09-14']){const f=fixture();mutate(f);assert.throws(()=>buildInsightSnapshot(f),{code:'BLOCKED'});}});
test('hash excludes lookup time, includes source metrics and tenant',()=>{const f=fixture(),s=buildInsightSnapshot(f);f.now='2026-09-15T03:00:00Z';assert.equal(buildInsightSnapshot(f).hash,s.hash);assert.equal(buildInsightSnapshot(f).dataState,'STALE');f.tenantId='tenant-b';assert.notEqual(buildInsightSnapshot(f).hash,s.hash);});
test('negative profit allowed only with explicit financial readiness',()=>{const f=fixture();f.reports[0].summary_json.naver.contribution_profit=-200;assert.equal(buildInsightSnapshot(f).metrics.contributionProfit.value,null);f.reports[0].summary_json.financial_trust.status='READY';assert.equal(buildInsightSnapshot(f).metrics.contributionProfit.value,-200);});
test('CVR is recalculated from counts, absent denominator stays null',()=>{const f=fixture();f.reports[0].summary_json.naver.cvr=999;assert.equal(buildInsightSnapshot(f).metrics.cvr.value,4);f.reports[0].summary_json.naver.clicks=0;assert.equal(buildInsightSnapshot(f).metrics.cvr.value,null);});
