'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {randomUUID}=require('node:crypto');const {createInsightService}=require('../lib/ai/insight-service');
const context={verified:true,tenantId:'tenant-a',actorId:'actor'};
function fixture(options={}){let calls=0;const runs=[],claims=new Map(),settlements=[];const snapshot={tenantId:'tenant-a',scope:'NAVER_AD_REPORT',dataClass:'INTERNAL_AGGREGATE',hash:'hash',sourceIds:['report'],sourceAsOf:'2026-09-14',dataState:'PARTIAL',metrics:{revenue:{value:null,unit:'KRW',sourceId:'report'}},findings:[]};const output={cards:[],answer:'매출 {{metric:revenue}}',nextChecks:[]};const store={getRun:async({tenantId,runId})=>runs.find(r=>r.runId===runId&&r.tenantId===tenantId),findReusable:async({fingerprint})=>runs.find(r=>r.fingerprint===fingerprint),listRuns:async()=>runs,deleteRun:async()=>({deleted:true}),saveRun:async run=>{if(options.saveFail)throw Error('db');runs.push(run);}};const budget={reserve:async input=>{if(claims.has(input.fingerprint))return {allowed:false,reason:'ALREADY_PROCESSED'};claims.set(input.fingerprint,input);return {allowed:true};},settle:async input=>settlements.push(input)};const service=createInsightService({store,budget,generate:async()=>{calls++;if(options.onGenerate)await options.onGenerate();if(options.providerError)throw Object.assign(Error('bad'),{code:'TIMEOUT'});return {output:options.output||output,usage:{promptTokens:10,completionTokens:5},model:'HCX-007'};},loadSnapshot:async()=>options.snapshot||snapshot,configuration:()=>({enabled:true,ready:true,model:'HCX-007',pricingVersion:'test'}),estimateMaxCost:()=>10,priceUsage:u=>u?1:null,assertCurrentContext:options.check||(async()=>true)});return {service,runs,settlements,reservations:()=>claims.size,calls:()=>calls,input:()=>({requestId:randomUUID(),reportIds:['report'],question:'',kind:'SUMMARY'})};}
test('same snapshot cache avoids paid request and missing value never zero',async()=>{const f=fixture();const first=await f.service.generateRun({context,input:f.input()});const second=await f.service.generateRun({context,input:f.input()});assert.equal(first.output.answer,'매출 확인 필요');assert.equal(second.reused,true);assert.equal(f.calls(),1);});
test('invalid fabricated output charges usage but stores no output',async()=>{const f=fixture({output:{cards:[],answer:'매출 123원',nextChecks:[]}});await assert.rejects(f.service.generateRun({context,input:f.input()}),{code:'INVALID_OUTPUT'});assert.equal(f.runs.length,0);assert.equal(f.settlements[0].actualCostKrw,1);});
test('provider timeout preserves unknown reservation',async()=>{const f=fixture({providerError:true});await assert.rejects(f.service.generateRun({context,input:f.input()}),{code:'TIMEOUT'});assert.equal(f.settlements[0].status,'UNKNOWN');assert.equal(f.settlements[0].actualCostKrw,null);});
test('saved result failure does not permit duplicate generation',async()=>{const f=fixture({saveFail:true});await assert.rejects(f.service.generateRun({context,input:f.input()}),{code:'SAVE_FAILED'});await assert.rejects(f.service.generateRun({context,input:f.input()}),{code:'ALREADY_PROCESSED'});assert.equal(f.calls(),1);});
test('scope and cross tenant boundaries prevent provider access',async()=>{const f=fixture();const input={...f.input(),kind:'QUESTION',question:'전체 주문 매출 알려줘'};assert.equal((await f.service.generateRun({context,input})).status,'SCOPE_BLOCKED');assert.equal(f.calls(),0);await assert.rejects(f.service.generateRun({context:{...context,tenantId:'other'},input:f.input()}),{code:'DATA_POLICY_BLOCKED'});await assert.rejects(f.service.listRuns({context:{tenantId:'tenant-a'}}),{code:'FORBIDDEN'});});
test('revocation before provider and before return cannot expose output',async()=>{let checks=0;const f=fixture({check:async()=>++checks<4});await assert.rejects(f.service.generateRun({context,input:f.input()}),{code:'FORBIDDEN'});assert.equal(f.calls(),0);});
test('history loads only server runs and enforces six turns',async()=>{const f=fixture();let prior=await f.service.generateRun({context,input:f.input()});for(let n=2;n<=6;n++)prior=await f.service.generateRun({context,input:{...f.input(),kind:'QUESTION',question:'광고 지표 설명',parentRunId:prior.runId}});assert.equal(prior.turn,6);await assert.rejects(f.service.generateRun({context,input:{...f.input(),kind:'QUESTION',question:'광고 지표 설명',parentRunId:prior.runId}}),{code:'TURN_LIMIT'});assert.equal(f.calls(),6);});


test('cancelled provider result is not persisted and known usage settles',async()=>{const controller=new AbortController();const f=fixture({onGenerate:async()=>controller.abort()});await assert.rejects(f.service.generateRun({context,input:f.input(),signal:controller.signal}),{code:'TIMEOUT'});assert.equal(f.runs.length,0);assert.equal(f.settlements[0].actualCostKrw,1);});
test('auth revoked after provider cannot save or return explanation',async()=>{let allowed=true;const f=fixture({onGenerate:async()=>{allowed=false;},check:async()=>allowed});await assert.rejects(f.service.generateRun({context,input:f.input()}),{code:'FORBIDDEN'});assert.equal(f.calls(),1);assert.equal(f.runs.length,0);});
test('cache reapplies current freshness without second paid generation',async()=>{const snapshot={tenantId:'tenant-a',scope:'NAVER_AD_REPORT',dataClass:'INTERNAL_AGGREGATE',hash:'same',sourceIds:['report'],dataState:'READY',metrics:{revenue:{value:null,unit:'KRW',sourceId:'report'}},findings:[]};const f=fixture({snapshot});await f.service.generateRun({context,input:f.input()});snapshot.dataState='STALE';const result=await f.service.generateRun({context,input:f.input()});assert.equal(result.dataState,'STALE');assert.equal(f.calls(),1);});
test('blocked metrics never reserve or call provider',async()=>{const f=fixture({snapshot:{tenantId:'tenant-a',scope:'NAVER_AD_REPORT',dataClass:'INTERNAL_AGGREGATE',hash:'blocked',sourceIds:['report'],dataState:'BLOCKED',metrics:{},findings:[]}});await assert.rejects(f.service.generateRun({context,input:f.input()}),{code:'BLOCKED'});assert.equal(f.calls(),0);assert.equal(f.settlements.length,0);assert.equal(f.reservations(),0);assert.equal(f.runs.length,0);});
test('recognizable private identifiers are rejected before provider and history storage',async()=>{for(const question of ['010-1234-5678 광고 지표 설명','name@example.com 광고 지표 설명','900101-1234567 광고 지표 설명']){const f=fixture();await assert.rejects(f.service.generateRun({context,input:{...f.input(),kind:'QUESTION',question}}),{code:'QUESTION_PRIVACY_BLOCKED'});assert.equal(f.calls(),0);assert.equal(f.runs.length,0);assert.equal(f.reservations(),0);assert.equal(f.settlements.length,0);}});
