const test=require('node:test'),assert=require('node:assert/strict');
const r=require('../lib/assistant/ads-report.js'),c=require('../desktop/assistant-ads-contract.cjs');
test('missing metrics remain unknown and escaped HTML never includes source markup',()=>{const rows=r.points([{data:[{date:'2026-09-01',impCnt:100,clkCnt:4,salesAmt:200,ccnt:1}]}],'a','2026-09-01','2026-09-01');const s=r.summarize(rows,{start:'2026-09-01',end:'2026-09-01'},[{id:'a',name:'a'}],null);assert.equal(s.metrics.revenue,null);assert.equal(s.metrics.roas,null);assert.equal(s.status,'PARTIAL');assert.equal(s.metrics.cpc,50);assert.doesNotMatch(r.html({title:'<script>x</script>',summary_json:s}),/<script>/);});
test('only selected period and unique daily rows accepted',()=>{assert.throws(()=>r.points([{data:[{date:'2026-09-02'}]}],'a','2026-09-01','2026-09-01'),/ADS_DATE_INVALID/);assert.throws(()=>r.points([{data:[]}],'a','2026-09-01','2026-09-01'),/ADS_NO_DATA/);});
test('advertising requests bind private identity and valid dates',()=>{const v={action:'ADS_REQUEST',start:'2026-09-01',end:'2026-09-07',fresh:true};assert.equal(c.valid(v),true);assert.equal(c.valid(v,true),false);assert.equal(c.valid({...v,userId:'123',chatId:'123'},true),true);assert.equal(c.valid({...v,userId:'123',chatId:'456'},true),false);assert.equal(c.valid({...v,start:'2026-02-30'}),false);assert.equal(c.valid({action:'ADS_TICK'}),false);});
test('fresh collection reads Naver endpoints only',async()=>{const calls=[];const summary=await r.collect({start:'2026-09-01',end:'2026-09-01',fresh:true,request:async(method,path)=>{calls.push([method,path]);return {data:path==='/ncc/campaigns'?[{nccCampaignId:'c',name:'test'}]:[{data:[{date:'2026-09-01',impCnt:10,clkCnt:1,salesAmt:100,ccnt:0,convAmt:0}]}]};}});assert.equal(summary.metrics.roas,0);assert.equal(summary.status,'OBSERVED');assert.deepEqual(calls,[['GET','/ncc/campaigns'],['GET','/stats']]);});

test('selected campaigns never query unselected campaigns or substitute missing selection',async()=>{
 const calls=[];const request=async(method,path,q)=>{calls.push([path,q?.id]);return {data:path==='/ncc/campaigns'?[{nccCampaignId:'a',name:'A'},{nccCampaignId:'b',name:'B'}]:[{data:[{date:'2026-09-01',impCnt:10,clkCnt:1,salesAmt:100,ccnt:0,convAmt:0}]}]};};
 const s=await r.collect({start:'2026-09-01',end:'2026-09-01',fresh:true,campaignIds:['b'],request});assert.equal(s.campaigns.length,1);assert.equal(s.campaigns[0].id,'b');assert.deepEqual(calls.filter(x=>x[0]==='/stats'),[['/stats','b']]);
 await assert.rejects(r.collect({start:'2026-09-01',end:'2026-09-01',fresh:true,campaignIds:['missing'],request}),/ADS_CAMPAIGN_MISSING/);
});
