'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),{PGlite}=require('@electric-sql/pglite');
const T='a3452bca-e259-40ed-a93d-b8bcc5c1b9e0',ids=[1,2,3].map(n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`),sessions=[4,5,6].map(n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`),H='a'.repeat(64);
async function fixture(legacy=false){const db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema moaon_control;create table moaon_control.tenants(id uuid primary key,status text);create table public.dashboard_users(user_id uuid primary key,display_name text,role text,active boolean);create table public.dashboard_sessions(id uuid,user_id uuid,token_hash text,revoked_at timestamptz,expires_at timestamptz,role text);create table moaon_control.memberships(tenant_id uuid,user_id uuid,version int,status text,role text);insert into moaon_control.tenants values('${T}','ACTIVE');create table public.moaon_cases(id uuid primary key,tenant_id uuid,kind text,platform text,status text,observed_state text);create table public.moaon_case_events(id uuid primary key,tenant_id uuid,case_id uuid,created_at timestamptz default now());create table public.moaon_assistant_bots(tenant_id uuid,slot text,revision int,username text,envelope jsonb,settings jsonb,runtime_status text);create function public.moaon_assistant_access_verify(text,boolean) returns jsonb language plpgsql as $$begin if $1<>'worker' then raise exception 'ASSISTANT_AUTH_REQUIRED';end if;return '{"scopes":["orders","cs","tasks","reports"]}';end$$;`);for(let i=0;i<3;i++){await db.query("insert into dashboard_users values($1,$2,$3,true);",[ids[i],`User ${i+1}`,i?'MEMBER':'OWNER']);await db.query("insert into dashboard_sessions values($1,$2,'sessionhash',null,now()+interval '1 day',$3)",[sessions[i],ids[i],i?'MEMBER':'OWNER']);await db.query("insert into moaon_control.memberships values($1,$2,1,'ACTIVE',$3)",[T,ids[i],i?'MEMBER':'OWNER']);}for(const slot of ['WORK','SOLO','STUDY','SUP','AD'])await db.query("insert into moaon_assistant_bots values($1,$2,1,$3,'{\"ciphertext\":\"fixture-only\"}','{\"enabled\":true}','RUNNING')",[T,slot,'bot_'+slot]);if(legacy){
await db.exec(`create function public.moaon_assistant_menu(uuid,uuid,text,jsonb,text) returns jsonb language sql as $fn$select '{"AD":["reports","checklist","settings"]}'::jsonb$fn$;`);

await db.exec('create table moaon_assistant_settings(tenant_id uuid,settings jsonb,test_id uuid,revision int);drop table public.moaon_case_events;drop table public.moaon_cases;create table public.moaon_assistant_access(tenant_id uuid,owner_id uuid,membership_version int,revoked_at timestamptz,expires_at timestamptz);');
for(const name of ['20260916130000_moaon_bot_automations.sql','20260917110000_moaon_role_briefings.sql','20260917010000_moaon_case_tracking.sql','20260917011000_moaon_case_digest.sql','20260917120000_moaon_new_orders_only.sql','20260916200000_moaon_advertising_jobs.sql','20260916220000_moaon_ads_scope_revisions.sql','20260916230000_moaon_ads_revision_compare.sql'])await db.exec(fs.readFileSync('supabase/migrations/'+name,'utf8'));
await db.query("insert into moaon_assistant_access values($1,$2,1,null,now()+interval '1 day')",[T,ids[0]]);
await db.exec(`update moaon_assistant_bots set settings=settings||'{"chatId":"100"}';insert into moaon_bot_automations(tenant_id,slot,settings) values('a3452bca-e259-40ed-a93d-b8bcc5c1b9e0','WORK','{"schedule":true,"changes":false,"time":"09:00","days":[0,1,2,3,4,5,6],"quietStart":8,"quietEnd":20,"sections":["tasks"]}');insert into moaon_ads_settings(tenant_id,settings) values('a3452bca-e259-40ed-a93d-b8bcc5c1b9e0','{"daily":true,"weekly":false,"time":"10:00","notify":true,"failures":true}');insert into moaon_case_settings(tenant_id,enabled) values('a3452bca-e259-40ed-a93d-b8bcc5c1b9e0',true);`);
}
await db.exec(fs.readFileSync('supabase/migrations/20260917140000_moaon_personal_preferences.sql','utf8'));const call=async(i,input,worker=false)=>(await db.query('select public.moaon_assistant_preferences($1,$2,$3,$4,$5) v',[worker?null:ids[i],worker?null:sessions[i],worker?null:'sessionhash',JSON.stringify(input),worker?'worker':null])).rows[0].v;return {db,call};}
async function link(call,i,chat){let r=await call(i,{action:'PREF_READ'});r=await call(i,{action:'LINK_BEGIN',revision:r.revision,chatId:chat,codeHash:H});return call(i,{action:'LINK_VERIFY',revision:r.revision,codeHash:H});}
test('personal preferences isolate three active members and strictly validate own settings',async()=>{const {db,call}=await fixture();try{for(let i=0;i<3;i++){const r=await call(i,{action:'PREF_READ'});assert.equal(r.userId,ids[i]);assert.equal(r.verified,false);assert.equal(r.settings.newOrders,false);assert.equal(r.settings.WORK.enabled,false);assert.ok(!JSON.stringify(r).includes('fixture-only'));await link(call,i,String(100+i));}let r=await call(1,{action:'PREF_READ'});r=await call(1,{action:'PREF_SAVE',revision:r.revision,settings:{...r.settings,WORK:{enabled:true,time:'10:30',days:[0,2]}}});assert.equal((await call(0,{action:'PREF_READ'})).settings.WORK.enabled,false);assert.equal((await call(2,{action:'PREF_READ'})).settings.WORK.enabled,false);await assert.rejects(call(1,{action:'PREF_SAVE',revision:r.revision-1,settings:r.settings}),/CONFLICT/);for(const change of [{days:[0,0]},{days:['0']},{days:[]},{time:'24:00'},{enabled:'true'},{extra:true}])await assert.rejects(call(1,{action:'PREF_SAVE',revision:r.revision,settings:{...r.settings,WORK:{...r.settings.WORK,...change}}}),/INVALID/);await assert.rejects(call(1,{action:'PREF_READ',userId:ids[0]}),/INVALID/);await db.query('update dashboard_sessions set revoked_at=now() where id=$1',[sessions[1]]);await assert.rejects(call(1,{action:'PREF_READ'}),/AUTH_REQUIRED/);await db.exec('set role anon');await assert.rejects(db.query('select * from moaon_personal_preferences'),/permission denied/);await assert.rejects(db.query("select public.moaon_assistant_preferences(null,null,null,'{}',null)"),/permission denied/);}finally{await db.close();}});
test('recipient proof caps persist and duplicate private chat ownership is rejected',async()=>{const {db,call}=await fixture();try{await link(call,0,'100');let r=await call(1,{action:'PREF_READ'});for(const chatId of ['-123','@group','0','123.5',' 100',100])await assert.rejects(call(1,{action:'LINK_BEGIN',revision:r.revision,chatId,codeHash:H}),/INVALID/);r=await call(1,{action:'LINK_BEGIN',revision:r.revision,chatId:'100',codeHash:H});assert.equal((await call(1,{action:'LINK_VERIFY',revision:r.revision,codeHash:H})).error,'ASSISTANT_RECIPIENT_IN_USE');await assert.rejects(call(1,{action:'LINK_BEGIN',revision:r.revision,chatId:'101',codeHash:H}),/RATE_LIMITED/);r=await call(2,{action:'PREF_READ'});r=await call(2,{action:'LINK_BEGIN',revision:r.revision,chatId:'102',codeHash:H});for(let i=0;i<5;i++)assert.equal((await call(2,{action:'LINK_VERIFY',revision:r.revision,codeHash:'b'.repeat(64)})).error,'ASSISTANT_CODE_INVALID');assert.equal((await call(2,{action:'LINK_VERIFY',revision:r.revision,codeHash:H})).error,'ASSISTANT_CHALLENGE_EXPIRED');assert.equal((await db.query('select attempts from moaon_personal_preferences where user_id=$1',[ids[2]])).rows[0].attempts,5);await db.query("update moaon_personal_preferences set challenge_until=now()-interval '1 minute' where user_id=$1",[ids[1]]);assert.equal((await call(1,{action:'LINK_VERIFY',revision:1,codeHash:H})).error,'ASSISTANT_CHALLENGE_EXPIRED');}finally{await db.close();}});
test('worker claims recheck membership and revision; result loss never permits duplicate delivery',async()=>{const {db,call}=await fixture();try{const time=(await db.query("select to_char(now() at time zone 'Asia/Seoul','HH24:MI') t")).rows[0].t;for(let i=0;i<3;i++){await link(call,i,String(100+i));const r=await call(i,{action:'PREF_READ'});for(const slot of ['WORK','SOLO','STUDY','SUP','AD'])r.settings[slot]={enabled:true,time,days:[0,1,2,3,4,5,6]};await call(i,{action:'PREF_SAVE',revision:r.revision,settings:r.settings});}let jobs=(await call(0,{action:'PREF_DUE'},true)).jobs;assert.equal(jobs.length,15);const job=jobs.find(x=>x.userId===ids[0]&&x.slot==='WORK');let c=await call(0,{...job,action:'PREF_CLAIM'},true);assert.equal(c.claimed,true);assert.equal(c.chatId,'100');assert.equal(c.bot.envelope.ciphertext,'fixture-only');assert.equal((await call(0,{...job,action:'PREF_CLAIM'},true)).claimed,false);await call(0,{...job,action:'PREF_RESULT',status:'FAILED'},true);assert.equal((await call(0,{...job,action:'PREF_CLAIM'},true)).claimed,false);const revoked=jobs.find(x=>x.userId===ids[1]);await db.query("update moaon_control.memberships set status='REVOKED',version=2 where user_id=$1",[ids[1]]);await assert.rejects(call(0,{...revoked,action:'PREF_CLAIM'},true),/AUTH_REQUIRED/);assert.ok(!(await call(0,{action:'PREF_DUE'},true)).jobs.some(x=>x.userId===ids[1]));const stale=jobs.find(x=>x.userId===ids[2]);await call(2,{action:'PREF_UNLINK',revision:stale.revision});await assert.rejects(call(0,{...stale,action:'PREF_CLAIM'},true),/CONFLICT/);await db.query('update dashboard_users set active=false where user_id=$1',[ids[0]]);await assert.rejects(call(0,{action:'PREF_READ'}),/AUTH_REQUIRED/);}finally{await db.close();}});

test('test request is idempotent and unlink disables flags without restoring legacy recipients',async()=>{const {db,call}=await fixture();try{await link(call,1,'101');let r=await call(1,{action:'PREF_READ'});let req={action:'PREF_TEST',revision:r.revision,slot:'SOLO',id:'77777777-7777-4777-8777-777777777777'};assert.equal((await call(1,req)).queued,true);assert.equal((await call(1,req)).queued,true);let job=(await call(0,{action:'PREF_DUE'},true)).jobs.find(j=>j.kind==='TEST');assert.equal(job.userId,ids[1]);assert.equal((await call(0,{...job,action:'PREF_CLAIM'},true)).claimed,true);assert.equal((await call(0,{...job,action:'PREF_CLAIM'},true)).claimed,false);await call(1,{action:'PREF_UNLINK',revision:r.revision});r=await call(1,{action:'PREF_READ'});assert.equal(r.chatId,'');assert.equal(r.settings.newOrders,false);assert.ok(Object.values(r.settings).every(x=>typeof x!=='object'||x.enabled===false));assert.ok(!(await call(0,{action:'PREF_DUE'},true)).jobs.length);}finally{await db.close();}});
test('legacy owner migration preserves configuration and installs guarded delivery suppression',async()=>{const {db,call}=await fixture(true);try{let r=await call(0,{action:'PREF_READ'});assert.equal(r.verified,true);assert.equal(r.chatId,'100');assert.equal(r.settings.WORK.enabled,true);assert.equal(r.settings.AD.enabled,true);assert.equal(r.settings.AD.time,'10:00');assert.equal(r.settings.newOrders,true);assert.equal((await call(1,{action:'PREF_READ'})).verified,false);for(const [fn,marker] of [['moaon_assistant_bot_automation','legacy_chat_id'],['moaon_assistant_cases','personal_ordered_at'],['moaon_assistant_ads',"j.dedupe like 'daily:%'"]])assert.ok((await db.query('select pg_get_functiondef($1::regprocedure) source',[`public.${fn}(uuid,uuid,text,jsonb,text)`])).rows[0].source.includes(marker));await call(0,{action:'PREF_UNLINK',revision:r.revision});assert.equal((await db.query('select legacy_chat_id from moaon_personal_preferences where user_id=$1',[ids[0]])).rows[0].legacy_chat_id,'100');const callLegacy=async(input)=>(await db.query('select public.moaon_assistant_ads(null,null,null,$1,$2) r',[JSON.stringify(input),'worker'])).rows[0].r;for(const dedupe of ['daily:2026-09-17','manual:fixture'])await db.query("insert into moaon_ads_jobs(tenant_id,dedupe,start_date,end_date,fresh,status,bot_revision,chat_id) values($1,$2,current_date,current_date,true,'SUCCEEDED',1,'100')",[T,dedupe]);assert.deepEqual(await callLegacy({action:'DELIVERY'}),{});assert.equal((await db.query("select delivery from moaon_ads_jobs where dedupe like 'daily:%'")).rows[0].delivery,'SKIPPED');assert.ok((await callLegacy({action:'DELIVERY'})).job);const fn=(await db.query("select pg_get_functiondef('public.moaon_assistant_preferences(uuid,uuid,text,jsonb,text)'::regprocedure) s")).rows[0].s;await db.exec(fn.replace("ts timestamp :=",'ts timestamp :='));}finally{await db.close();}});

test('new orders aggregate by recipient and channel, exclude pre-subscription orders, and consume once',async()=>{const {db,call}=await fixture(true);try{
 await link(call,1,'101');let r=await call(1,{action:'PREF_READ'});await call(1,{action:'PREF_SAVE',revision:r.revision,settings:{...r.settings,newOrders:true}});
 await db.query("update moaon_personal_preferences set notify_since=now()-interval '2 days' where user_id=$1",[ids[0]]);
 let source=(await db.query("select pg_get_functiondef('public.moaon_assistant_preferences(uuid,uuid,text,jsonb,text)'::regprocedure) s")).rows[0].s;source=source.replace("ts timestamp:=now() at time zone 'Asia/Seoul'","ts timestamp:=(now() at time zone 'Asia/Seoul')::date+interval '12 hours'");await db.exec(source);
 await db.exec('update moaon_case_settings set enabled=false');
 const cases=async input=>(await db.query('select public.moaon_assistant_cases(null,null,null,$1,$2) r',[JSON.stringify(input),'worker'])).rows[0].r;
 const lease=(await cases({action:'BEGIN'})).lease;assert.ok(lease,'personal opt-in keeps collection active while legacy notifications are off');
 const observed=[{platform:'NAVER',kind:'ORDER',state:'PENDING',sourceId:'old',orderedAt:new Date(Date.now()-86400000).toISOString()},{platform:'NAVER',kind:'ORDER',state:'PENDING',sourceId:'new',orderedAt:new Date().toISOString()},{platform:'CAFE24',kind:'ORDER',state:'PENDING',sourceId:'new2',orderedAt:new Date().toISOString()},{platform:'COUPANG',kind:'CS',state:'PENDING',sourceId:'cs',orderedAt:new Date().toISOString()}];
 await cases({action:'APPLY',lease,observations:observed,sources:[]});
 const jobs=(await call(0,{action:'PREF_DUE'},true)).jobs.filter(j=>j.kind==='NEW_ORDER');assert.equal(jobs.length,2);
 const own=await call(0,{...jobs.find(j=>j.userId===ids[0]),action:'PREF_CLAIM'},true);assert.deepEqual(own.groups.sort((a,b)=>a.platform.localeCompare(b.platform)),[{platform:'CAFE24',count:1},{platform:'NAVER',count:2}]);
 const memberJob=jobs.find(j=>j.userId===ids[1]);const member=await call(0,{...memberJob,action:'PREF_CLAIM'},true);assert.deepEqual(member.groups.sort((a,b)=>a.platform.localeCompare(b.platform)),[{platform:'CAFE24',count:1},{platform:'NAVER',count:1}]);assert.equal((await call(0,{...memberJob,action:'PREF_CLAIM'},true)).claimed,false);assert.equal((await call(0,{action:'PREF_DUE'},true)).jobs.filter(j=>j.kind==='NEW_ORDER').length,0);
 await call(0,{...memberJob,action:'PREF_RESULT',status:'UNKNOWN'},true);assert.equal((await call(0,{action:'PREF_DUE'},true)).jobs.filter(j=>j.kind==='NEW_ORDER').length,0);
 }finally{await db.close();}});
