'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {PGlite}=require('@electric-sql/pglite');
const {createGroupBidOperations}=require('../lib/dashboard/group-bids.js');
const {valid,project}=require('../desktop/keyword-bids.cjs');
function adapter(pg){return {from(table){let kind='SELECT',data,filters=[],single=false;const b={select(){return b},eq(k,v){filters.push([k,v]);return b},update(v){kind='UPDATE';data=v;return b},upsert(v){kind='INSERT';data=v;return b},single(){single=true;return run()},maybeSingle(){single=true;return run()},then(a,z){return run().then(a,z)}};async function run(){let args=[],sql;const param=v=>{args.push(v);return '$'+args.length};if(kind==='SELECT')sql='select * from '+table;else if(kind==='UPDATE')sql='update '+table+' set '+Object.entries(data).map(([k,v])=>k+'='+param(v)).join(',');else sql='insert into '+table+' ('+Object.keys(data).join(',')+') values ('+Object.values(data).map(param).join(',')+') on conflict(actor,request_key) do nothing';if(filters.length)sql+=' where '+filters.map(([k,v])=>k+'='+param(v)).join(' and ');if(kind!=='SELECT')sql+=' returning *';try{const r=await pg.query(sql,args);return {data:single?r.rows[0]||null:r.rows};}catch(error){return {error};}}return b}};}
const scope={ready:true,keywords:[],campaigns:[{ncc_campaign_id:'cmp-test',campaign_type:'SHOPPING',name:'캠페인'}],groups:[{ncc_adgroup_id:'grp-test',ncc_campaign_id:'cmp-test',name:'차'}]};
test('group manual bid contracts preserve explicit confirmation and separate target IDs',()=>{assert.ok(valid({action:'GROUP_LIST'}));assert.ok(valid({action:'GROUP_READ',keywordId:'grp-test'}));assert.equal(valid({action:'READ',keywordId:'grp-test'}),false);assert.equal(valid({action:'GROUP_EXECUTE',requestId:'00000000-0000-4000-8000-000000000001',confirm:false}),false);assert.throws(()=>project({ok:true,groups:[{id:'bad',name:'x',campaignName:'x'}]},{action:'GROUP_LIST'}));});
test('group bid database claim, stale preview, inactive protection and uncertain-write dedupe',async()=>{const pg=new PGlite();try{await pg.exec('create role anon;create role authenticated;create role service_role;');await pg.exec(fs.readFileSync('supabase/migrations/20260912124607_moaon_group_bid_requests.sql','utf8'));let bid=1000,writes=0,locked=false,uncertain=false,enabled=true;const api={request:async(method,url,query,body)=>{if(method==='PUT'){assert.equal(query.fields,'bidAmt');assert.deepEqual(Object.keys(body).sort(),['bidAmt','nccAdgroupId']);writes++;if(uncertain)throw Error('timeout');bid=body.bidAmt;}return {data:url.includes('campaigns')?{nccCampaignId:'cmp-test',status:'ELIGIBLE',userLock:false}:{nccAdgroupId:'grp-test',nccCampaignId:'cmp-test',name:'차',adgroupType:'SHOPPING',bidAmt:bid,status:'ELIGIBLE',userLock:locked}};}};
const op=createGroupBidOperations({db:adapter(pg),api,loadScope:async()=>scope,configuration:()=>({write_enabled:enabled})}),ctx={actor:'owner-a',check:async()=>{}};
const preview=async(key,b=1200)=>op({action:'GROUP_PREVIEW',keywordId:'grp-test',currentBid:bid,bid:b,key},ctx),execute=id=>op({action:'GROUP_EXECUTE',requestId:id,confirm:true},ctx);
let r=await preview('first');assert.equal(writes,0);await assert.rejects(op({action:'GROUP_EXECUTE',requestId:r.requestId,confirm:true},{...ctx,actor:'other'}),/BID_REQUEST_NOT_FOUND/);locked=true;await assert.rejects(execute(r.requestId),/CAMPAIGN_NOT_ACTIVE/);locked=false;bid=1100;await assert.rejects(execute(r.requestId),/BID_SNAPSHOT_STALE/);bid=1000;const out=await Promise.allSettled([execute(r.requestId),execute(r.requestId)]);assert.ok(out.some(r=>r.status==='fulfilled'));assert.equal(writes,1);assert.equal(bid,1200);assert.equal((await execute(r.requestId)).state,'VERIFIED');assert.equal(writes,1);
r=await preview('second',1300);enabled=false;await assert.rejects(execute(r.requestId),/NAVER_BID_WRITE_DISABLED/);enabled=true;uncertain=true;await assert.rejects(execute(r.requestId),/BID_RESULT_UNKNOWN/);await assert.rejects(execute(r.requestId),/BID_RESULT_REQUIRES_REVIEW/);assert.equal(writes,2);const another=await preview('third',1400);await assert.rejects(execute(another.requestId),/BID_BUSY/);assert.equal(writes,2);assert.equal((await op({action:'GROUP_STATUS',requestId:r.requestId},ctx)).state,'UNKNOWN');bid=1300;assert.equal((await op({action:'GROUP_STATUS',requestId:r.requestId},ctx)).state,'VERIFIED');assert.equal((await pg.query("select has_table_privilege('anon','moaon_group_bid_requests','SELECT') ok")).rows[0].ok,false);
}finally{await pg.close();}});
