'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
const {createPublicMarketAiService}=require('../lib/ai/public-market-service');
const {buildPublicMarketSnapshot}=require('../lib/ai/public-market-snapshot');
function setup(opts={}){let calls=0,loads=0;const runs=[],claims=new Set(),settlements=[];const snapshot=()=>buildPublicMarketSnapshot({approvedPublicSources:[{kind:'NAVER_SEARCH_TREND',id:'naver-search-trend',url:'https://datalab.naver.com/keyword/trendSearch.naver',observedAt:'2026-09-14T00:00:00Z',period:{start:'2026-09-01',end:'2026-09-13'},points:Array.from({length:13},(_,i)=>({date:`2026-09-${String(i+1).padStart(2,'0')}`,ratio:20+i}))}],now:'2026-09-14T01:00:00Z'});const store={findReusable:async({fingerprint})=>runs.find(r=>r.fingerprint===fingerprint),reserve:async({fingerprint})=>{if(claims.has(fingerprint))return {allowed:false,reason:'ALREADY_PROCESSED'};claims.add(fingerprint);return {allowed:true};},settle:async x=>settlements.push(x),saveRun:async r=>{if(opts.saveFail)throw Error('save');runs.push(r);}};const service=createPublicMarketAiService({store,now:()=>Date.parse("2026-09-14T01:00:00Z"),configuration:()=>({enabled:!opts.off,ready:true,model:'gemini-3.5-flash-lite'}),accountId:'test-account',loadSnapshot:async()=>{loads++;return snapshot();},generate:async args=>{calls++;assert.ok(!JSON.stringify(args.snapshot).includes('PRIVATE_QUERY'));if(opts.timeout)throw Object.assign(Error('timeout'),{code:'TIMEOUT'});return {output:{cards:[],answer:'자료의 흐름을 추가 확인하세요.',nextChecks:[]},model:'gemini-3.5-flash-lite',usage:{promptTokens:10,completionTokens:20}};},assertCurrentContext:opts.check||(async()=>true)});return {service,runs,calls:()=>calls,loads:()=>loads,settlements};}
const context={verified:true,tenantId:'a3452bca-e259-40ed-a93d-b8bcc5c1b9e0',actorId:'owner'},input=()=>({requestId:randomUUID(),kind:'TREND_EXPLANATION',query:'PRIVATE_QUERY',days:30});
test('public analysis caches validated output and never exposes query to model or storage',async()=>{const s=setup();const first=await s.service.generateRun({context,input:input()});assert.equal(first.status,'SUCCEEDED');assert.equal((await s.service.generateRun({context,input:input()})).reused,true);assert.equal(s.calls(),1);assert.ok(!JSON.stringify(s.runs).includes('PRIVATE_QUERY'));});
test('OFF does not even fetch public sources',async()=>{const s=setup({off:true});await assert.rejects(s.service.generateRun({context,input:input()}),{code:'DISABLED'});assert.equal(s.calls(),0);assert.equal(s.loads(),0);});
test('timeout retains quota and duplicate request never calls again',async()=>{const s=setup({timeout:true});await assert.rejects(s.service.generateRun({context,input:input()}),{code:'TIMEOUT'});assert.equal(s.settlements[0].status,'UNKNOWN');await assert.rejects(s.service.generateRun({context,input:input()}),{code:'ALREADY_PROCESSED'});assert.equal(s.calls(),1);});
test('save failure cannot cause silent duplicate generation',async()=>{const s=setup({saveFail:true});await assert.rejects(s.service.generateRun({context,input:input()}),{code:'SAVE_FAILED'});await assert.rejects(s.service.generateRun({context,input:input()}),{code:'ALREADY_PROCESSED'});assert.equal(s.calls(),1);});
