'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {loadSalesCatalog,seedSalesRules,saveSalesRule}=require('../lib/stock/sales');
function fixture(){
 const tables={cafe24_products:[{external_product_no:'10',product_name:'작수차 3개'}],channel_products:[{id:'1',platform:'CAFE24',external_product_id:'10',master_product_id:'m',external_product_name:'작수차 3개'},{id:'2',platform:'NAVER',external_product_id:'20',master_product_id:'m',external_product_name:'작수차 3개',raw_data:{source_type:'NAVER_COMMERCE_PRODUCT'}},{id:'3',platform:'COUPANG',external_product_id:'30',master_product_id:'m'}],coupang_product_items:[{vendor_item_id:'31',seller_product_id:'30',item_name:'작수차 5개'},{vendor_item_id:'32',seller_product_id:'30',item_name:'RG',raw_data:{fulfillmentType:'ROCKET_GROWTH'}}],cafe24_order_items:[{external_item_id:'a',external_product_no:'10',option_name:'2개입',product_name:'작수차'}],naver_commerce_order_items:[],moaon_stock_lots:[{tenant_id:'a3452bca-e259-40ed-a93d-b8bcc5c1b9e0',data:{productNo:'10',unit:'개'}}],moaon_stock_sales_rules:[]};
 const db={from(table){let rows=tables[table]||[];const q={select(){return q},order(){return q},limit(){return q},abortSignal(){return q},in(k,v){rows=rows.filter(r=>v.includes(String(r[k])));return q},eq(k,v){rows=rows.filter(r=>r[k]===v);return q},gt(k,v){rows=rows.filter(r=>r[k]>v);return q},then(resolve){return Promise.resolve({data:rows}).then(resolve)},upsert(row,options){const list=tables[table]||(tables[table]=[]);const old=list.find(r=>['platform','product_key','option_key'].every(k=>r[k]===row[k]));if(old&&!options.ignoreDuplicates)Object.assign(old,row);else if(!old)list.push(row);return Promise.resolve({data:null});}};return q;}};return {db,tables};
}
test('every linked platform defaults to one regardless of title multipacks; reseeding preserves edits',async()=>{const {db,tables}=fixture();await seedSalesRules({db,productNo:'10',unit:'개',actor:'actor'});assert.equal(tables.moaon_stock_sales_rules.length,3);assert.ok(tables.moaon_stock_sales_rules.every(r=>r.factor===1));assert.ok(!tables.moaon_stock_sales_rules.some(r=>r.product_key==='32'));tables.moaon_stock_sales_rules[0].factor=3;await seedSalesRules({db,productNo:'10',unit:'개',actor:'actor'});assert.equal(tables.moaon_stock_sales_rules[0].factor,3);});
test('exact option factors can be saved without changing the base rule; invalid or unlinked factors rejected',async()=>{const {db,tables}=fixture();await seedSalesRules({db,productNo:'10',unit:'개',actor:'actor'});const value={platform:'CAFE24',productKey:'10',optionKey:'2개입',productNo:'10',unit:'개',factor:2,enabled:true};await saveSalesRule({db,value,actor:'actor'});assert.equal(tables.moaon_stock_sales_rules.find(r=>r.option_key==='2개입').factor,2);assert.equal(tables.moaon_stock_sales_rules.find(r=>r.platform==='CAFE24'&&r.option_key==='*').factor,1);for(const bad of [{factor:0},{factor:1.2},{factor:NaN},{productNo:'999'},{productKey:'999'}])await assert.rejects(saveSalesRule({db,value:{...value,...bad},actor:'actor'}),/INVALID_RULE/);});
test('ambiguous cross-platform product links never silently pick a stock target',async()=>{const {db,tables}=fixture();tables.channel_products.push({id:'4',platform:'CAFE24',external_product_id:'11',master_product_id:'m'});const result=await loadSalesCatalog({db});assert.ok(!result.some(r=>r.platform==='NAVER'||r.platform==='COUPANG'));});
test('Naver channel and origin aliases retain the same factor',async()=>{const {db,tables}=fixture();tables.channel_products[1].raw_data.originProductNo='21';await seedSalesRules({db,productNo:'10',unit:'개',actor:'actor'});await saveSalesRule({db,value:{platform:'NAVER',productKey:'20',optionKey:'*',productNo:'10',unit:'개',factor:5,enabled:true},actor:'actor'});assert.deepEqual(tables.moaon_stock_sales_rules.filter(r=>r.platform==='NAVER').map(r=>r.factor),[5,5]);});
