const test=require('node:test'),assert=require('node:assert/strict');
const {checkCredentialInvariants}=require('../lib/tenancy/credential-invariants-check.js');
const codes=['CATALOG_VERSION','CATALOG_SEARCH_PATH','PROVIDER_TABLE','CONSTRAINT_SET','PRIMARY_KEY','TENANT_FOREIGN_KEY','MEMBER_FOREIGN_KEY','PROVIDER_CHECK','REVISION_CHECK','ENVELOPE_CHECK','UPDATED_AT_DEFAULT','TRUSTED_BUILTINS'];
const safeRows=()=>codes.map(code=>({code,present:true,valid:true}));
test('disabled invariants diagnostic has no transport side effects and failures always close safely',async()=>{
 let calls=0,closed=0;const factory=()=>{calls++;return {query:async()=>{throw Error('private-error');},close:async()=>{closed++;}};};
 assert.equal((await checkCredentialInvariants({env:{},createControlDatabase:factory})).status,'BLOCKED');assert.equal(calls,0);
 const result=await checkCredentialInvariants({env:{MOAON_CONTROL_DB_DIAGNOSTIC:'1'},createControlDatabase:factory});assert.equal(result.status,'BLOCKED');assert.equal(closed,1);assert.doesNotMatch(JSON.stringify(result),/private/);assert.ok(result.operationalChecks.every(x=>x.status==='UNVERIFIED'));
});
test('malformed catalog or close failure is blocked, unsupported version is explicit',async()=>{
 let closed=0;const env=Object.freeze({MOAON_CONTROL_DB_DIAGNOSTIC:'1'});
 for(const mode of ['malformed','close']){
  const result=await checkCredentialInvariants({env,createControlDatabase:()=>({query:async()=>({rows:mode==='malformed'?[{code:'private-row-secret'}]:safeRows()}),close:async()=>{closed++;if(mode==='close')throw Error('private-close-error');}})});
  assert.equal(result.status,'BLOCKED');assert.doesNotMatch(JSON.stringify(result),/private/);
 }assert.equal(closed,2);
 const result=await checkCredentialInvariants({env,createControlDatabase:()=>({query:async()=>({rows:safeRows().map(row=>row.code==='CATALOG_VERSION'?{...row,valid:false}:row)}),close:async()=>{}})});assert.equal(result.checks.find(x=>x.code==='CATALOG_VERSION').status,'UNSUPPORTED');assert.equal(result.status,'BLOCKED');
});
test('CLI emits safe JSON, rejects arguments before connection and closes bounded default transport',()=>{
 const {spawnSync}=require('node:child_process'),path=require('node:path');const cli=path.join(__dirname,'../scripts/check-moaon-credential-invariants.js');
 const env={SystemRoot:process.env.SystemRoot,TEMP:process.env.TEMP,TMP:process.env.TMP,MOAON_CONTROL_DB_DIAGNOSTIC:'1',MOAON_CONTROL_DB_HOST:'private-host.example',MOAON_CONTROL_DB_PORT:'5432',MOAON_CONTROL_DB_NAME:'private_db',MOAON_CONTROL_DB_PASSWORD:'private-password'};
 for(const args of [[],['--execute=private']]){
  const script=`const assert=require('node:assert/strict'),Module=require('node:module'),load=Module._load;let connects=0,closes=0;Module._load=function(name,...rest){if(name==='pg')return {Pool:class{constructor(c){assert.equal(c.connectionTimeoutMillis,5000);assert.equal(c.query_timeout,5000);}on(){}async connect(){connects++;throw Error('private-host-password');}async end(){closes++;}}};return load.call(this,name,...rest);};process.argv=['node',${JSON.stringify(cli)},...${JSON.stringify(args)}];require(${JSON.stringify(cli)});process.on('beforeExit',()=>{assert.equal(connects,${args.length?0:1});assert.equal(closes,${args.length?0:1});});`;
  const result=spawnSync(process.execPath,['-e',script],{env,encoding:'utf8',windowsHide:true,timeout:10000});assert.equal(result.status,1,result.stderr);assert.equal(result.stderr,'');assert.equal(JSON.parse(result.stdout).status,'BLOCKED');assert.doesNotMatch(result.stdout,/private|CONTROL_DATABASE_FAILURE/);
 }
 const success=`const assert=require('node:assert/strict'),Module=require('node:module'),load=Module._load;let closed=0;Module._load=function(name,...rest){if(name==='./control-database-config.js')return {createConfiguredControlDatabase:()=>({query:async()=>({rows:${JSON.stringify(safeRows())}}),close:async()=>{closed++;}})};return load.call(this,name,...rest);};process.argv=['node',${JSON.stringify(cli)}];require(${JSON.stringify(cli)});process.on('beforeExit',()=>assert.equal(closed,1));`;
 const result=spawnSync(process.execPath,['-e',success],{env,encoding:'utf8',windowsHide:true,timeout:10000});assert.equal(result.status,0,result.stderr);assert.equal(JSON.parse(result.stdout).status,'CREDENTIAL_INVARIANTS_MATCH_REQUIRES_OPERATIONS');assert.equal(result.stderr,'');
});
test('actual SQL candidate and conservative invariant drift on PostgreSQL 18 catalogs',async t=>{
 const {PGlite}=require('@electric-sql/pglite'),fs=require('node:fs/promises'),path=require('node:path');const db=new PGlite();t.after(()=>db.close());
 await db.exec(await fs.readFile(path.join(__dirname,'../lib/tenancy/sql/control-plane.sql'),'utf8'));
 await db.exec(await fs.readFile(path.join(__dirname,'../lib/tenancy/sql/credential-store.sql'),'utf8'));
 await db.exec('set search_path=pg_catalog');
 const run=()=>checkCredentialInvariants({env:{MOAON_CONTROL_DB_DIAGNOSTIC:'1'},createControlDatabase:()=>({query:sql=>db.query(sql),close:async()=>{}})});
 const state=(result,code)=>result.checks.find(x=>x.code===code)?.status;
 assert.equal((await run()).status,'CREDENTIAL_INVARIANTS_MATCH_REQUIRES_OPERATIONS');
 const drifts=[
  ['set search_path=public','CATALOG_SEARCH_PATH','set search_path=pg_catalog'],
  ['alter table moaon_control.provider_credentials drop constraint provider_credentials_revision_check;alter table moaon_control.provider_credentials add check(revision>=0)','REVISION_CHECK','alter table moaon_control.provider_credentials drop constraint provider_credentials_revision_check;alter table moaon_control.provider_credentials add check(revision>0)'],
  ['alter table moaon_control.provider_credentials drop constraint provider_credentials_revision_check;alter table moaon_control.provider_credentials add check(revision>0) not valid','REVISION_CHECK','alter table moaon_control.provider_credentials validate constraint provider_credentials_revision_check'],
  ['alter table moaon_control.provider_credentials drop constraint provider_credentials_revision_check;alter table moaon_control.provider_credentials add check(revision>0) not enforced','REVISION_CHECK','alter table moaon_control.provider_credentials drop constraint provider_credentials_revision_check;alter table moaon_control.provider_credentials add check(revision>0)'],
  ["alter table moaon_control.provider_credentials drop constraint provider_credentials_provider_check;alter table moaon_control.provider_credentials add check(provider in ('NAVER','CAFE24','COUPANG','EPOST','OTHER'))",'PROVIDER_CHECK',"alter table moaon_control.provider_credentials drop constraint provider_credentials_provider_check;alter table moaon_control.provider_credentials add check(provider in ('NAVER','CAFE24','COUPANG','EPOST'))"],
  ["alter table moaon_control.provider_credentials drop constraint provider_credentials_envelope_check;alter table moaon_control.provider_credentials add check(jsonb_typeof(envelope)='object' and octet_length(envelope::text)<=65536)",'ENVELOPE_CHECK',"alter table moaon_control.provider_credentials drop constraint provider_credentials_envelope_check;alter table moaon_control.provider_credentials add check(jsonb_typeof(envelope)='object' and octet_length(envelope::text)<=32768)"],
  ["alter table moaon_control.provider_credentials alter column updated_at set default '2000-01-01'::timestamptz",'UPDATED_AT_DEFAULT','alter table moaon_control.provider_credentials alter column updated_at set default pg_catalog.clock_timestamp()'],
  ['alter table moaon_control.provider_credentials drop constraint provider_credentials_tenant_id_fkey;alter table moaon_control.provider_credentials add foreign key(tenant_id) references moaon_control.tenants(id) on delete cascade','TENANT_FOREIGN_KEY','alter table moaon_control.provider_credentials drop constraint provider_credentials_tenant_id_fkey;alter table moaon_control.provider_credentials add foreign key(tenant_id) references moaon_control.tenants(id)'],
  ['alter table moaon_control.provider_credentials add unique(updated_by)','CONSTRAINT_SET','alter table moaon_control.provider_credentials drop constraint provider_credentials_updated_by_key'],
  ['alter table moaon_control.provider_credentials add constraint extra_check check(true)','CONSTRAINT_SET','alter table moaon_control.provider_credentials drop constraint extra_check'],
  ['alter table moaon_control.provider_credentials drop constraint provider_credentials_tenant_id_updated_by_fkey;alter table moaon_control.provider_credentials add foreign key(tenant_id,updated_by) references moaon_control.memberships(tenant_id,user_id) not valid','MEMBER_FOREIGN_KEY','alter table moaon_control.provider_credentials validate constraint provider_credentials_tenant_id_updated_by_fkey'],
  ['alter table moaon_control.provider_credentials drop constraint provider_credentials_pkey;alter table moaon_control.provider_credentials add primary key(provider,tenant_id)','PRIMARY_KEY','alter table moaon_control.provider_credentials drop constraint provider_credentials_pkey;alter table moaon_control.provider_credentials add primary key(tenant_id,provider)'],
  ['alter table moaon_control.provider_credentials drop constraint provider_credentials_pkey;alter table moaon_control.provider_credentials add primary key(tenant_id,provider) include(updated_by)','PRIMARY_KEY','alter table moaon_control.provider_credentials drop constraint provider_credentials_pkey;alter table moaon_control.provider_credentials add primary key(tenant_id,provider)'],
  ['alter table moaon_control.provider_credentials drop constraint provider_credentials_pkey;alter table moaon_control.provider_credentials add primary key(tenant_id,provider) deferrable','PRIMARY_KEY','alter table moaon_control.provider_credentials drop constraint provider_credentials_pkey;alter table moaon_control.provider_credentials add primary key(tenant_id,provider)'],
  ['create table moaon_control.wrong_tenants(id uuid primary key);alter table moaon_control.provider_credentials drop constraint provider_credentials_tenant_id_fkey;alter table moaon_control.provider_credentials add foreign key(tenant_id) references moaon_control.wrong_tenants(id)','TENANT_FOREIGN_KEY','alter table moaon_control.provider_credentials drop constraint provider_credentials_tenant_id_fkey;alter table moaon_control.provider_credentials add foreign key(tenant_id) references moaon_control.tenants(id);drop table moaon_control.wrong_tenants'],
 ];
 for(const [change,code,undo] of drifts){await db.exec(change);const result=await run();assert.equal(state(result,code),'INVALID',JSON.stringify(result));await db.exec(undo);assert.equal((await run()).status,'CREDENTIAL_INVARIANTS_MATCH_REQUIRES_OPERATIONS',undo);}
 await db.exec("create function public.clock_timestamp() returns timestamptz language plpgsql as $$begin raise exception 'must not execute';end$$;alter table moaon_control.provider_credentials alter column updated_at set default public.clock_timestamp()");
 assert.equal(state(await run(),'TRUSTED_BUILTINS'),'INVALID');
 await db.exec('alter table moaon_control.provider_credentials alter column updated_at set default pg_catalog.clock_timestamp()');assert.equal((await run()).status,'CREDENTIAL_INVARIANTS_MATCH_REQUIRES_OPERATIONS');
 await db.exec("create function public.fake_gt(integer,integer) returns boolean language plpgsql as $$begin raise exception 'must not execute';end$$;create operator public.> (function=public.fake_gt,leftarg=integer,rightarg=integer);alter table moaon_control.provider_credentials drop constraint provider_credentials_revision_check;alter table moaon_control.provider_credentials add check(revision operator(public.>) 0)");assert.equal(state(await run(),'TRUSTED_BUILTINS'),'INVALID');
});
