const test=require('node:test'),assert=require('node:assert/strict');
const {checkCredentialContract}=require('../lib/tenancy/credential-contract-check.js');
const codes=['RUNTIME_ROLE','PROVIDER_COLUMNS','PROVIDER_CREDENTIALS_ACL','ACCOUNT_STATE_ACL','DASHBOARD_USERS_ACL','DASHBOARD_SESSIONS_ACL'];
const rows=()=>codes.map(code=>({code,present:true,valid:true}));
test('opt-in, fixed catalog query, no raw values and mandatory close',async()=>{
 let factories=0,closed=0,queries=0;const make=()=>{factories++;return {query:async sql=>{queries++;assert.match(sql,/pg_catalog\.pg_attribute/);return {rows:rows()};},close:async()=>{closed++;}};};
 for(const flag of [undefined,'','0','yes'])assert.equal((await checkCredentialContract({env:{MOAON_CONTROL_DB_DIAGNOSTIC:flag},createControlDatabase:make})).status,'BLOCKED');assert.equal(factories,0);
 const env=Object.freeze({MOAON_CONTROL_DB_DIAGNOSTIC:'1'});const result=await checkCredentialContract({env,createControlDatabase:make});assert.equal(result.status,'CREDENTIAL_CONTRACT_MATCHES_REQUIRES_OPERATIONS');assert.equal(queries,1);assert.equal(closed,1);assert.ok(result.operationalChecks.every(x=>x.status==='UNVERIFIED'));
 for(const step of ['query','shape','close']){const result=await checkCredentialContract({env,createControlDatabase:()=>({query:async()=>{if(step==='query')throw Error('private-secret-host');return {rows:step==='shape'?[{code:'private-row'}]:rows()};},close:async()=>{closed++;if(step==='close')throw Error('private-close');}})});assert.equal(result.status,'BLOCKED');assert.doesNotMatch(JSON.stringify(result),/private/);}assert.equal(closed,4);
});
test('real catalog contract detects column and effective ACL drift without reading table data',async t=>{
 const {PGlite}=require('@electric-sql/pglite');const db=new PGlite();t.after(()=>db.close());
 const direct=()=>checkCredentialContract({env:{MOAON_CONTROL_DB_DIAGNOSTIC:'1'},createControlDatabase:()=>({query:sql=>db.query(sql),close:async()=>{}})});
 assert.equal((await direct()).checks.find(x=>x.code==='RUNTIME_ROLE').status,'MISSING');
 const fs=require('node:fs/promises'),path=require('node:path');
 const {setupCredentialAuth}=require('./helpers/credential-auth-fixture.js');await setupCredentialAuth(db);
 for(const file of ['control-plane.sql','credential-store.sql','control-role.sql','credential-runtime-role.sql'])await db.exec(await fs.readFile(path.join(__dirname,'../lib/tenancy/sql',file),'utf8'));
 await db.exec('alter table public.dashboard_sessions add column extra text');
 const run=async()=>{await db.exec('set session authorization moaon_control_app');try{return await checkCredentialContract({env:{MOAON_CONTROL_DB_DIAGNOSTIC:'1'},createControlDatabase:()=>({query:sql=>db.query(sql),close:async()=>{}})});}finally{await db.exec('set session authorization postgres');}};
 const state=(result,code)=>result.checks.find(x=>x.code===code)?.status;
 assert.equal((await run()).status,'CREDENTIAL_CONTRACT_MATCHES_REQUIRES_OPERATIONS');
 assert.equal((await direct()).checks.find(x=>x.code==='RUNTIME_ROLE').status,'INVALID');
 const drifts=[
  ['alter table moaon_control.provider_credentials alter column revision drop not null','PROVIDER_COLUMNS','alter table moaon_control.provider_credentials alter column revision set not null'],
  ['alter table moaon_control.provider_credentials alter column revision type bigint','PROVIDER_COLUMNS','alter table moaon_control.provider_credentials alter column revision type integer'],
  ['alter table moaon_control.provider_credentials add column private_extra text','PROVIDER_COLUMNS','alter table moaon_control.provider_credentials drop column private_extra'],
  ['alter table moaon_control.provider_credentials alter column updated_at drop default','PROVIDER_COLUMNS','alter table moaon_control.provider_credentials alter column updated_at set default clock_timestamp()'],
  ['alter table moaon_control.provider_credentials alter column revision add generated by default as identity','PROVIDER_COLUMNS','alter table moaon_control.provider_credentials alter column revision drop identity'],
  ['grant select(envelope) on moaon_control.provider_credentials to moaon_control_app','PROVIDER_CREDENTIALS_ACL','revoke select(envelope) on moaon_control.provider_credentials from moaon_control_app'],
  ['grant select on moaon_auth.account_state to moaon_control_app','ACCOUNT_STATE_ACL','revoke select on moaon_auth.account_state from moaon_control_app;grant select(user_id,blocked) on moaon_auth.account_state to moaon_control_app'],
  ['grant select(user_id) on public.dashboard_users to public','DASHBOARD_USERS_ACL','revoke select(user_id) on public.dashboard_users from public'],
  ['grant select(extra) on public.dashboard_sessions to moaon_control_app','DASHBOARD_SESSIONS_ACL','revoke select(extra) on public.dashboard_sessions from moaon_control_app'],
  ['revoke update(id) on public.dashboard_sessions from moaon_control_app','DASHBOARD_SESSIONS_ACL','grant update(id) on public.dashboard_sessions to moaon_control_app'],
  ['grant delete on moaon_control.provider_credentials to moaon_control_app','PROVIDER_CREDENTIALS_ACL','revoke delete on moaon_control.provider_credentials from moaon_control_app'],
  ['grant truncate on moaon_control.provider_credentials to moaon_control_app','PROVIDER_CREDENTIALS_ACL','revoke truncate on moaon_control.provider_credentials from moaon_control_app'],
  ['grant trigger on moaon_control.provider_credentials to moaon_control_app','PROVIDER_CREDENTIALS_ACL','revoke trigger on moaon_control.provider_credentials from moaon_control_app'],
  ['grant select(user_id) on public.dashboard_users to moaon_control_app with grant option','DASHBOARD_USERS_ACL','revoke grant option for select(user_id) on public.dashboard_users from moaon_control_app'],
  ['grant select(revision) on moaon_control.provider_credentials to moaon_control_app with grant option','PROVIDER_CREDENTIALS_ACL','revoke grant option for select(revision) on moaon_control.provider_credentials from moaon_control_app'],
 ];
 for(const [change,code,undo] of drifts){await db.exec(change);const result=await run();assert.equal(result.status,'BLOCKED',change);assert.equal(state(result,code),'INVALID',change);assert.doesNotMatch(JSON.stringify(result),/private_extra/);await db.exec(undo);assert.equal((await run()).status,'CREDENTIAL_CONTRACT_MATCHES_REQUIRES_OPERATIONS',undo);}
 await db.exec('alter table moaon_control.provider_credentials drop column envelope');assert.equal(state(await run(),'PROVIDER_COLUMNS'),'INVALID');
 await db.exec('alter table moaon_control.provider_credentials add column envelope jsonb not null;grant insert(envelope),update(envelope) on moaon_control.provider_credentials to moaon_control_app');assert.equal((await run()).status,'CREDENTIAL_CONTRACT_MATCHES_REQUIRES_OPERATIONS');
 await db.exec('alter table moaon_control.provider_credentials drop column revision;alter table moaon_control.provider_credentials add column revision integer generated always as (1) stored not null');assert.equal(state(await run(),'PROVIDER_COLUMNS'),'INVALID');
 await db.exec('drop table public.dashboard_sessions');assert.equal(state(await run(),'DASHBOARD_SESSIONS_ACL'),'MISSING');
});
test('CLI has bounded hidden lifecycle, sanitized failures and rejects args before connecting',()=>{
 const {spawnSync}=require('node:child_process'),path=require('node:path');const cli=path.join(__dirname,'../scripts/check-moaon-credential-contract.js');
 const env={SystemRoot:process.env.SystemRoot,TEMP:process.env.TEMP,TMP:process.env.TMP,MOAON_CONTROL_DB_DIAGNOSTIC:'1',MOAON_CONTROL_DB_HOST:'private-host.example',MOAON_CONTROL_DB_PORT:'5432',MOAON_CONTROL_DB_NAME:'private_database',MOAON_CONTROL_DB_PASSWORD:'private-password'};
 for(const args of [[],['--sql=private-data']]){
  const code=`const assert=require('node:assert/strict'),Module=require('node:module'),load=Module._load;let connects=0,closes=0;Module._load=function(name,...rest){if(name==='pg')return {Pool:class {constructor(config){assert.equal(config.connectionTimeoutMillis,5000);assert.equal(config.query_timeout,5000);}on(){}async connect(){connects++;throw Error('private-host-password');}async end(){closes++;}}};return load.call(this,name,...rest);};process.argv=['node',${JSON.stringify(cli)},...${JSON.stringify(args)}];require(${JSON.stringify(cli)});process.on('beforeExit',()=>{assert.equal(connects,${args.length?0:1});assert.equal(closes,${args.length?0:1});});`;
  const result=spawnSync(process.execPath,['-e',code],{env,encoding:'utf8',windowsHide:true,timeout:10000});assert.equal(result.status,1,result.stderr);assert.equal(result.stderr,'');assert.equal(JSON.parse(result.stdout).status,'BLOCKED');assert.doesNotMatch(result.stdout,/private|CONTROL_DATABASE_FAILURE/);
 }
 const success=`const assert=require('node:assert/strict'),Module=require('node:module'),load=Module._load;let closed=0;Module._load=function(name,...rest){if(name==='./control-database-config.js')return {createConfiguredControlDatabase:()=>({query:async()=>({rows:${JSON.stringify(rows())}}),close:async()=>{closed++;}})};return load.call(this,name,...rest);};process.argv=['node',${JSON.stringify(cli)}];require(${JSON.stringify(cli)});process.on('beforeExit',()=>assert.equal(closed,1));`;
 const result=spawnSync(process.execPath,['-e',success],{env,encoding:'utf8',windowsHide:true,timeout:10000});assert.equal(result.status,0,result.stderr);assert.equal(JSON.parse(result.stdout).status,'CREDENTIAL_CONTRACT_MATCHES_REQUIRES_OPERATIONS');assert.equal(result.stderr,'');
});
