'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createMarketAiRequest,validMarketInput}=require('../lib/tenancy/workspace-market-ai-request');
const {resolveTenantContext}=require('../lib/tenancy/context');
const tenant='a3452bca-e259-40ed-a93d-b8bcc5c1b9e0',url=`https://harin-cafe24-sync.vercel.app/api/moaon/businesses/${tenant}/market-ai`,headers={cookie:'harin_dashboard_session=a.b',origin:'https://harin-cafe24-sync.vercel.app','content-type':'application/json'},input={requestId:'12345678-1234-4123-8123-123456789abc',kind:'TREND_EXPLANATION',query:'작두콩차',days:30};
const ctx=(id=tenant,session='session')=>resolveTenantContext({session:{id:session,userId:'owner',expiresAt:'2099-01-01T00:00:00Z'},requestedTenantId:id},{now:()=>new Date(),findMembership:async()=>({userId:'owner',tenantId:id,status:'ACTIVE',role:'OWNER',version:1})});
const req=(v=input,h=headers)=>new Request(url,{method:'POST',headers:h,body:JSON.stringify(v)});
function setup(options={}){let calls=0;const handle=createMarketAiRequest({resolveContext:()=>ctx(),configuration:()=>({status:'DISABLED'}),createService:()=>({generateRun:async()=>{calls++;return {runId:input.requestId,status:'SUCCEEDED',snapshot:{period:{start:'2026-08-01',end:'2026-08-30'},sources:[],metrics:{}},output:{cards:[],answer:'공개 추이',nextChecks:[]}};}}),...options});return {handle,calls:()=>calls};}
test('GET readiness makes no generation, POST validates closed request shape',async()=>{const s=setup();assert.equal((await s.handle(new Request(url,{headers}))).status,200);assert.equal(s.calls(),0);assert.equal((await s.handle(req())).status,200);assert.equal(s.calls(),1);for(const v of [{...input,memo:'secret'},{...input,query:'test@example.com'},{...input,days:10},{...input,kind:'FREE_QUESTION'},{...input,query:'010-1234-5678'}]){assert.equal(validMarketInput(v),false);assert.equal((await s.handle(req(v))).status,400);}assert.equal(s.calls(),1);});
test('origin/auth/tenant/session fence and size limits',async()=>{const s=setup();assert.equal((await s.handle(req(input,{...headers,origin:'https://evil.example'}))).status,403);assert.equal((await s.handle(req(input,{'content-type':'application/json',origin:headers.origin}))).status,401);assert.equal((await s.handle(req({query:'a'.repeat(3000)}))).status,413);const other=setup({resolveContext:()=>ctx('12345678-1234-4123-8123-123456789abc')});assert.equal((await other.handle(req())).status,403);let n=0;const changed=setup({resolveContext:()=>ctx(tenant,++n===1?'before':'after')});assert.equal((await changed.handle(req())).status,409);});
test('absolute deadline returns no late output',async()=>{const s=setup({timeoutMs:15,createService:()=>({generateRun:()=>new Promise(()=>{})})});assert.equal((await s.handle(req())).status,504);});
