'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createWorkspaceAiInsightsRequest,guardWorkspaceAiInsightsRequest}=require('../lib/tenancy/workspace-ai-insights-request');
const id='a3452bca-e259-40ed-a93d-b8bcc5c1b9e0',url=`https://harin-cafe24-sync.vercel.app/api/moaon/businesses/${id}/insights/ai`;
const headers={cookie:'harin_dashboard_session=a.b',origin:'https://harin-cafe24-sync.vercel.app','content-type':'application/json'};
const {resolveTenantContext}=require('../lib/tenancy/context');
const ctx={tenantId:id,userId:'owner',sessionId:'session',role:'OWNER',membershipVersion:1};
const issue=async(value=ctx)=>resolveTenantContext({session:{id:value.sessionId,userId:value.userId,expiresAt:'2099-01-01T00:00:00Z'},requestedTenantId:value.tenantId},{now:()=>new Date(),findMembership:async()=>({userId:value.userId,tenantId:value.tenantId,status:'ACTIVE',role:value.role,version:value.membershipVersion})});
const req=(body={},opts={})=>new Request(url,{method:'POST',headers,body:JSON.stringify(body),...opts});
const input={requestId:'12345678-1234-4123-8123-123456789abc',reportIds:['report-a'],kind:'SUMMARY',question:''};
function setup(options={}){let calls=0;const handle=createWorkspaceAiInsightsRequest({resolveContext:async()=>issue(),createService:({assertCurrentContext})=>({generateRun:async()=>{await assertCurrentContext();calls++;return {status:'READY'};},listRuns:async()=>[],deleteRun:async()=>({deleted:true})}),configuration:()=>({status:'DISABLED'}),...options});return {handle,calls:()=>calls};}
test('AI guard rejects origin/method/query and missing auth before service',async()=>{for(const request of [req(input,{headers:{...headers,origin:'https://evil.example'}}),req(input,{headers:{origin:headers.origin,'content-type':'application/json'}}),new Request(url+'?x=1',{headers}),new Request(url,{method:'PUT',headers})])assert.ok(guardWorkspaceAiInsightsRequest(request).response);});
test('AI request validates body and only POST generates',async()=>{const s=setup();assert.equal((await s.handle(req(input))).status,200);assert.equal(s.calls(),1);assert.equal((await s.handle(new Request(url,{headers}))).status,200);assert.equal(s.calls(),1);assert.equal((await s.handle(req({...input,provider:'OPENAI'}))).status,400);assert.equal(s.calls(),1);assert.equal((await s.handle(req({x:'x'.repeat(9000)}))).status,413);});
test('AI route prevents cross-tenant data and rechecks session before return',async()=>{const s=setup({resolveContext:async()=>issue({...ctx,tenantId:'12345678-1234-4123-8123-123456789abc'})});assert.equal((await s.handle(req(input))).status,403);assert.equal(s.calls(),0);let checks=0;const changed=setup({resolveContext:async()=>issue({...ctx,sessionId:++checks===1?'session':'new-session'})});assert.equal((await changed.handle(req(input))).status,409);assert.equal(changed.calls(),0);});
test('AI deadline aborts slow work and never releases late results',async()=>{let signal;const s=setup({timeoutMs:15,createService:o=>{signal=o.signal;return {generateRun:async()=>new Promise(()=>{})};}});assert.equal((await s.handle(req(input))).status,504);assert.equal(signal.aborted,true);});
