'use client';

import { useEffect, useMemo, useState } from 'react';
import { HarinBadge, HarinButton, HarinCard, HarinEmptyState, HarinPictogram, HarinProgressiveDetails, HarinSectionHeading, HarinStateCard } from '../../../_design-system/harin-ui.js';

const statusMeta={VERIFIED:['확인 완료','success'],REVIEW_REQUIRED:['검토 필요','warning'],DRAFT:['초안','neutral'],BLOCKED:['사용 중지','danger']};
const claimMeta={ALLOWED:['사용 가능','success'],VERIFY:['표현 확인','warning'],BLOCKED:['사용 금지','danger']};
const platformNames={NAVER:'네이버',CAFE24:'Cafe24',COUPANG:'쿠팡',OTHER:'기타'};
const appealNames={DIFFERENTIATION:'차별점',TRUST:'신뢰',CONVENIENCE:'편의',VALUE:'가격·구성',USAGE:'사용 상황',OTHER:'기타'};
const blankCompetitor={platform:'NAVER',competitor_name:'',product_name:'',product_url:'',price_won:'',package_quantity:'',package_unit:'',strengths:[],comparison_notes:'',evidence_ids:[],owner_confirmed:false};
const blankReview={competitor_id:'',review_set_name:'',review_period_start:'',review_period_end:'',sample_size:'',pain_points:[],praised_points:[],purchase_reasons:[],rejection_reasons:[],evidence_ids:[],owner_confirmed:false};
const blankAppeal={appeal_type:'DIFFERENTIATION',title:'',customer_problem:'',own_resolution:'',proof_summary:'',claim_text:'',competitor_review_ids:[],competitor_pain_evidence_ids:[],own_resolution_evidence_ids:[],owner_confirmed:false};
const lines=value=>String(value||'').split(/\r?\n/u).map(item=>item.trim()).filter(Boolean);
const joinLines=value=>Array.isArray(value)?value.join('\n'):'';
const money=value=>value==null?'확인 필요':`${Number(value).toLocaleString('ko-KR')}원`;

export default function CompetitionWorkbench({projectId,productName}){
  const endpoint=`/api/market-intelligence/projects/${projectId}/competition`;
  const [data,setData]=useState(null),[loading,setLoading]=useState(true),[working,setWorking]=useState(''),[message,setMessage]=useState('');
  const [competitorDraft,setCompetitorDraft]=useState(blankCompetitor),[reviewDraft,setReviewDraft]=useState(blankReview),[appealDraft,setAppealDraft]=useState(blankAppeal);
  async function load(){setLoading(true);try{const response=await fetch(endpoint,{cache:'no-store'}),result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'경쟁 분석 자료 조회 실패');setData(result);}catch(error){setMessage(`확인 필요 · ${error.message}`);}finally{setLoading(false);}}
  useEffect(()=>{load();},[projectId]);
  async function run(action,payload){setWorking(action);setMessage('');try{const response=await fetch(endpoint,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({action,...payload})}),result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'경쟁 분석 작업 실패');setData(result);if(action==='SAVE_COMPETITOR')setCompetitorDraft(blankCompetitor);if(action==='SAVE_COMPETITOR_REVIEW')setReviewDraft(blankReview);if(action==='SAVE_APPEAL')setAppealDraft(blankAppeal);setMessage(result.message);}catch(error){setMessage(`판단 보류 · ${error.message}`);}finally{setWorking('');}}
  const competitorMap=useMemo(()=>new Map((data?.competitors||[]).map(item=>[item.id,item])),[data?.competitors]);
  const verifiedReviews=useMemo(()=>(data?.reviews||[]).filter(item=>item.status==='VERIFIED'),[data?.reviews]);
  const painSignals=useMemo(()=>[...new Set(verifiedReviews.flatMap(item=>item.pain_points||[]))].slice(0,12),[verifiedReviews]);
  const setEvidence=(draft,setDraft,field,id,checked)=>setDraft(current=>({...current,[field]:checked?[...new Set([...(current[field]||[]),id])]:(current[field]||[]).filter(item=>item!==id)}));
  if(loading)return <HarinCard className="marketCompetitionLoading"><HarinPictogram icon="search" tone="pink"/><span><b>{productName} 경쟁근거를 여는 중이에요…</b><small>다른 상품 프로젝트의 경쟁자료는 섞지 않습니다.</small></span></HarinCard>;
  if(!data)return <HarinEmptyState icon="search" title="경쟁 분석 자료를 불러오지 못했어요" description={message||'잠시 뒤 다시 시도해주세요.'}/>;
  const summary=data.summary;
  return <section className="marketCompetitionWorkbench">
    <HarinSectionHeading eyebrow="COMPETITOR · REVIEW · APPEAL" title="경쟁상품과 소구점" description="경쟁상품의 반복 불편과 우리 상품의 해결 근거를 양쪽으로 확인해요." icon="search" aside={<HarinBadge tone={summary.readiness==='READY'?'success':'warning'}>{summary.readiness==='READY'?'차별화 준비':'판단 보류'}</HarinBadge>}/>
    <section className="marketCompetitionKpis"><HarinStateCard icon="store" label="확인된 경쟁상품" value={`${summary.competitors_verified}/${summary.competitors_total}`} description="상품 Evidence와 사장님 확인 기준"/><HarinStateCard icon="customer" label="검증 리뷰 표본" value={`${summary.review_sample.toLocaleString('ko-KR')}건`} description={`${summary.review_sets_verified}개 경쟁 리뷰 묶음`}/><HarinStateCard icon="warning" label="확인된 반복 불편" value={`${summary.pain_signals_verified}개`} description="검증 리뷰 집계에서만 계산"/><HarinStateCard tone={summary.readiness==='READY'?'success':'warning'} icon="target" label="확정 소구점" value={`${summary.appeals_verified}개`} description={summary.readiness_message}/></section>
    {message?<div className="marketDataMessage" role="status"><HarinPictogram icon="sparkles" tone="pink" size={18}/><span>{message}</span></div>:null}
    <section className="marketCompetitionColumns"><HarinCard><HarinSectionHeading eyebrow="COMPETITOR SNAPSHOT" title="경쟁상품" description="가격이 없으면 0원으로 바꾸지 않고 확인 필요로 표시해요." icon="store" aside={<HarinBadge>{data.competitors.length}개</HarinBadge>}/>{data.competitors.length?<div className="marketCompetitorList">{data.competitors.map(item=>{const meta=statusMeta[item.status]||statusMeta.DRAFT;return <article key={item.id}><header><HarinBadge tone="info">{platformNames[item.platform]}</HarinBadge><HarinBadge tone={meta[1]}>{meta[0]}</HarinBadge></header><b>{item.competitor_name}</b><h3>{item.product_name}</h3><footer><span>{money(item.price_won)}</span><small>{item.package_quantity?`${Number(item.package_quantity).toLocaleString('ko-KR')} ${item.package_unit||'개'}`:'구성 확인 필요'}</small></footer></article>;})}</div>:<HarinEmptyState icon="store" title="확인된 경쟁상품이 없어요" description="자료실에서 경쟁상품 화면이나 보고서를 Evidence로 검수한 뒤 추가해주세요."/>}</HarinCard><HarinCard><HarinSectionHeading eyebrow="PRIVACY-SAFE REVIEW" title="경쟁 리뷰 신호" description="리뷰 원문과 고객정보 대신 표본과 반복 신호만 저장해요." icon="customer" aside={<HarinBadge>{data.reviews.length}개 묶음</HarinBadge>}/>{data.reviews.length?<div className="marketCompetitorReviewList">{data.reviews.map(review=>{const meta=statusMeta[review.status]||statusMeta.DRAFT,competitor=competitorMap.get(review.competitor_id);return <article key={review.id}><HarinPictogram icon="customer" tone="pink" size={18}/><span><small>{competitor?.competitor_name||'경쟁상품'}</small><b>{review.review_set_name}</b><p>{review.pain_points?.[0]||'반복 불편을 더 확인해주세요.'}</p></span><div><strong>{review.sample_size.toLocaleString('ko-KR')}건</strong><HarinBadge tone={meta[1]}>{meta[0]}</HarinBadge></div></article>;})}</div>:<HarinEmptyState icon="customer" title="경쟁 리뷰 집계가 없어요" description="검증된 경쟁상품을 먼저 만들고 리뷰 표본을 집계해주세요."/>}</HarinCard></section>
    <HarinCard className="marketAppealBridge"><HarinSectionHeading eyebrow="PAIN → RESOLUTION → PROOF" title="불편에서 소구점까지" description="양쪽 근거가 모두 있는지 한눈에 비교합니다." icon="target" aside={<HarinBadge tone={summary.appeals_verified?'success':'warning'}>{summary.appeals_verified?`${summary.appeals_verified}개 확정`:'근거 연결 전'}</HarinBadge>}/><div className="marketAppealFlow"><section><header><HarinPictogram icon="warning" tone="pink"/><span><small>경쟁 리뷰 불편</small><b>고객이 반복해서 말한 문제</b></span></header>{painSignals.length?<ul>{painSignals.map(item=><li key={item}>{item}</li>)}</ul>:<p>검증 리뷰 표본이 모이면 여기에 반복 불편이 나타나요.</p>}</section><i aria-hidden="true">→</i><section><header><HarinPictogram icon="product" tone="lavender"/><span><small>우리 상품 소구점</small><b>해결 근거가 연결된 문구</b></span></header>{data.appeals.length?<div>{data.appeals.map(appeal=>{const meta=statusMeta[appeal.status]||statusMeta.DRAFT,claim=claimMeta[appeal.claim_status]||claimMeta.VERIFY;return <article key={appeal.id}><span><b>{appeal.title}</b><small>{appeal.claim_text}</small></span><div><HarinBadge tone={claim[1]}>{claim[0]}</HarinBadge><HarinBadge tone={meta[1]}>{meta[0]}</HarinBadge></div></article>;})}</div>:<p>경쟁 불편 Evidence와 우리 해결 Evidence를 함께 연결해야 표시돼요.</p>}</section></div></HarinCard>
    <HarinProgressiveDetails eyebrow="경쟁상품 추가" title="실제 경쟁상품과 가격 확인" description="상품 페이지·보고서 등 검증 Evidence를 연결해요." count={data.evidence.length?`근거 ${data.evidence.length}개`:'근거 먼저 필요'}><CompetitorForm draft={competitorDraft} setDraft={setCompetitorDraft} evidence={data.evidence} working={working} onEvidence={(id,checked)=>setEvidence(competitorDraft,setCompetitorDraft,'evidence_ids',id,checked)} onSubmit={()=>run('SAVE_COMPETITOR',{competitor:competitorDraft})}/></HarinProgressiveDetails>
    <HarinProgressiveDetails eyebrow="경쟁 리뷰 집계" title="반복 불편과 만족을 숫자로 확인" description="검증된 경쟁상품의 리뷰 원문은 저장하지 않습니다." count={data.competitors.length?`경쟁상품 ${data.competitors.length}개`:'경쟁상품 먼저 필요'}><ReviewForm draft={reviewDraft} setDraft={setReviewDraft} competitors={data.competitors} evidence={data.evidence} working={working} onEvidence={(id,checked)=>setEvidence(reviewDraft,setReviewDraft,'evidence_ids',id,checked)} onSubmit={()=>run('SAVE_COMPETITOR_REVIEW',{review:reviewDraft})}/></HarinProgressiveDetails>
    <HarinProgressiveDetails eyebrow="소구점 연결" title="경쟁 불편과 우리 해결 근거를 한 쌍으로" description="한쪽 근거만 있거나 위험한 표현이면 확인 완료가 되지 않습니다." count={verifiedReviews.length?`검증 리뷰 ${verifiedReviews.length}개`:'검증 리뷰 필요'}><AppealForm draft={appealDraft} setDraft={setAppealDraft} reviews={verifiedReviews} competitors={competitorMap} evidence={data.evidence} working={working} onEvidence={(field,id,checked)=>setEvidence(appealDraft,setAppealDraft,field,id,checked)} onSubmit={()=>run('SAVE_APPEAL',{appeal:appealDraft})}/></HarinProgressiveDetails>
    <HarinProgressiveDetails eyebrow="안전 규칙" title="왜 차별점이 아직 확정되지 않나요?" description="경쟁 불편과 우리 해결을 각각 검증해야 과장 없는 소구점이 됩니다." count={`${data.evidence.length}개 검증 Evidence`}><div className="marketProfileRules"><article><HarinPictogram icon="warning" tone="pink"/><span><b>경쟁 불편 근거</b><p>검증된 경쟁 리뷰 표본과 Evidence가 필요해요.</p></span></article><article><HarinPictogram icon="shield" tone="mint"/><span><b>우리 해결 근거</b><p>상품 기준선·상세자료에서 확인된 Evidence가 필요해요.</p></span></article><article><HarinPictogram icon="ai" tone="lavender"/><span><b>표현 안전 검사</b><p>치료·완치·최고 표현은 중지하고 건강 표현은 확인 대기로 둬요.</p></span></article></div></HarinProgressiveDetails>
  </section>;
}

function EvidenceChoices({title,description,evidence,selected,onChange}){return <fieldset className="marketEvidenceChoices"><legend>{title}</legend>{description?<p>{description}</p>:null}{evidence.length?<div>{evidence.map(item=><label key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={event=>onChange(item.id,event.target.checked)}/><span><b>{item.label}</b><small>{item.value_text}</small></span></label>)}</div>:<HarinEmptyState icon="database" title="연결할 검증 Evidence가 없어요" description="자료실에서 출처를 확인 완료해주세요."/>}</fieldset>;}
function OwnerCheck({checked,onChange,text}){return <label className="marketOwnerCheck"><input type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)}/><span><b>{text}</b><small>필요한 양쪽 근거가 없으면 검토 필요 상태를 유지합니다.</small></span></label>;}
function CompetitorForm({draft,setDraft,evidence,working,onEvidence,onSubmit}){const update=(field,value)=>setDraft(current=>({...current,[field]:value}));return <form className="marketProfileForm" onSubmit={event=>{event.preventDefault();onSubmit();}}><div className="marketProfileFields"><label><span>플랫폼</span><select value={draft.platform} onChange={event=>update('platform',event.target.value)}>{Object.entries(platformNames).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><label><span>경쟁 브랜드</span><input maxLength="160" value={draft.competitor_name} onChange={event=>update('competitor_name',event.target.value)} placeholder="브랜드 또는 판매자"/></label><label className="wide"><span>경쟁상품 이름</span><input maxLength="240" value={draft.product_name} onChange={event=>update('product_name',event.target.value)} placeholder="실제 판매상품 이름"/></label><label className="wide"><span>상품 주소</span><input type="url" maxLength="1000" value={draft.product_url} onChange={event=>update('product_url',event.target.value)} placeholder="https://"/></label><label><span>확인한 판매가</span><input type="number" min="0" value={draft.price_won} onChange={event=>update('price_won',event.target.value)} placeholder="모르면 비워두기"/></label><label><span>구성 수량·단위</span><div className="marketPackageInputs"><input aria-label="구성 수량" type="number" min="0.001" step="0.001" value={draft.package_quantity} onChange={event=>update('package_quantity',event.target.value)} placeholder="30"/><input aria-label="구성 단위" maxLength="40" value={draft.package_unit} onChange={event=>update('package_unit',event.target.value)} placeholder="티백"/></div></label><label><span>확인된 강점 · 한 줄에 하나</span><textarea value={joinLines(draft.strengths)} onChange={event=>update('strengths',lines(event.target.value))}/></label><label><span>비교 메모</span><textarea maxLength="2000" value={draft.comparison_notes} onChange={event=>update('comparison_notes',event.target.value)}/></label></div><EvidenceChoices title="경쟁상품 확인 Evidence" description="가격·구성·상품 존재를 확인한 같은 상품 프로젝트 근거" evidence={evidence} selected={draft.evidence_ids} onChange={onEvidence}/><OwnerCheck checked={draft.owner_confirmed} onChange={checked=>update('owner_confirmed',checked)} text="이 경쟁상품과 연결 근거를 직접 확인했어요"/><HarinButton variant="primary" icon="check" type="submit" disabled={Boolean(working)}>{working==='SAVE_COMPETITOR'?'경쟁상품 저장 중…':'경쟁상품 저장'}</HarinButton></form>;}
function ReviewForm({draft,setDraft,competitors,evidence,working,onEvidence,onSubmit}){const update=(field,value)=>setDraft(current=>({...current,[field]:value}));return <form className="marketProfileForm" onSubmit={event=>{event.preventDefault();onSubmit();}}><div className="marketProfileFields"><label><span>경쟁상품</span><select value={draft.competitor_id} onChange={event=>update('competitor_id',event.target.value)}><option value="">선택해주세요</option>{competitors.map(item=><option value={item.id} key={item.id}>{item.competitor_name} · {item.product_name}</option>)}</select></label><label><span>리뷰 묶음 이름</span><input maxLength="160" value={draft.review_set_name} onChange={event=>update('review_set_name',event.target.value)} placeholder="예: 최근 90일 구매후기"/></label><label><span>시작일</span><input type="date" value={draft.review_period_start} onChange={event=>update('review_period_start',event.target.value)}/></label><label><span>종료일</span><input type="date" value={draft.review_period_end} onChange={event=>update('review_period_end',event.target.value)}/></label><label><span>전체 표본 수</span><input type="number" min="1" max="100000" value={draft.sample_size} onChange={event=>update('sample_size',event.target.value)}/></label><label><span>반복 불편 · 한 줄에 하나</span><textarea value={joinLines(draft.pain_points)} onChange={event=>update('pain_points',lines(event.target.value))}/></label><label><span>반복 만족 · 한 줄에 하나</span><textarea value={joinLines(draft.praised_points)} onChange={event=>update('praised_points',lines(event.target.value))}/></label><label><span>구매 이유 · 한 줄에 하나</span><textarea value={joinLines(draft.purchase_reasons)} onChange={event=>update('purchase_reasons',lines(event.target.value))}/></label><label><span>이탈 이유 · 한 줄에 하나</span><textarea value={joinLines(draft.rejection_reasons)} onChange={event=>update('rejection_reasons',lines(event.target.value))}/></label></div><EvidenceChoices title="경쟁 리뷰 Evidence" description="리뷰 기간·표본·반복 신호를 확인한 근거" evidence={evidence} selected={draft.evidence_ids} onChange={onEvidence}/><OwnerCheck checked={draft.owner_confirmed} onChange={checked=>update('owner_confirmed',checked)} text="리뷰 표본과 반복 신호를 직접 확인했어요"/><HarinButton variant="primary" icon="check" type="submit" disabled={Boolean(working)}>{working==='SAVE_COMPETITOR_REVIEW'?'경쟁 리뷰 저장 중…':'경쟁 리뷰 집계 저장'}</HarinButton></form>;}
function AppealForm({draft,setDraft,reviews,competitors,evidence,working,onEvidence,onSubmit}){const update=(field,value)=>setDraft(current=>({...current,[field]:value})),toggleReview=(id,checked)=>update('competitor_review_ids',checked?[...new Set([...draft.competitor_review_ids,id])]:draft.competitor_review_ids.filter(item=>item!==id));return <form className="marketProfileForm" onSubmit={event=>{event.preventDefault();onSubmit();}}><div className="marketProfileFields"><label><span>소구점 유형</span><select value={draft.appeal_type} onChange={event=>update('appeal_type',event.target.value)}>{Object.entries(appealNames).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><label><span>소구점 이름</span><input maxLength="160" value={draft.title} onChange={event=>update('title',event.target.value)} placeholder="예: 구성 선택이 쉬워요"/></label><label><span>경쟁상품에서 확인한 고객 불편</span><textarea maxLength="1000" value={draft.customer_problem} onChange={event=>update('customer_problem',event.target.value)}/></label><label><span>우리 상품의 해결 방식</span><textarea maxLength="1000" value={draft.own_resolution} onChange={event=>update('own_resolution',event.target.value)}/></label><label className="wide"><span>고객에게 보여줄 문구</span><input maxLength="500" value={draft.claim_text} onChange={event=>update('claim_text',event.target.value)} placeholder="치료·완치·최고 같은 표현은 사용할 수 없어요."/></label><label className="wide"><span>근거를 쉬운 말로 설명</span><textarea maxLength="2000" value={draft.proof_summary} onChange={event=>update('proof_summary',event.target.value)}/></label></div><fieldset className="marketReviewChoices"><legend>연결할 검증 경쟁 리뷰</legend>{reviews.length?<div>{reviews.map(review=><label key={review.id}><input type="checkbox" checked={draft.competitor_review_ids.includes(review.id)} onChange={event=>toggleReview(review.id,event.target.checked)}/><span><b>{competitors.get(review.competitor_id)?.competitor_name||'경쟁상품'} · {review.review_set_name}</b><small>{review.sample_size.toLocaleString('ko-KR')}건 · {review.pain_points?.[0]||'불편 신호 확인'}</small></span></label>)}</div>:<HarinEmptyState icon="customer" title="연결할 검증 경쟁 리뷰가 없어요" description="표본 10건 이상과 Evidence를 확인 완료해주세요."/>}</fieldset><div className="marketDualEvidence"><EvidenceChoices title="① 경쟁 불편 근거" description="경쟁 리뷰에서 확인한 문제" evidence={evidence} selected={draft.competitor_pain_evidence_ids} onChange={(id,checked)=>onEvidence('competitor_pain_evidence_ids',id,checked)}/><EvidenceChoices title="② 우리 해결 근거" description="우리 상품이 해결한다는 자료" evidence={evidence} selected={draft.own_resolution_evidence_ids} onChange={(id,checked)=>onEvidence('own_resolution_evidence_ids',id,checked)}/></div><OwnerCheck checked={draft.owner_confirmed} onChange={checked=>update('owner_confirmed',checked)} text="경쟁 불편과 우리 해결 근거, 고객 문구를 모두 확인했어요"/><HarinButton variant="primary" icon="check" type="submit" disabled={Boolean(working)}>{working==='SAVE_APPEAL'?'소구점 확인 중…':'소구점 저장·안전 검사'}</HarinButton></form>;}
