'use strict';
const auth=require('../dashboard-auth.js'),{getSupabase}=require('../cafe24/supabase.js'),{readJson}=require('../api/safety.js'),{valid}=require('../../desktop/assistant-automation-contract.cjs'),{hash}=require('./access.js');
const reply=(status,value)=>Response.json(value,{status,headers:{'cache-control':'private, no-store',vary:'Cookie, Authorization','x-content-type-options':'nosniff'}});
function handler({worker=false,database=getSupabase,validate=auth.validateSession}={}){return async request=>{try{
 const url=new URL(request.url),path='/api/moaon/assistant/'+(worker?'worker':'automation');if(url.pathname!==path||url.search||request.method!=='POST'||!/^application\/json(?:;.*)?$/i.test(request.headers.get('content-type')||''))return reply(400,{ok:false,code:'ASSISTANT_INVALID'});
 let session=null,digest=null;const db=database();
 if(worker){const bearer=request.headers.get('authorization')||'';if(request.headers.has('cookie')||!/^Bearer moaon_ro_[A-Za-z0-9_-]{43}$/.test(bearer))return reply(401,{ok:false,code:'ASSISTANT_AUTH_REQUIRED'});digest=hash(bearer.slice(7));}
 else{if(request.headers.get('origin')!==url.origin||request.headers.get('sec-fetch-site')==='cross-site')return reply(403,{ok:false,code:'ASSISTANT_AUTH_REQUIRED'});const cookies=(request.headers.get('cookie')||'').split(';').map(v=>v.trim()).filter(v=>v.startsWith(auth.COOKIE_NAME+'='));if(cookies.length!==1)return reply(401,{ok:false,code:'ASSISTANT_AUTH_REQUIRED'});const token=cookies[0].slice(auth.COOKIE_NAME.length+1);if(token.length>4096)return reply(401,{ok:false,code:'ASSISTANT_AUTH_REQUIRED'});session=await validate(token,{db});if(session?.role!=='OWNER')return reply(401,{ok:false,code:'ASSISTANT_AUTH_REQUIRED'});session.hash=auth.tokenHash(token);}
 const input=await readJson(request,{maxBytes:64000});if(!valid(input,worker))return reply(400,{ok:false,code:'ASSISTANT_INVALID'});
 if(input.action.startsWith('BOT_')){try{return reply(200,{ok:true,value:await require('./bots.js').command({input,worker,db,session,digest})});}catch(e){return reply(e.code==='ASSISTANT_CONFLICT'?409:e.code==='ASSISTANT_AUTH_REQUIRED'?401:400,{ok:false,code:e.code||'ASSISTANT_UNAVAILABLE'});}}
 const r=await db.rpc(input.action.startsWith('ACT_')?'moaon_assistant_actions':input.action.startsWith('AUTO_')?'moaon_assistant_bot_automation':'moaon_assistant_automation',{p_actor:session?.userId||null,p_session:session?.id||null,p_hash:session?.hash||null,p_input:input,p_worker_hash:digest});
 if(r.error){const code=['ASSISTANT_AUTH_REQUIRED','ASSISTANT_CONFLICT','ASSISTANT_INVALID','ASSISTANT_DISABLED','ASSISTANT_LIMIT','ASSISTANT_RATE_LIMITED'].find(c=>r.error.message?.includes(c))||'ASSISTANT_UNAVAILABLE';return reply(({ASSISTANT_AUTH_REQUIRED:401,ASSISTANT_CONFLICT:409,ASSISTANT_INVALID:400,ASSISTANT_DISABLED:403,ASSISTANT_LIMIT:409,ASSISTANT_RATE_LIMITED:429})[code]||503,{ok:false,code});}
 return reply(200,{ok:true,value:r.data});
 }catch{return reply(503,{ok:false,code:'ASSISTANT_UNAVAILABLE'});}};}
module.exports={handler};
