'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{spawnSync}=require('node:child_process');
const keyFile='D:/GPT/secrets/moaon-update/private.dpapi';
function protect(bytes,decrypt=false){const method=decrypt?'Unprotect':'Protect';const script=`$ErrorActionPreference='Stop';Add-Type -AssemblyName System.Security;$b=[Convert]::FromBase64String([Console]::In.ReadToEnd());[Console]::Out.Write([Convert]::ToBase64String([Security.Cryptography.ProtectedData]::${method}($b,$null,[Security.Cryptography.DataProtectionScope]::CurrentUser)))`;const r=spawnSync('powershell.exe',['-NoProfile','-NonInteractive','-Command',script],{input:bytes.toString('base64'),encoding:'utf8',windowsHide:true});if(r.status!==0)throw Error('Windows key protection failed');return Buffer.from(r.stdout.trim(),'base64');}
function publicKey(){return fs.readFileSync(keyFile+'.pub','utf8');}
function init(){if(fs.existsSync(keyFile))return publicKey();fs.mkdirSync(path.dirname(keyFile),{recursive:true});const pair=crypto.generateKeyPairSync('ed25519');const raw=pair.privateKey.export({format:'der',type:'pkcs8'});try{fs.writeFileSync(keyFile,protect(raw),{flag:'wx'});fs.writeFileSync(keyFile+'.pub',pair.publicKey.export({format:'pem',type:'spki'}),{flag:'wx'});}finally{raw.fill(0);}return publicKey();}
function signInstaller(file,version,output){if(!/^\d{1,4}\.\d{1,4}\.\d{1,4}$/.test(version)||path.basename(file)!==`Moaon-${version}-Setup.exe`)throw Error('Installer/version mismatch');const data=fs.readFileSync(file),payload={appId:'com.moaon.preview',channel:'stable',version,file:path.basename(file),size:data.length,sha512:crypto.createHash('sha512').update(data).digest('base64')},raw=protect(fs.readFileSync(keyFile),true);try{const key=crypto.createPrivateKey({key:raw,type:'pkcs8',format:'der'}),bytes=Buffer.from(JSON.stringify(payload));const envelope={payload:bytes.toString('base64'),signature:crypto.sign(null,bytes,key).toString('base64')};require('../signed-updates.cjs').verifyManifest(envelope,publicKey());fs.writeFileSync(path.join(output,'release.json'),JSON.stringify(envelope,null,2));fs.writeFileSync(path.join(output,'latest.yml'),`version: ${version}\nfiles:\n  - url: ${payload.file}\n    sha512: ${payload.sha512}\n    size: ${payload.size}\npath: ${payload.file}\nsha512: ${payload.sha512}\n`);return {version,file:payload.file,size:payload.size,signed:true};}finally{raw.fill(0);}}
if(require.main===module){try{const [command,file,version,output]=process.argv.slice(2);if(command==='init')process.stdout.write(init());else if(command==='sign')console.log(JSON.stringify(signInstaller(file,version,output)));else throw Error('Use init or sign <installer> <version> <output>');}catch(e){console.error(e.message);process.exitCode=1;}}
module.exports={init,signInstaller};
