'use strict';

const configModule=require('./config.js');
const holidayClient=require('./holiday-client.js');
const addressClient=require('./address-client.js');
const businessCalendar=require('./business-calendar.js');

const DEFINITIONS=[
  {key:'holidayCalendar',provider:'HOLIDAY_CALENDAR',label:'대한민국 공휴일',subtitle:'15시 마감·주말·공휴일 출고일 계산',icon:'clock',actionLabel:'올해 공휴일 읽기 확인'},
  {key:'roadAddress',provider:'ROAD_ADDRESS',label:'도로명주소 검색',subtitle:'사장님이 직접 조회할 때만 주소 후보 확인',icon:'search',actionLabel:'주소 후보 조회'}
];
function time(row){return new Date(row?.fetched_at||row?.created_at||0).getTime()||0;}
function latest(rows){return [...rows].sort((a,b)=>time(b)-time(a))[0]||null;}
function publicError(error){const message=String(error?.message||'연결 확인에 실패했습니다.').replace(/\s+/g,' ').slice(0,180);if(/quota|rate|429|LIMIT/i.test(message))return '공급자 호출 한도를 확인해주세요. 이전 성공 자료는 유지됩니다.';if(/key|인증|승인키|E0001|30|31/i.test(message))return '서버에 저장한 API 키 또는 승인 상태를 확인해주세요.';return message;}
function providerStatus(row,config,missing){if(!config.enabled)return 'LOCKED';if(missing.length)return 'SETUP_REQUIRED';if(!row)return 'VERIFY_REQUIRED';if(row.status==='SUCCESS')return 'READY';if(row.status==='NO_DATA')return 'NO_DATA';return 'FAILED';}
function extractCalendar(snapshots=[],year=new Date().getFullYear()){
  const success=latest(snapshots.filter(row=>row.provider==='HOLIDAY_CALENDAR'&&row.status==='SUCCESS'&&Number(row.reference_year)===Number(year)));
  const holidays=Array.isArray(success?.source_data?.holidays)?success.source_data.holidays:[];
  return {year:Number(year),ready:Boolean(success),holidays,sourceTimestamp:success?.source_timestamp||success?.fetched_at||null};
}
function previewDays(calendar,now){
  const start=businessCalendar.dateKey(now);return Array.from({length:7},(_,index)=>{const date=businessCalendar.addDays(start,index);return {date,businessDay:businessCalendar.isBusinessDay(date,businessCalendar.holidaySet(calendar.holidays)),holiday:calendar.holidays.find(item=>String(item.date).replace(/[^0-9]/g,'')===date.replace(/-/g,''))?.name||null};});
}
function buildShippingReferenceReadiness({snapshots=[],env=process.env,now=new Date()}={}){
  const year=Number(businessCalendar.dateKey(now).slice(0,4));const calendar=extractCalendar(snapshots,year);
  const services=DEFINITIONS.map(def=>{const config=configModule.providerConfig(def.provider,env);const missing=configModule.missingFields(def.provider,config);const rows=snapshots.filter(row=>row.provider===def.provider);const attempt=latest(rows);const success=latest(rows.filter(row=>row.status==='SUCCESS'));const status=providerStatus(attempt,config,missing);return {...def,status,missingFields:missing,lastAttemptAt:attempt?.fetched_at||null,lastSuccessAt:success?.fetched_at||null,previousSuccess:Boolean(success&&success!==attempt),errorMessage:status==='FAILED'?publicError({message:attempt?.error_message}):null,summary:{READY:'읽기 연결과 최신 자료를 확인했어요.',NO_DATA:'연결은 됐지만 조회 결과가 없어요.',FAILED:'최근 읽기 확인이 실패했어요.',VERIFY_REQUIRED:'설정은 준비됐고 첫 확인이 필요해요.',SETUP_REQUIRED:'API 키는 마지막 연결 단계에서 한 번에 입력해요.',LOCKED:'서버 안전 스위치로 중지되어 있어요.'}[status],detail:def.provider==='HOLIDAY_CALENDAR'?(calendar.ready?`${year}년 공휴일 ${calendar.holidays.length}일 저장`:'현재는 주말만 반영하며 공휴일은 판단 보류'):'고객 주소를 자동 전송하거나 저장하지 않습니다.',action:{endpoint:def.provider==='HOLIDAY_CALENDAR'?'/api/shipping-reference/holiday/probe':'/api/shipping-reference/address/probe',label:def.actionLabel}};});
  return {phase:'19-3',generatedAt:new Date(now).toISOString(),services,calendar:{...calendar,preview:previewDays(calendar,now)},summary:{ready:services.filter(item=>item.status==='READY').length,attention:services.filter(item=>!['READY','NO_DATA'].includes(item.status)).length},rules:['공휴일 자료만 서버에 저장하고 고객 주소 원문은 저장하지 않습니다.','주소 조회는 사장님이 직접 입력한 때만 실행하며 동·호수와 연락처를 제거합니다.','키가 없을 때도 주말과 15시 마감은 계산하지만 공휴일 관련 판단은 보류합니다.','공급자 실패 시 이전 성공 자료를 보존하고 주문 화면을 중단하지 않습니다.']};
}
async function saveSnapshot(db,row){const result=await db.from('shipping_reference_snapshots').insert(row).select('id,provider,status,fetched_at').single();if(result.error){const error=new Error(`연결 결과 저장 실패: ${result.error.message}`);error.code='SHIPPING_REFERENCE_SAVE_FAILED';throw error;}return result.data;}
async function probeHoliday({db,env=process.env,fetchImpl=fetch,now=new Date(),year}={}){const config=configModule.providerConfig('HOLIDAY_CALENDAR',env);const missing=configModule.missingFields('HOLIDAY_CALENDAR',config);if(!config.enabled){const error=new Error('공휴일 공급자가 서버에서 중지되어 있습니다.');error.code='PROVIDER_DISABLED';error.status=423;throw error;}if(missing.length){const error=new Error(`필요한 서버 설정: ${missing.join(', ')}`);error.code='CONFIG_REQUIRED';error.status=412;throw error;}const targetYear=Number(year||businessCalendar.dateKey(now).slice(0,4));try{const result=await holidayClient.readYear({config,year:targetYear,fetchImpl});const row={provider:'HOLIDAY_CALENDAR',status:result.status,reference_year:targetYear,metric_summary:{holiday_count:result.holidays.length},source_data:{holidays:result.holidays},source_timestamp:result.sourceTimestamp,fetched_at:new Date(now).toISOString(),metadata:{read_only:true,contains_customer_data:false}};const stored=await saveSnapshot(db,row);return {provider:'HOLIDAY_CALENDAR',status:result.status,snapshot:stored,count:result.holidays.length};}catch(error){await saveSnapshot(db,{provider:'HOLIDAY_CALENDAR',status:'FAILED',reference_year:targetYear,metric_summary:{},source_data:{},fetched_at:new Date(now).toISOString(),error_code:error.code||'HOLIDAY_READ_FAILED',error_message:publicError(error),metadata:{read_only:true}}).catch(()=>{});throw error;}}
async function probeAddress({db,query,env=process.env,fetchImpl=fetch,now=new Date()}={}){const config=configModule.providerConfig('ROAD_ADDRESS',env);const missing=configModule.missingFields('ROAD_ADDRESS',config);if(!config.enabled){const error=new Error('주소 공급자가 서버에서 중지되어 있습니다.');error.code='PROVIDER_DISABLED';error.status=423;throw error;}if(missing.length){const error=new Error(`필요한 서버 설정: ${missing.join(', ')}`);error.code='CONFIG_REQUIRED';error.status=412;throw error;}try{const result=await addressClient.lookup({config,query,fetchImpl});await saveSnapshot(db,{provider:'ROAD_ADDRESS',status:result.status,metric_summary:{candidate_count:result.count},source_data:{},fetched_at:new Date(now).toISOString(),metadata:{read_only:true,manual_lookup:true,raw_query_stored:false}});return {provider:'ROAD_ADDRESS',status:result.status,count:result.count,candidates:result.candidates};}catch(error){await saveSnapshot(db,{provider:'ROAD_ADDRESS',status:'FAILED',metric_summary:{},source_data:{},fetched_at:new Date(now).toISOString(),error_code:error.code||'ADDRESS_READ_FAILED',error_message:publicError(error),metadata:{read_only:true,raw_query_stored:false}}).catch(()=>{});throw error;}}

module.exports={DEFINITIONS,buildShippingReferenceReadiness,extractCalendar,probeAddress,probeHoliday,publicError};
