'use strict';

const auth=require('../dashboard-auth.js');const supabase=require('../cafe24/supabase.js');const readiness=require('./readiness.js');const requestGuard=require('../provider-operations/request-guard.js');const providerConfig=require('./config.js');
function cookieValue(request){return request.headers.get('cookie')?.split(';').map(value=>value.trim()).find(value=>value.startsWith(`${auth.COOKIE_NAME}=`))?.split('=').slice(1).join('=');}
async function jsonBody(request){const length=Number(request.headers.get('content-length')||0);if(length>4096){const error=new Error('요청 내용이 너무 큽니다.');error.status=413;throw error;}return request.json().catch(()=>({}));}
function logFailure(scope,error){console.error(`[shipping-reference:${scope}]`,{code:error?.code||null,message:String(error?.message||error).slice(0,300),stack:String(error?.stack||'').split('\n').slice(0,8).join('\n')});}
async function handleHoliday(request){if(!auth.verifySession(cookieValue(request)))return Response.json({ok:false,error:'Unauthorized'},{status:401});try{const body=await jsonBody(request);const db=supabase.getSupabase();const year=Number(body.year||new Date().getFullYear()),config=providerConfig.providerConfig('HOLIDAY_CALENDAR'),missingFields=providerConfig.missingFields('HOLIDAY_CALENDAR',config);const result=await requestGuard.protectedRead({db,provider:'HOLIDAY_CALENDAR',requestInput:{year},ttlMs:12*60*60*1000,killSwitchEnabled:config.enabled,missingFields,execute:()=>readiness.probeHoliday({db,year})});return Response.json({ok:true,result},{headers:{'Cache-Control':'no-store'}});}catch(error){logFailure('holiday',error);return Response.json({ok:false,code:error.code||'HOLIDAY_PROBE_FAILED',error:readiness.publicError(error)},{status:error.status||502,headers:{'Cache-Control':'no-store'}});}}
async function handleAddress(request){if(!auth.verifySession(cookieValue(request)))return Response.json({ok:false,error:'Unauthorized'},{status:401});try{const body=await jsonBody(request);const db=supabase.getSupabase(),config=providerConfig.providerConfig('ROAD_ADDRESS'),missingFields=providerConfig.missingFields('ROAD_ADDRESS',config);const result=await requestGuard.protectedRead({db,provider:'ROAD_ADDRESS',requestInput:{query:body.query},cacheResponse:false,allowStaleFallback:false,killSwitchEnabled:config.enabled,missingFields,execute:()=>readiness.probeAddress({db,query:body.query})});return Response.json({ok:true,result},{headers:{'Cache-Control':'no-store'}});}catch(error){logFailure('address',error);return Response.json({ok:false,code:error.code||'ADDRESS_PROBE_FAILED',error:readiness.publicError(error)},{status:error.status||502,headers:{'Cache-Control':'no-store'}});}}
module.exports={handleAddress,handleHoliday};
