'use strict';
(()=>{const root=document.querySelector('[data-page=assistant]');if(!root)return;const el=(tag,text='',cls='')=>{const n=document.createElement(tag);n.textContent=text;n.className=cls;return n;};const button=(p,text,fn)=>{const n=el('button',text);n.type='button';n.onclick=fn;p.append(n);return n;};
 const tab=button(root.querySelector('.assistant-tabs'),'광고 자동화',()=>{root.querySelectorAll('[data-assistant-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b===tab)));root.querySelectorAll('[data-assistant-view]').forEach(v=>v.hidden=v!==view);run({action:'ADS_READ'});});tab.dataset.assistantTab='ads';tab.setAttribute('aria-pressed','false');
 const view=el('section');view.dataset.assistantView='ads';view.hidden=true;root.append(view);view.append(el('h2','네이버 광고 리포트'),el('p','자료 수집부터 보고서 보관까지. 광고 예산·입찰은 변경하지 않습니다.','assistant-help'));const status=el('p','','assistant-help');status.id='assistant-ads-status';status.setAttribute('role','status');view.append(status);
 const card=el('section','','assistant-card');view.append(card);card.append(el('h3','리포트 만들기'));function input(p,label,type){const l=el('label',label,'assistant-field'),i=el('input');i.type=type;l.append(i);p.append(l);return i;}
 const start=input(card,'시작일','date'),end=input(card,'종료일','date');start.id='assistant-ads-start';end.id='assistant-ads-end';const kst=new Date(Date.now()+9*3600000);kst.setUTCDate(kst.getUTCDate()-1);end.value=kst.toISOString().slice(0,10);start.value=end.value;const fresh=input(card,'네이버 API에서 새로 수집','checkbox');fresh.checked=true;
 button(card,'리포트 생성 요청',()=>run({action:'ADS_REQUEST',start:start.value,end:end.value,fresh:fresh.checked}));card.append(el('p','어제까지 최근 90일 중 최대 31일을 선택하세요. 같은 날 같은 기간·자료 방식은 중복 생성하지 않습니다. 처리에는 수 분이 걸릴 수 있어요.','assistant-help'));
 const config=el('section','','assistant-card');view.append(config);config.append(el('h3','예약·알림'));const daily=input(config,'매일 전일 리포트','checkbox'),weekly=input(config,'월요일 지난주 리포트','checkbox'),time=input(config,'발송 준비 시작 시간 · 한국 시간','time'),notify=input(config,'광고비서로 완료 알림','checkbox'),failures=input(config,'관리비서로 실패 알림','checkbox');time.value='09:00';const monthly=input(config,'매월 2일 지난달 리포트','checkbox'),changes=input(config,'매일 최근 7일 성과 변화 감지','checkbox'),minClicks=input(config,'비교 기간별 최소 클릭 수','number'),minCost=input(config,'비교 기간별 최소 광고비 · 원','number'),changePercent=input(config,'변화 알림 기준 · %','number'),watchdog=input(config,'매일 오전 7시 Hermes 외부 장애 점검','checkbox');for(const [i,value,max] of [[minClicks,30,1000000],[minCost,10000,1000000000],[changePercent,30,500]]){i.value=value;i.min=1;i.max=max;i.step=1;}let state=null,busy=false,epoch=0,catalog=[],selected=[];const scope=el('section','','assistant-card');config.before(scope);scope.append(el('h3','집계할 캠페인'));const scopeLabel=el('p','','assistant-help'),choices=el('div','','assistant-campaign-choices');scope.append(scopeLabel);button(scope,'네이버 캠페인 불러오기',()=>run({action:'ADS_CAMPAIGNS'}));button(scope,'전체 캠페인으로 선택',()=>{selected=[];drawScope();});scope.append(choices,el('p','선택이 없으면 전체 캠페인입니다. 아래 설정 저장 후 새 요청·예약에 적용됩니다. 이미 요청한 작업과 재작성은 원래 범위를 유지합니다.','assistant-help'));function drawScope(){scopeLabel.textContent=selected.length?selected.length+'개 선택 · 저장 후 적용':'전체 캠페인';choices.replaceChildren();for(const c of catalog){const i=input(choices,c.name+' · '+c.id,'checkbox');i.checked=selected.includes(c.id);i.onchange=()=>{selected=i.checked?[...selected,c.id]:selected.filter(x=>x!==c.id);scopeLabel.textContent=selected.length?selected.length+'개 선택 · 저장 후 적용':'전체 캠페인';};}}
 button(config,'광고 자동화 설정 저장',()=>{if(state)run({action:'ADS_SAVE',revision:state.revision,settings:{daily:daily.checked,weekly:weekly.checked,time:time.value,notify:notify.checked,failures:failures.checked,monthly:monthly.checked,changes:changes.checked,minClicks:Number(minClicks.value),minCost:Number(minCost.value),changePercent:Number(changePercent.value),watchdog:watchdog.checked,campaignIds:selected}});});config.append(el('p','수신처는 텔레그램 봇에 저장한 본인 계정입니다. 실패 알림은 관리비서도 같은 개인 계정에 연결돼 있어야 합니다. 지정 시각부터 서버가 작업을 준비하며, 완료 후 발송합니다.','assistant-help'));
 button(config,'변화 감지 지금 실행',()=>run({action:'ADS_CHANGE_TEST'}));button(config,'외부 점검 지금 실행',()=>run({action:'ADS_WATCHDOG'}));config.append(el('p','시험 전 설정을 저장하세요. 변화 감지 시험은 예약과 같은 하루 1회 작업을 사용합니다. 외부 점검은 해당 스위치가 켜져 있어야 실행됩니다.','assistant-help'));
 button(view,'실행 결과 새로고침',()=>run({action:'ADS_READ'}));const list=el('div');list.id='assistant-ads-jobs';view.append(list);
 function render(){selected=state.settings.campaignIds||[];if(state.campaigns)catalog=state.campaigns;drawScope();for(const [k,i] of Object.entries({daily,weekly,time,notify,failures,monthly,changes,minClicks,minCost,changePercent,watchdog}))i.type==='checkbox'?i.checked=state.settings[k]:i.value=(state.settings[k]??({minClicks:30,minCost:10000,changePercent:30})[k]);list.replaceChildren();list.append(el('h3','최근 실행·보고서'));if(state.watchdog)list.append(el('p','외부 점검: '+({HEALTHY:'실행 신호 확인',STALE:'연결 확인 필요'})[state.watchdog.status]+' · 마지막 점검 '+(state.watchdog.checkedAt||'대기')+' · 알림 '+state.watchdog.delivery,'assistant-help'));for(const j of state.jobs){const d=el('details','','assistant-card');const label=({PENDING:'대기',RUNNING:'생성 중',SUCCEEDED:'완료',FAILED:'실패',UNKNOWN:'처리 결과 확인 필요'})[j.status]||'확인 필요';d.append(el('summary',j.start_date+' ~ '+j.end_date+' · '+label));d.append(el('p','알림: '+({PENDING:'대기',SENT:'전송 완료',FAILED:'실패',UNKNOWN:'결과 확인 필요',SKIPPED:'발송 안 함'})[j.delivery]));if(j.error_code)d.append(el('p','확인 코드: '+j.error_code+' · 연결 상태와 조회 기간을 확인하세요.'));
  if(j.summary?.revisionComparison){const c=j.summary.revisionComparison,section=el('section','','assistant-revision');section.append(el('h4','원본과 재작성 비교'),el('p',c.reason),el('p','원본 조회: '+(c.previousSourceAsOf||'확인 필요')+' · 재조회: '+(c.currentSourceAsOf||'확인 필요'),'assistant-help'));section.append(el('p','자료 관측: 원본 '+(c.coverage?.before?.observed??'?')+'/'+(c.coverage?.before?.expected??'?')+' → 재작성 '+(c.coverage?.after?.observed??'?')+'/'+(c.coverage?.after?.expected??'?'),'assistant-help'));const wrap=el('div','','assistant-revision-table'),table=el('table'),head=el('thead'),hr=el('tr');for(const label of ['지표','원본','재작성','차이']){const th=el('th',label);th.scope='col';hr.append(th);}head.append(hr);table.append(head);const body=el('tbody');for(const r of c.rows){const row=el('tr'),name=el('th',r.label);name.scope='row';row.append(name);for(const v of [r.before,r.after])row.append(el('td',v===null?'확인 필요':Number(v).toLocaleString('ko-KR',{maximumFractionDigits:2})));row.append(el('td',r.delta===null?({ADDED:'자료 보완',MISSING:'자료 누락'})[r.state]||'비교 보류':(r.delta>0?'+':'')+r.delta.toLocaleString('ko-KR')+r.unit));body.append(row);}table.append(body);wrap.append(table);section.append(wrap,el('p',c.caveat,'assistant-help'));d.append(section);}else if(j.parent_id)d.append(el('p','이전 버전에서 만든 보고서입니다. 다시 재작성하면 원본 비교가 함께 생성됩니다.','assistant-help'));
  if(j.summary?.change){const c=j.summary.change;d.append(el('p','변화 감지: '+({HOLD:'판단 보류',STABLE:'기준 이내',ALERT:'확인 필요'})[c.status]+' · '+c.reason));for(const x of c.signals)d.append(el('p',x.label+' '+x.percent+'%'));}if(j.summary){const m=j.summary.metrics;for(const [k,name] of Object.entries({cost:'광고비',clicks:'클릭',conversions:'전환',revenue:'전환매출',roas:'ROAS'}))d.append(el('p',name+': '+(m[k]===null?'확인 필요':Math.round(m[k]*100)/100)));d.append(el('p','자료 상태: '+j.summary.status+' · API 조회: '+(j.summary.sourceAsOf||'원본 수집 시각 확인 필요')));for(const text of j.summary.caveats)d.append(el('p',text,'assistant-help'));}
  d.append(el('p',(j.campaign_ids?.length?j.campaign_ids.length+'개 캠페인':'전체 캠페인')+(j.parent_id?' · 이전 작업 '+j.parent_id.slice(0,8)+' 재작성':''),'assistant-help'));if(j.status==='SUCCEEDED')button(d,'같은 범위로 새로 수집·재작성',()=>run({action:'ADS_REVISE',id:j.id}));
  if(j.report_id)button(d,'보고서 다운로드 주소 복사',async()=>{await window.moaonHub.copyEventText('https://harin-cafe24-sync.vercel.app/api/reports/'+j.report_id+'/download');status.textContent='복사했어요. 로그인된 웹 브라우저에서 열면 HTML 보고서를 받을 수 있어요.';});list.append(d);}}
 async function run(v){if(busy)return;busy=true;const current=epoch;view.querySelectorAll('button').forEach(b=>b.disabled=true);status.textContent='처리 중…';try{const r=await window.moaonHub.assistantAutomation(v);if(current!==epoch)return;if(!r.ok){status.textContent='처리하지 못했어요. '+(r.code||'연결 확인 필요');return;}state=r.value;render();status.textContent=['ADS_REQUEST','ADS_CHANGE_TEST','ADS_REVISE'].includes(v.action)?'생성 요청을 저장했어요. 실행 결과 새로고침으로 확인하세요.':v.action==='ADS_SAVE'?'설정을 저장했어요.':'실행 내역을 확인했어요.';}catch{status.textContent='결과를 확인하지 못했어요. 새로고침해 주세요.';}finally{busy=false;view.querySelectorAll('button').forEach(b=>b.disabled=false);}}
 const guide=el('details','','assistant-card');guide.append(el('summary','처음 연결하는 순서·오류 해결'),el('p','1. 앱 설정에서 네이버 광고 API 연결을 확인합니다. 2. 업무비서의 연결 설정에서 보고서 조회 권한을 확인합니다. 3. 광고비서를 본인 텔레그램과 연결합니다. 4. 어제 리포트를 생성하고 보고서와 알림을 확인합니다. 5. 확인 후 예약 스위치를 켜세요.'),el('p','ADS_CAMPAIGN_MISSING: 선택 캠페인이 삭제되었거나 조회되지 않음 · 원본 보고서는 보존되며 재작성 요청은 원본당 한 번만 접수합니다. 이후에는 새 보고서에서 다시 재작성하세요. 원본 비교는 같은 기간을 재조회한 수치 차이입니다. 광고 성과 개선이나 변경 원인을 뜻하지 않습니다. ADS_NO_DATA: 조회 자료 없음 · ADS_COLLECTION_FAILED: API 인증·기간·응답 확인 · PARTIAL: 누락 지표 또는 기간 확인 · UNKNOWN: 완료 여부가 불확실하므로 반복 요청 전에 결과를 확인하세요. 월간 리포트는 매월 2일 지난달 전체를 수집합니다. 변화 감지는 최근 7일과 직전 7일의 광고비·CPC 상승 또는 ROAS 하락을 비교합니다. 두 기간이 최소 클릭·광고비 조건을 충족하고 캠페인 구성이 같을 때만 경고합니다. 이는 통계적 유의성 검정이 아닙니다. 자료 부족은 판단 보류하며 경고를 보내지 않습니다. 외부 점검은 Hermes 밖에서 매일 오전 7시경 실행하며 마지막 신호가 15분 넘게 없으면 관리비서에 한 번 알립니다. 복구도 다음 외부 점검에서 알립니다. 실시간 장애 감시는 아닙니다.'));view.append(guide);
 document.querySelectorAll('[data-action=hub-disconnect]').forEach(b=>b.addEventListener('click',()=>{epoch++;state=null;catalog=[];selected=[];drawScope();list.replaceChildren();status.textContent='로그인 후 확인하세요.';}));
})();
