'use strict';
(()=>{const root=document.querySelector('[data-page=assistant]');if(!root)return;const el=(tag,text='',cls='')=>{const n=document.createElement(tag);n.textContent=text;n.className=cls;return n;};let rows=[],busy=false,generation=0;const cards={};const tab=el('button','텔레그램 봇');tab.type='button';tab.dataset.assistantTab='bots';tab.setAttribute('aria-pressed','false');root.querySelector('.assistant-tabs').append(tab);const view=el('div','','assistant-bot-grid');view.dataset.assistantView='bots';view.hidden=true;root.append(view);const status=el('p','두 봇을 각각 연결하고 대화 허용 사용자와 수신처를 설정하세요.','assistant-help');status.id='assistant-bots-status';status.setAttribute('role','status');view.append(status);
const action=(text,fn,parent,cls='')=>{const b=el('button',text,cls);b.type='button';b.onclick=fn;parent.append(b);return b;};
const field=(parent,label,type,id)=>{const l=el('label',label,'assistant-field'),n=el(type==='textarea'?'textarea':'input');n.id=id;if(type!=='textarea')n.type=type;l.append(n);parent.append(l);return n;};
const confirm=el('dialog','','assistant-dialog'),heading=el('h2'),detail=el('p'),buttons=el('div','','assistant-actions');let pending;confirm.append(heading,detail,buttons);action('취소',()=>confirm.close(),buttons);action('확인',()=>{const f=pending;confirm.close();if(f)f();},buttons).id='assistant-bot-confirm';confirm.addEventListener('close',()=>pending=null);root.append(confirm);
function ask(title,body,fn){if(busy)return;heading.textContent=title;detail.textContent=body;pending=fn;confirm.showModal();}
for(const slot of ['WORK','SOLO']){const id=slot.toLowerCase(),c=el('section','','assistant-card assistant-auto-card assistant-bot-card');c.dataset.botSlot=slot;const name=slot==='WORK'?'모아온 업무비서':'모아온 개인비서',username=slot==='WORK'?'moaon_hub_bot':'moaon_solo_bot';c.append(el('h2',name),el('p','@'+username,'assistant-bot-handle'),el('p',slot==='WORK'?'주문·문의·제품 지식과 업무 등록안을 도와줍니다.':'본인과의 대화, 아이디어 정리와 개인 업무를 도와줍니다.','assistant-help'));const badge=el('p','연결 확인 전','assistant-bot-state');c.append(badge);const form=el('form');form.autocomplete='off';c.append(form);const key=field(form,'봇 토큰','password','assistant-bot-token-'+id);key.autocomplete='new-password';key.placeholder='처음 연결하거나 토큰을 교체할 때 입력';key.maxLength=100;const chat=field(form,slot==='WORK'?'알림 수신 대화 ID · 개인 또는 그룹':'본인 텔레그램 숫자 ID','text','assistant-bot-chat-'+id);chat.required=true;chat.placeholder=slot==='WORK'?'개인 123456789 / 그룹 -100…':'예: 123456789';const users=field(form,'대화 허용 사용자 ID · 쉼표로 구분','text','assistant-bot-users-'+id);users.required=true;users.placeholder='예: 123456789';if(slot==='SOLO'){users.closest('label').hidden=true;chat.oninput=()=>users.value=chat.value;}
const instructions=field(form,'비서에게 알려줄 응답 방식','textarea','assistant-bot-instructions-'+id);instructions.rows=4;instructions.maxLength=4000;instructions.placeholder='예: 한국어로 간결하게, 굵은 글씨나 별표를 남발하지 않기';
const check=(label,id)=>{const l=el('label','','assistant-check'),n=el('input');n.type='checkbox';n.id=id;l.append(n,document.createTextNode(label));form.append(l);return n;};const enabled=check('Hermes 대화 연결 켜기','assistant-bot-enabled-'+id),notifications=check('예약·변화 알림을 이 봇으로 보내기','assistant-bot-notifications-'+id);notifications.closest('label').hidden=true;
const save=el('button','연결 확인 · 저장','assistant-primary');save.type='submit';form.append(save);action('시험 알림 보내기',()=>{const r=rows.find(r=>r.slot===slot);if(!r){status.textContent='먼저 봇을 연결하고 저장하세요.';return;}ask(name+' 시험 알림을 보낼까요?','저장한 대화 ID '+r.settings.chatId+'로 1회 발송합니다.',()=>run({action:'BOT_TEST',slot,revision:r.revision,id:crypto.randomUUID()}));},form);c.append(el('p','토큰은 암호화해 저장하며 다시 표시하지 않습니다. 저장 후 Hermes 적용에는 약 2분이 걸립니다.','assistant-help'));if(slot==='WORK')c.append(el('p','그룹 수신은 봇을 그룹에 추가하고 해당 그룹 ID를 저장하세요. 예약 시간과 발송 스위치는 예약·알림 탭에서 관리합니다.','assistant-help'));else c.append(el('p','개인비서는 입력한 본인의 개인 대화만 허용합니다. 두 비서는 대화·기억을 별도 프로필에 저장합니다.','assistant-help'));
form.onsubmit=e=>{e.preventDefault();const r=rows.find(r=>r.slot===slot);ask(name+' 설정을 저장할까요?','봇을 확인한 뒤 저장하며, 켜둔 연결 설정을 Hermes에 적용합니다.',()=>run({action:'BOT_SAVE',slot,revision:r?.revision||0,token:key.value.trim(),settings:{enabled:enabled.checked,chatId:chat.value.trim(),allowedUsers:(slot==='SOLO'?chat.value:users.value).split(',').map(v=>v.trim()).filter(Boolean),instructions:instructions.value.trim(),notifications:slot==='WORK'&&notifications.checked}}));};cards[slot]={key,chat,users,instructions,enabled,notifications,badge};view.append(c);}
action('연결 상태 새로고침',()=>run({action:'BOT_LIST'}),view);
function render(){for(const slot of ['WORK','SOLO']){const c=cards[slot],r=rows.find(r=>r.slot===slot);if(!r){c.badge.textContent='아직 연결하지 않았어요';continue;}c.key.value='';c.key.placeholder='저장됨 · 비워두면 기존 토큰 유지';c.chat.value=r.settings.chatId;c.users.value=r.settings.allowedUsers.join(', ');c.instructions.value=r.settings.instructions;c.enabled.checked=r.settings.enabled;c.notifications.checked=r.settings.notifications;const fresh=r.checked_at&&Date.now()-Date.parse(r.checked_at)<5*60*1000;const runtime=r.applied_revision===r.revision&&fresh?({RUNNING:'Hermes 실행 중',STOPPED:'대화 연결 꺼짐',CHECK_REQUIRED:'Hermes 확인 필요'})[r.runtime_status]:'Hermes 적용 확인 대기';c.badge.textContent='토큰 확인됨 · '+runtime+(r.test_status?' · 시험 '+({SENT:'전송 완료',FAILED:'실패 · 봇 /start와 대화 ID 확인',UNKNOWN:'결과 확인 필요',PENDING:'처리 확인 필요'})[r.test_status]:'');}}
async function run(input){if(busy)return;busy=true;const epoch=generation;view.querySelectorAll('button').forEach(b=>b.disabled=true);status.textContent='연결 상태를 확인하고 있어요…';try{const r=await window.moaonHub.assistantAutomation(input);if(epoch!==generation)return;if(!r.ok){status.textContent=({BOT_IDENTITY_MISMATCH:'선택한 봇의 토큰이 아닙니다. 사용자명을 확인하세요.',BOT_REJECTED:'Telegram에서 거절했습니다. 토큰과 /start 여부를 확인하세요.',BOT_INVALID:'봇 토큰 형식을 확인하세요.',ASSISTANT_INVALID:'토큰, 숫자 ID와 설정을 확인하세요.',ASSISTANT_CONFLICT:'설정이 변경됐어요. 새로고침 후 다시 저장하세요.',ASSISTANT_RATE_LIMITED:'잠시 후 다시 시도하세요.'})[r.code]||'처리 결과를 확인하지 못했어요. 새로고침해 확인하세요.';return;}rows=r.value.bots;render();status.textContent=input.action==='BOT_SAVE'?'저장했어요. Hermes 적용 상태는 새로고침해서 확인하세요.':input.action==='BOT_TEST'?'시험 발송 결과를 봇 카드에서 확인하세요.':'서버의 연결 상태를 확인했어요.';}catch{status.textContent='연결 결과를 확인하지 못했어요. 새로고침해 확인하세요.';}finally{if(Object.hasOwn(input,'token'))input.token='';busy=false;view.querySelectorAll('button').forEach(b=>b.disabled=false);}}
tab.onclick=()=>{root.querySelectorAll('[data-assistant-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b===tab)));root.querySelectorAll('[data-assistant-view]').forEach(v=>v.hidden=v!==view);void run({action:'BOT_LIST'});};document.querySelectorAll('[data-action=hub-disconnect]').forEach(b=>b.addEventListener('click',()=>{generation++;rows=[];for(const c of Object.values(cards)){c.key.value='';c.chat.value='';c.users.value='';c.instructions.value='';c.badge.textContent='로그인 후 확인하세요';}confirm.close();}));
})();
