'use strict';
(()=>{const root=document.querySelector('[data-page=assistant]');if(!root)return;const el=(tag,text='',cls='')=>{const n=document.createElement(tag);n.textContent=text;n.className=cls;return n;};const button=(p,text,fn)=>{const n=el('button',text);n.type='button';n.onclick=fn;p.append(n);return n;};
 const tab=button(root.querySelector('.assistant-tabs'),'광고 자동화',()=>{root.querySelectorAll('[data-assistant-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b===tab)));root.querySelectorAll('[data-assistant-view]').forEach(v=>v.hidden=v!==view);run({action:'ADS_READ'});});tab.dataset.assistantTab='ads';tab.setAttribute('aria-pressed','false');
 const view=el('section');view.dataset.assistantView='ads';view.hidden=true;root.append(view);view.append(el('h2','네이버 광고 리포트'),el('p','자료 수집부터 보고서 보관까지. 광고 예산·입찰은 변경하지 않습니다.','assistant-help'));const status=el('p','','assistant-help');status.id='assistant-ads-status';status.setAttribute('role','status');view.append(status);
 const card=el('section','','assistant-card');view.append(card);card.append(el('h3','리포트 만들기'));function input(p,label,type){const l=el('label',label,'assistant-field'),i=el('input');i.type=type;l.append(i);p.append(l);return i;}
 const start=input(card,'시작일','date'),end=input(card,'종료일','date');start.id='assistant-ads-start';end.id='assistant-ads-end';const kst=new Date(Date.now()+9*3600000);kst.setUTCDate(kst.getUTCDate()-1);end.value=kst.toISOString().slice(0,10);start.value=end.value;const fresh=input(card,'네이버 API에서 새로 수집','checkbox');fresh.checked=true;
 button(card,'리포트 생성 요청',()=>run({action:'ADS_REQUEST',start:start.value,end:end.value,fresh:fresh.checked}));card.append(el('p','어제까지 최근 90일 중 최대 31일을 선택하세요. 같은 날 같은 기간·자료 방식은 중복 생성하지 않습니다. 처리에는 수 분이 걸릴 수 있어요.','assistant-help'));
 const config=el('section','','assistant-card');view.append(config);config.append(el('h3','예약·알림'));const daily=input(config,'매일 전일 리포트','checkbox'),weekly=input(config,'월요일 지난주 리포트','checkbox'),time=input(config,'발송 준비 시작 시간 · 한국 시간','time'),notify=input(config,'광고비서로 완료 알림','checkbox'),failures=input(config,'관리비서로 실패 알림','checkbox');time.value='09:00';let state=null,busy=false,epoch=0;
 button(config,'광고 자동화 설정 저장',()=>{if(state)run({action:'ADS_SAVE',revision:state.revision,settings:{daily:daily.checked,weekly:weekly.checked,time:time.value,notify:notify.checked,failures:failures.checked}});});config.append(el('p','수신처는 텔레그램 봇에 저장한 본인 계정입니다. 실패 알림은 관리비서도 같은 개인 계정에 연결돼 있어야 합니다. 지정 시각부터 서버가 작업을 준비하며, 완료 후 발송합니다.','assistant-help'));
 button(view,'실행 결과 새로고침',()=>run({action:'ADS_READ'}));const list=el('div');list.id='assistant-ads-jobs';view.append(list);
 function render(){for(const [k,i] of Object.entries({daily,weekly,time,notify,failures}))i.type==='checkbox'?i.checked=state.settings[k]:i.value=state.settings[k];list.replaceChildren();list.append(el('h3','최근 실행·보고서'));for(const j of state.jobs){const d=el('details','','assistant-card');const label=({PENDING:'대기',RUNNING:'생성 중',SUCCEEDED:'완료',FAILED:'실패',UNKNOWN:'처리 결과 확인 필요'})[j.status]||'확인 필요';d.append(el('summary',j.start_date+' ~ '+j.end_date+' · '+label));d.append(el('p','알림: '+({PENDING:'대기',SENT:'전송 완료',FAILED:'실패',UNKNOWN:'결과 확인 필요',SKIPPED:'발송 안 함'})[j.delivery]));if(j.error_code)d.append(el('p','확인 코드: '+j.error_code+' · 연결 상태와 조회 기간을 확인하세요.'));
  if(j.summary){const m=j.summary.metrics;for(const [k,name] of Object.entries({cost:'광고비',clicks:'클릭',conversions:'전환',revenue:'전환매출',roas:'ROAS'}))d.append(el('p',name+': '+(m[k]===null?'확인 필요':Math.round(m[k]*100)/100)));d.append(el('p','자료 상태: '+j.summary.status+' · API 조회: '+(j.summary.sourceAsOf||'원본 수집 시각 확인 필요')));for(const text of j.summary.caveats)d.append(el('p',text,'assistant-help'));}
  if(j.report_id)button(d,'보고서 다운로드 주소 복사',async()=>{await window.moaonHub.copyEventText('https://harin-cafe24-sync.vercel.app/api/reports/'+j.report_id+'/download');status.textContent='복사했어요. 로그인된 웹 브라우저에서 열면 HTML 보고서를 받을 수 있어요.';});list.append(d);}}
 async function run(v){if(busy)return;busy=true;const current=epoch;view.querySelectorAll('button').forEach(b=>b.disabled=true);status.textContent='처리 중…';try{const r=await window.moaonHub.assistantAutomation(v);if(current!==epoch)return;if(!r.ok){status.textContent='처리하지 못했어요. '+(r.code||'연결 확인 필요');return;}state=r.value;render();status.textContent=v.action==='ADS_REQUEST'?'생성 요청을 저장했어요. 실행 결과 새로고침으로 확인하세요.':v.action==='ADS_SAVE'?'설정을 저장했어요.':'실행 내역을 확인했어요.';}catch{status.textContent='결과를 확인하지 못했어요. 새로고침해 주세요.';}finally{busy=false;view.querySelectorAll('button').forEach(b=>b.disabled=false);}}
 const guide=el('details','','assistant-card');guide.append(el('summary','처음 연결하는 순서·오류 해결'),el('p','1. 앱 설정에서 네이버 광고 API 연결을 확인합니다. 2. 업무비서의 연결 설정에서 보고서 조회 권한을 확인합니다. 3. 광고비서를 본인 텔레그램과 연결합니다. 4. 어제 리포트를 생성하고 보고서와 알림을 확인합니다. 5. 확인 후 예약 스위치를 켜세요.'),el('p','ADS_NO_DATA: 조회 자료 없음 · ADS_COLLECTION_FAILED: API 인증·기간·응답 확인 · PARTIAL: 누락 지표 또는 기간 확인 · UNKNOWN: 완료 여부가 불확실하므로 반복 요청 전에 결과를 확인하세요. 월간 예약·변화율 감지·외부 장애 감시는 아직 포함되지 않습니다.'));view.append(guide);
 document.querySelectorAll('[data-action=hub-disconnect]').forEach(b=>b.addEventListener('click',()=>{epoch++;state=null;list.replaceChildren();status.textContent='로그인 후 확인하세요.';}));
})();
