'use strict';
(()=>{const $=id=>document.getElementById(id),root=document.querySelector('[data-page=assistant]');if(!root)return;let metadata=null,busy=false,pending=null,epoch=0;const labels={NOT_ISSUED:'미발급',ACTIVE:'키 유효 · 서버 등록 필요',REVOKED:'해제됨',EXPIRED:'만료됨',REISSUE_REQUIRED:'재발급 필요'};const message=s=>$('assistant-access-message').textContent=s;
function hideKey(){$('assistant-access-key').type='password';$('assistant-access-toggle').textContent='보기';$('assistant-access-toggle').setAttribute('aria-pressed','false');$('assistant-access-key').value='';$('assistant-access-secret').hidden=true;}
function controls(){for(const id of ['refresh','issue','revoke'])$('assistant-access-'+id).disabled=busy||(id!=='refresh'&&!metadata)||(id==='revoke'&&(!metadata||['NOT_ISSUED','REVOKED'].includes(metadata.status)));$('assistant-access-scopes').disabled=busy;}
function show(v){metadata=v;$('assistant-access-state').textContent=labels[v.status];$('assistant-access-issue').textContent=v.revision?'조회 키 재발급':'조회 키 발급';$('assistant-access-meta').textContent=(v.expiresAt?'만료 '+new Date(v.expiresAt).toLocaleString('ko-KR')+' · ':'')+(v.lastUsedAt?'최근 접근 '+new Date(v.lastUsedAt).toLocaleString('ko-KR')+' · ':'')+'30일 유효 · 분당 최대 10회';if(v.scopes.length)root.querySelectorAll('#assistant-access-scopes input').forEach(n=>n.checked=v.scopes.includes(n.value));}
async function run(input){if(busy)return;busy=true;const expected=epoch;hideKey();controls();message('권한을 확인하고 있어요…');try{const r=await window.moaonHub.assistantAccess(input);if(expected!==epoch)return;if(!r.ok){metadata=null;$('assistant-access-state').textContent='확인 필요';message(({ASSISTANT_AUTH_REQUIRED:'소유자 계정으로 로그인한 뒤 다시 확인하세요.',ASSISTANT_CONFLICT:'다른 곳에서 권한이 변경되었습니다. 상태를 다시 확인하세요.',ASSISTANT_RESULT_UNKNOWN:'처리 결과를 확인하지 못했습니다. 상태를 확인한 뒤 필요하면 키를 재발급하세요.',ASSISTANT_RATE_LIMITED:'잠시 후 다시 확인하세요.'})[r.code]||'서버 상태를 확인하지 못했습니다. 다시 시도해 주세요.');return;}show(r.value);if(r.key){$('assistant-access-key').value=r.key;$('assistant-access-secret').hidden=false;message('키를 발급했어요. Hermes 서버 등록과 실제 조회 확인이 남아 있습니다.');}else message(input.action==='REVOKE'?'조회 권한을 해제했어요. 기존 키로는 조회할 수 없습니다.':'권한 상태를 확인했어요. 최근 접근 시각은 답변 성공을 보장하지 않습니다.');}catch{metadata=null;message('연결 결과를 확인하지 못했습니다. 상태 확인부터 다시 진행하세요.');}finally{busy=false;controls();}}
$('assistant-access-refresh').onclick=()=>run({action:'STATUS'});$('assistant-access-hide').onclick=hideKey;$('assistant-access-key').onclick=e=>e.target.select();
$('assistant-access-toggle').onclick=()=>{const visible=$('assistant-access-key').type==='password';$('assistant-access-key').type=visible?'text':'password';$('assistant-access-toggle').textContent=visible?'가리기':'보기';$('assistant-access-toggle').setAttribute('aria-pressed',String(visible));};
$('assistant-access-copy').onclick=async()=>{const expected=epoch;if(!$('assistant-access-key').value)return;try{const r=await window.moaonHub.copyEventText($('assistant-access-key').value);if(expected===epoch)message(r?.ok?'조회 키를 복사했어요. Hermes의 키 입력창에 붙여넣으세요.':'복사하지 못했어요. 보기 버튼을 누르고 직접 복사해 주세요.');}catch{if(expected===epoch)message('복사하지 못했어요. 보기 버튼을 누르고 직접 복사해 주세요.');}};
function confirm(action){if(!metadata||busy)return;const scopes=[...root.querySelectorAll('#assistant-access-scopes input:checked')].map(n=>n.value);if(action==='ISSUE'&&!scopes.length){message('조회할 자료를 하나 이상 선택하세요.');return;}pending={action,revision:metadata.revision,...(action==='ISSUE'?{scopes}:{})};$('assistant-access-confirm-title').textContent=action==='ISSUE'?'조회 키를 발급할까요?':'조회 권한을 해제할까요?';$('assistant-access-confirm-body').textContent=action==='ISSUE'?'기존 키는 즉시 사용할 수 없게 됩니다. 새 키를 등록한 Hermes의 승인된 사용자들이 선택한 업무 자료를 조회할 수 있습니다.':'Hermes에서 모아온 자료를 새로 조회할 수 없게 됩니다. 이미 전달한 답변은 삭제되지 않습니다.';$('assistant-access-confirm-run').textContent=action==='ISSUE'?'발급하기':'권한 해제';$('assistant-access-confirm').showModal();}
$('assistant-access-issue').onclick=()=>confirm('ISSUE');$('assistant-access-revoke').onclick=()=>confirm('REVOKE');$('assistant-access-confirm-cancel').onclick=()=>$('assistant-access-confirm').close();$('assistant-access-confirm-run').onclick=()=>{const input=pending;$('assistant-access-confirm').close();if(input)void run(input);};$('assistant-access-confirm').addEventListener('close',()=>pending=null);
root.querySelectorAll('[data-assistant-tab],[data-assistant-go]').forEach(b=>b.addEventListener('click',()=>{epoch++;hideKey();}));new MutationObserver(()=>{if(!root.classList.contains('is-visible')){epoch++;hideKey();}}).observe(root,{attributes:true,attributeFilter:['class']});document.querySelectorAll('[data-action=hub-disconnect]').forEach(b=>b.addEventListener('click',()=>{epoch++;hideKey();metadata=null;controls();}));root.addEventListener('click',e=>{if(e.target.closest('[data-assistant-tab]')){epoch++;hideKey();}});window.addEventListener('pagehide',hideKey);
})();
