'use strict';
(()=>{
 const root=document.querySelector('[data-page=assistant]');if(!root)return;
 const catalog={WORK:[['briefing','📊 업무 브리핑'],['orders','📦 주문·배송'],['cs','💬 고객 문의'],['tasks','✅ 업무 관리'],['knowledge','📚 제품·운영 지식'],['settings','⚙️ 알림 설정']],SOLO:[['tasks','☀️ 오늘 내 업무'],['memo','📝 빠른 메모'],['reminders','⏰ 내 알림'],['focus','🎯 오늘 집중할 일'],['review','🌙 하루 정리'],['settings','⚙️ 내 설정']],STUDY:[['register','📥 자료 등록'],['knowledge','🔎 지식 찾기'],['pending','🕓 검토 대기'],['correct','✏️ 지식 수정'],['quiz','🧪 기억 테스트'],['settings','⚙️ 학습 현황']],SUP:[['health','🛠️ 연결 상태'],['sources','🕓 자료 상태'],['settings','⚙️ 관리 설정']],AD:[['reports','📊 광고 보고서'],['checklist','🔎 수익 검토'],['settings','⚙️ 광고 설정']]};
 const names={WORK:'업무비서',SOLO:'개인비서',STUDY:'지식비서',SUP:'관리비서',AD:'광고비서'};
 const el=(tag,text='',cls='')=>{const n=document.createElement(tag);n.textContent=text;n.className=cls;return n;};
 const button=(parent,text,fn,cls='')=>{const b=el('button',text,cls);b.type='button';b.onclick=fn;parent.append(b);return b;};
 const tab=el('button','봇 메뉴');tab.type='button';tab.dataset.assistantTab='menus';tab.setAttribute('aria-pressed','false');root.querySelector('.assistant-tabs').append(tab);
 const view=el('section');view.dataset.assistantView='menus';view.hidden=true;root.append(view);view.append(el('h2','봇마다 필요한 메뉴만'),el('p','표시할 메뉴와 순서를 고르세요. 저장한 뒤 텔레그램 봇에 “메뉴”를 보내면 새 메뉴가 표시됩니다. 최소 한 개는 선택해야 합니다.','assistant-help'));
 const status=el('p','메뉴를 확인하고 있어요…','assistant-help');status.id='assistant-menu-status';status.setAttribute('role','status');view.append(status);
 const refresh=button(view,'서버 설정 새로고침',()=>run({action:'MENU_READ'}));const grid=el('div','','assistant-bot-grid');view.append(grid);
 let rows=[],busy=false,epoch=0;const drafts=new Map();
 function render(){grid.replaceChildren();for(const slot of ['WORK','SOLO','STUDY','SUP','AD']){const r=rows.find(x=>x.slot===slot);if(!r)continue;const selected=drafts.get(slot)||[...r.items];drafts.set(slot,selected);const card=el('section','','assistant-card');card.dataset.menuSlot=slot;card.append(el('h3',names[slot]),el('p','체크한 메뉴만 표시됩니다. 위·아래 버튼으로 순서를 바꿀 수 있어요.','assistant-help'));grid.append(card);
  const ordered=[...selected,...catalog[slot].map(([k])=>k).filter(k=>!selected.includes(k))];for(const key of ordered){const label=catalog[slot].find(([k])=>k===key)[1],row=el('div','','assistant-actions');row.style.flexWrap='nowrap';row.style.alignItems='center';row.style.marginBottom='8px';row.dataset.menuItem=key;card.append(row);const field=el('label','','assistant-check');field.style.flex='1';field.style.minWidth='0';const check=el('input');check.type='checkbox';check.checked=selected.includes(key);check.setAttribute('aria-label',label);check.disabled=busy||check.checked&&selected.length===1;field.append(check,document.createTextNode(label));row.append(field);check.onchange=()=>{if(busy)return;drafts.set(slot,check.checked?[...selected,key]:selected.filter(x=>x!==key));render();};
  const index=selected.indexOf(key);for(const [delta,text] of [[-1,'↑'],[1,'↓']]){const move=button(row,text,()=>{if(busy)return;const next=[...selected];[next[index],next[index+delta]]=[next[index+delta],next[index]];drafts.set(slot,next);render();});move.setAttribute('aria-label',label+(delta<0?' 위로':' 아래로'));move.disabled=busy||index<0||index+delta<0||index+delta>=selected.length;}}
  card.append(el('h4','텔레그램 메뉴 미리보기'));const preview=el('div');preview.dataset.menuPreview=slot;preview.style.display='grid';preview.style.gridTemplateColumns='repeat(2,minmax(0,1fr))';preview.style.gap='8px';preview.style.marginBottom='16px';for(const key of selected){const tile=el('div',catalog[slot].find(([k])=>k===key)[1],'assistant-card');tile.style.padding='12px 8px';tile.style.textAlign='center';tile.style.overflowWrap='anywhere';preview.append(tile);}card.append(preview);
  const changed=JSON.stringify(selected)!==JSON.stringify(r.items);const save=button(card,'메뉴 저장',()=>run({action:'MENU_SAVE',slot,revision:r.revision,items:[...selected]}),'assistant-primary');save.dataset.menuSave=slot;save.disabled=busy||!changed;card.append(el('p',changed?'저장하지 않은 변경사항이 있어요.':'저장된 메뉴입니다.','assistant-help'));}
 }
 async function run(input){if(busy)return;busy=true;const generation=epoch;refresh.disabled=true;render();view.setAttribute('aria-busy','true');status.textContent='서버 메뉴 설정을 확인하고 있어요…';try{await root.assistantCommonLoad;if(generation!==epoch)return;const result=await window.moaonHub.assistantAutomation(input);if(generation!==epoch)return;if(!result.ok){status.textContent=result.code==='ASSISTANT_CONFLICT'?'다른 곳에서 메뉴 설정이 바뀌었어요. 편집 내용은 유지했습니다. 서버 설정을 새로고침한 뒤 다시 편집해 주세요.':'메뉴 저장 결과를 확인하지 못했어요. 서버 설정 새로고침으로 확인해 주세요.';return;}rows=result.value.menus;if(input.action==='MENU_READ')drafts.clear();else drafts.delete(input.slot);status.textContent=input.action==='MENU_SAVE'?names[input.slot]+' 메뉴를 저장했어요. 텔레그램에 “메뉴”를 보내 확인하세요.':'저장된 봇 메뉴를 불러왔어요.';}catch{status.textContent='서버 연결을 확인하지 못했어요. 잠시 후 다시 시도해 주세요.';}finally{busy=false;refresh.disabled=false;view.removeAttribute('aria-busy');render();}}
 tab.onclick=()=>{root.querySelectorAll('[data-assistant-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b===tab)));root.querySelectorAll('[data-assistant-view]').forEach(v=>v.hidden=v!==view);if(rows.length)render();else void run({action:'MENU_READ'});};
 document.querySelectorAll('[data-action=hub-disconnect]').forEach(b=>b.addEventListener('click',()=>{epoch++;rows=[];drafts.clear();grid.replaceChildren();status.textContent='로그인 후 메뉴를 확인하세요.';}));
})();
