'use strict';
(()=>{
 const host=document.querySelector('.blog-workspace');if(!host)return;
 const el=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;};
 const box=el('section');box.className='blog-image blog-connection';box.setAttribute('aria-label','블로그 대표 이미지');
 box.append(el('small','IMAGE STUDIO · 대표 이미지'),el('h3','글의 첫인상을 만드는 한 장'),el('p','원하는 장면을 설명하거나 실제 제품 사진을 불러오세요. 제목은 사진 위에 또렷하게 배치합니다.'));
 const quota=el('p','이 PC의 이미지 설정을 확인해 주세요.');quota.className='blog-image-budget';
 const settings=el('details'),summary=el('summary','이미지용 Gemini 연결·월 한도');settings.append(summary,el('p','기존 무료 Gemini 글쓰기와 별개입니다. 유료 프로젝트의 이미지용 API 키를 입력하세요. 키는 이 Windows 계정에 암호화해 저장되고 Google에만 전송됩니다. 같은 Windows 계정을 쓰는 사람은 이 설정을 함께 사용합니다.'));
 const label=el('label','이미지용 API 키'),key=el('input');key.id='blog-image-key';key.type='password';key.autocomplete='off';key.maxLength=104;label.htmlFor=key.id;key.placeholder='저장한 키가 있으면 비워두세요';
 const enabledLabel=el('label','유료 이미지 생성 사용'),enabled=el('input');enabled.type='checkbox';enabledLabel.prepend(enabled);
 const settingsSave=el('button','키·사용 설정 저장');settingsSave.type='button';settingsSave.className='content-guide-button';
 const setupGuide=el('ol');['Google AI Studio(aistudio.google.com)의 API 키 메뉴에서 이미지 전용 프로젝트와 키를 준비하세요. 기존 무료 글쓰기 프로젝트와 분리하는 것을 권장합니다.','해당 프로젝트의 결제 연결 여부와 이미지 모델 사용 권한을 Google에서 확인하세요. 모아온이 결제 등록이나 요금제 변경을 대신하지 않습니다.','아래 키 입력칸에 직접 붙여넣고 유료 이미지 생성 사용을 선택한 뒤 저장하세요. 키를 채팅에 보내지 마세요.','장면을 입력하고 이미지 1장 생성을 누르세요. 실패해도 자동 재시도하지 않으며, 네이버 발행에는 저장한 PNG를 직접 첨부합니다.'].forEach(t=>setupGuide.append(el('li',t)));settings.append(setupGuide);
 settings.append(label,key,enabledLabel,el('p','월 $2 · 최대 10회 시도 · 한국시간 월초 초기화. 한 번에 1K 이미지 1장만 요청합니다. 실패·시간 초과도 1회로 계산하며 자동 재시도하지 않습니다.'),el('small','장당 출력 약 $0.067 + 입력·추론 비용. 1회 $0.20을 보수적으로 예약 차감합니다. Google 청구 상한이 아니며 다른 앱·PC의 사용, 세금, 환율은 포함하지 않습니다. 설정 저장은 유료 호출을 하지 않습니다.'),settingsSave);
 const grid=el('div');grid.className='blog-image-grid';const editor=el('div'),preview=el('div');preview.className='blog-image-preview';
 function field(text,id,tag,max){const l=el('label',text),n=el(tag);n.id=id;n.maxLength=max;l.htmlFor=id;editor.append(l,n);return n;}
 const prompt=field('만들고 싶은 장면','blog-image-prompt','textarea',1000);prompt.rows=4;prompt.placeholder='예: 밝은 창가의 나무 식탁, 투명한 찻잔에 따뜻한 작두콩차, 자연스러운 햇빛, 글자와 포장지 없이';
 const headline=field('이미지에 넣을 제목 · 선택','blog-image-headline','input',42);headline.placeholder='예: 오늘의 차 한 잔';
 const actions=el('div');actions.className='blog-actions';const button=(text,parent)=>{const b=el('button',text);b.type='button';b.className='content-guide-button';parent.append(b);return b;};
 const generate=button('AI 이미지 1장 생성',actions),useTitle=button('글 제목 가져오기',actions);editor.append(actions);
 const fileLabel=el('label','내 제품 사진 사용 · Google에 전송하지 않아요'),file=el('input');file.type='file';file.accept='image/png,image/jpeg,image/webp';file.id='blog-image-file';fileLabel.htmlFor=file.id;editor.append(fileLabel,file,el('small','PNG·JPG·WebP, 최대 6MB. 제목 편집·사진 불러오기·PNG 저장에는 생성 비용이 없습니다. AI 생성 결과는 실제 제품 촬영 사진과 구분해 사용하세요.'));
 const canvas=el('canvas');canvas.width=canvas.height=1024;canvas.setAttribute('aria-label','대표 이미지 미리보기');const caption=el('p','사진을 생성하거나 불러오면 여기에 보여요.');
 const resultActions=el('div');resultActions.className='blog-actions';const apply=button('글 미리보기에 적용',resultActions),save=button('PNG 저장',resultActions);apply.disabled=save.disabled=true;
 preview.append(canvas,caption,resultActions);grid.append(editor,preview);
 const status=el('p','이미지용 키를 연결한 뒤 생성하거나, 내 사진으로 시작하세요.');status.setAttribute('role','status');status.className='blog-status';
 box.append(quota,settings,grid,status);host.insertBefore(box,host.querySelector('.blog-editor-grid'));
 let epoch=0,busy=false,image=null,timer=null;const cover=el('img');cover.alt='블로그 대표 이미지';cover.className='blog-article-cover';cover.hidden=true;document.querySelector('.blog-draft-preview').prepend(cover);
 const errors={SETUP_REQUIRED:'이미지용 API 키를 연결하고 사용을 켜 주세요.',KEY_REQUIRED:'키 또는 유료 프로젝트 권한을 확인해 주세요.',QUOTA_BLOCKED:'이 PC의 이번 달 10회 한도에 도달했어요.',DUPLICATE:'이미 처리한 요청입니다. 중복 호출하지 않았어요.',PENDING:'이미지 작업이 진행 중이에요.',TIMEOUT:'90초 안에 완료하지 못했어요. 추가 과금을 피하려고 자동 재시도하지 않았어요. 이번 요청은 1회로 남습니다.',PROVIDER_LIMIT:'Google 사용량 제한에 도달했어요. 자동 재시도하지 않았어요.',INVALID_OUTPUT:'이미지 응답을 확인하지 못했어요. 이번 요청은 1회로 남습니다.',STORAGE_ERROR:'암호화 저장 또는 파일 저장을 완료하지 못했어요.',PROVIDER_ERROR:'Google 요청이 실패했어요. 자동 재시도하지 않았어요. 이번 요청은 1회로 남습니다.',CANCELLED:'요청을 취소했어요. 전송된 요청의 비용은 발생할 수 있어요.'};
 const call=(action,value=null)=>window.moaonHub.blogWorkspace({action,value});
 function showConfig(r){if(!r?.ok)return;enabled.checked=r.enabled;quota.textContent=`이 PC · ${r.month} · ${r.used}/10회 사용 · ${r.remaining}회 남음 · 월 $2 한도`;key.placeholder=r.keyPresent?'키 저장됨 · 변경할 때만 입력':'이미지용 유료 프로젝트 API 키';}
 function lock(v){busy=v;generate.disabled=settingsSave.disabled=file.disabled=v;box.setAttribute('aria-busy',String(v));}
 function draw(){const ctx=canvas.getContext('2d');ctx.clearRect(0,0,1024,1024);ctx.fillStyle='#eeece5';ctx.fillRect(0,0,1024,1024);if(image){const s=Math.min(1024/image.width,1024/image.height);ctx.drawImage(image,(1024-image.width*s)/2,(1024-image.height*s)/2,image.width*s,image.height*s);}else{ctx.fillStyle='#6b7564';ctx.font='42px "Moaon Pretendard", sans-serif';ctx.fillText('한 장의 이야기',84,480);}
  const title=headline.value.trim();if(title){ctx.fillStyle='rgba(248,247,241,.94)';ctx.fillRect(0,750,1024,274);ctx.fillStyle='#283f32';ctx.font='bold 54px "Moaon Pretendard", sans-serif';let line='',row=0;for(const c of title){if(ctx.measureText(line+c).width>864){ctx.fillText(line,80,855+row*72);line=c;row++;}else line+=c;}if(row<3)ctx.fillText(line,80,855+row*72);}
 }
 async function loadImage(data,e){const next=new Image();await new Promise((resolve,reject)=>{next.onload=resolve;next.onerror=reject;next.src=data;});if(e!==epoch)return false;if(next.width*next.height>24000000)throw Error('IMAGE_SIZE');image=next;draw();apply.disabled=save.disabled=false;return true;}
 headline.oninput=draw;useTitle.onclick=()=>{headline.value=document.querySelector('#blog-title').value.slice(0,42);draw();};draw();
 settingsSave.onclick=async()=>{if(busy)return;const e=epoch;lock(true);try{const r=await call('image-settings',{key:key.value.trim(),enabled:enabled.checked,confirmed:true});if(e!==epoch)return;key.value='';showConfig(r);status.textContent=r.ok?'설정을 저장했어요. 키의 실제 사용 가능 여부는 첫 생성 결과로 확인합니다.':errors[r.status]||'설정을 저장하지 못했어요.';}finally{if(e===epoch)lock(false);}};
 generate.onclick=async()=>{if(busy)return;if(!prompt.value.trim()){status.textContent='만들 장면을 먼저 입력해 주세요.';return;}const e=epoch;lock(true);const started=Date.now();status.textContent='Google에 이미지 생성 요청 중…';timer=setInterval(()=>{status.textContent=`이미지 응답을 기다리고 있어요 · ${Math.floor((Date.now()-started)/1000)}초 / 최대 90초`;},1000);
  try{const r=await call('image-generate',{requestId:crypto.randomUUID(),prompt:prompt.value.trim()});if(e!==epoch)return;if(r.ok){status.textContent='이미지를 준비하고 있어요…';if(await loadImage(r.dataUrl,e)){caption.textContent='AI 생성 이미지 · 실제 제품·문구를 확인한 뒤 사용하세요.';status.textContent='이미지를 만들었어요. 제목을 수정하고 미리보기에 적용하거나 PNG로 저장하세요.';}}else status.textContent=errors[r.status]||'이미지를 만들지 못했어요.';const cfg=await call('image-status');if(e===epoch)showConfig(cfg);}catch{if(e===epoch)status.textContent='이미지를 표시하지 못했어요. 자동 재시도하지 않았어요.';}finally{clearInterval(timer);if(e===epoch)lock(false);}};
 file.onchange=async()=>{const e=epoch,f=file.files[0];if(!f)return;if(f.size>6*1024*1024||!['image/png','image/jpeg','image/webp'].includes(f.type)){status.textContent='6MB 이하의 PNG·JPG·WebP 사진을 선택해 주세요.';return;}try{const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(f);});if(await loadImage(data,e)){caption.textContent='직접 불러온 사진 · 외부 전송 없음';status.textContent='사진을 불러왔어요. 제목을 넣고 저장할 수 있어요.';}}catch{if(e===epoch)status.textContent='사진을 읽지 못했어요. 다른 파일을 선택해 주세요.';}};
 apply.onclick=()=>{if(!image)return;cover.src=canvas.toDataURL('image/png');cover.hidden=false;status.textContent='글 미리보기에 적용했어요. 네이버에는 PNG를 저장한 뒤 직접 첨부하세요.';};
 save.onclick=async()=>{if(!image||save.disabled)return;const e=epoch;save.disabled=true;try{const r=await call('image-save',canvas.toDataURL('image/png'));if(e===epoch)status.textContent=r.ok?'PNG 파일을 저장했어요.':r.canceled?'저장을 취소했어요.':'저장에 실패했어요.';}finally{if(e===epoch)save.disabled=false;}};
 settings.addEventListener('toggle',()=>{if(settings.open){const e=epoch;call('image-status').then(r=>{if(e===epoch)showConfig(r);}).catch(()=>{});}});
 document.addEventListener('moaon-session-changed',()=>{epoch++;clearInterval(timer);call('image-cancel').catch(()=>{});lock(false);image=null;key.value=prompt.value=headline.value=file.value='';cover.removeAttribute('src');cover.hidden=true;apply.disabled=save.disabled=true;draw();caption.textContent='사진을 생성하거나 불러오면 여기에 보여요.';status.textContent='사진과 생성 설명을 초기화했어요. 이미지·키 설정은 이 Windows 계정 기준입니다.';});
})();
