'use strict';
(()=>{
 const ops=window.MoaonOperations,{node,button,message,request,field}=window.MoaonOperationsUI;
 function create(onChange){
  let config=null,revision=0,generation=0,busy=false,filter='ALL';const drafts=new Map(),writers=new Map();
  const host=node('section','','ops-card cs-targets'),top=node('div','','ops-toolbar'),summary=node('p','목표 응답시간을 조회해 주세요.','ops-note'),chips=node('div','','ops-segments'),settings=button('응답시간 · 답변 관리',openSettings);settings.id='cs-tools-settings';top.append(node('strong','우리 팀의 응답 목표'),settings);host.append(top,summary,chips);document.querySelector('.cs-filters').before(host);
  const dialog=node('dialog','','ops-dialog');dialog.setAttribute('aria-label','응답시간과 답변 템플릿');document.body.append(dialog);dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});
  function deadline(row){return config?ops.deadline(row,config):{state:'UNKNOWN',due:null,label:'응답 목표 확인 필요'};}
  function render(rows){settings.disabled=!config||busy;chips.replaceChildren();for(const [key,label] of [['ALL','전체'],['OVERDUE','목표 기한 초과'],['SOON','4시간 내 응답'],['UNKNOWN','시각 확인 필요']]){const count=rows.filter(r=>key==='ALL'||deadline(r).state===key).length;const b=button(label+' '+(config?count:'—'),()=>{filter=key;onChange();});b.setAttribute('aria-pressed',String(filter===key));b.disabled=!config;b.dataset.deadlineFilter=key;chips.append(b);}summary.textContent=config?'네이버 '+config.hours.NAVER+'시간 · 쿠팡 '+config.hours.COUPANG+'시간 · 카페24 '+config.hours.CAFE24+'시간 · 접수부터 주말 포함 경과시간 기준, 플랫폼 공식 마감과 별도':'응답 목표 조회 전 · 기본값으로 기한을 판단하지 않습니다.';}
  async function load(){const token=++generation;const r=await request({action:'CS_READ'});if(token!==generation)return;if(r.ok&&Number.isInteger(r.value?.revision)&&(r.value.config===null||ops.csConfig(r.value.config))){config=r.value.config||ops.defaults();revision=r.value.revision;}else{config=null;summary.textContent=message(r.code);}onChange();}
  function openSettings(){if(!config||busy)return;const token=generation;let copy=structuredClone(config);dialog.replaceChildren();const head=node('div','','ops-toolbar');head.append(node('h2','고객 응대 설정'),button('닫기',()=>{if(!busy)dialog.close();}));const form=node('form','','ops-form'),hours=node('div','','ops-grid'),note=node('p','','ops-note');note.setAttribute('role','status');form.append(node('h3','플랫폼별 목표 응답시간'),node('p','1~168시간 · 주말에도 시간이 흐릅니다.','ops-note'),hours);const inputs={};for(const [p,label] of [['NAVER','네이버'],['COUPANG','쿠팡'],['CAFE24','카페24']]){const i=field(hours,label+' (시간)','number',copy.hours[p]);i.min=1;i.max=168;i.step=1;i.required=true;inputs[p]=i;}
   const rows=node('div','','ops-template-list');function add(t){const item=node('section','','ops-template'),title=field(item,'답변 이름','text',t.title),body=field(item,'답변 문구','textarea',t.body);title.maxLength=60;title.required=true;body.maxLength=1500;body.rows=4;body.required=true;item.dataset.templateId=t.id;item.append(button('이 답변 삭제',()=>{item.remove();}));rows.append(item);}
   copy.templates.forEach(add);const addButton=button('+ 답변 템플릿 추가',()=>{if(rows.children.length>=30){note.textContent='답변은 최대 30개까지 저장할 수 있습니다.';return;}add({id:crypto.randomUUID(),title:'',body:''});});const save=node('button','공용 설정 저장');save.type='submit';save.className='primary-action';form.append(node('h3','자주 쓰는 답변'),node('p','개인정보 대신 여러 문의에 사용할 안내 문구를 저장하세요.','ops-note'),rows,addButton,note,save);form.onsubmit=async e=>{e.preventDefault();if(busy)return;copy={hours:Object.fromEntries(Object.entries(inputs).map(([p,i])=>[p,Number(i.value)])),templates:[...rows.children].map(row=>({id:row.dataset.templateId,title:row.querySelector('input').value.trim(),body:row.querySelector('textarea').value.trim()}))};if(!ops.csConfig(copy)){note.textContent='응답시간과 빈 답변 문구를 확인하세요.';return;}busy=true;form.querySelectorAll('input,textarea,button').forEach(i=>i.disabled=true);note.textContent='설정을 저장하고 있습니다…';try{const r=await request({action:'CS_SAVE',revision,config:copy});if(token!==generation)return;if(r.ok&&r.value?.revision===revision+1&&Object.entries(copy.hours).every(([k,v])=>r.value.config?.hours?.[k]===v)&&ops.csConfig(r.value.config)){config=r.value.config;revision=r.value.revision;dialog.close();onChange();}else note.textContent=message(r.code);}finally{busy=false;form.querySelectorAll('input,textarea,button').forEach(i=>i.disabled=false);}};dialog.append(head,form);dialog.showModal();
  }
  function detail(row,parent){const box=node('section','','ops-card cs-reply-draft');box.append(node('h3','답변 준비'),node('p','접수별로 문구를 수정해 복사한 뒤 해당 판매자센터에서 확인·발송하세요. 복사만으로 답변 완료가 되지 않습니다.','ops-note'));if(!config){box.append(node('p','답변 템플릿 연결을 확인하세요.'));parent.append(box);return;}
   const select=field(box,'자주 쓰는 답변','select'),blank=node('option','답변 선택');blank.value='';select.append(blank);for(const t of config.templates){const o=node('option',t.title);o.value=t.id;select.append(o);}const body=field(box,'이번 문의 답변','textarea',drafts.get(row.id)||'');body.maxLength=1500;body.rows=6;body.oninput=()=>drafts.set(row.id,body.value);select.onchange=()=>{const t=config.templates.find(t=>t.id===select.value);if(t){body.value=t.body;drafts.set(row.id,t.body);}};const note=node('p','','ops-note');note.setAttribute('role','status');const copy=button('답변 문구 복사',async()=>{if(!body.value.trim()){note.textContent='답변 문구를 먼저 작성하세요.';return;}copy.disabled=true;try{const r=await window.moaonHub.copyEventText(body.value);note.textContent=r?.ok===true?'복사했습니다. 판매자센터에서 검토 후 발송하세요.':'복사하지 못했습니다. 문구를 직접 선택해 복사하세요.';}catch{note.textContent='복사하지 못했습니다. 문구를 직접 선택해 복사하세요.';}finally{copy.disabled=false;}});box.append(copy,note);
   if(row.platform==='COUPANG'&&row.details?.reply?.available){body.maxLength=1000;box.querySelector('.ops-note').textContent='온라인 상품문의는 모아온에서 쿠팡으로 답변을 전송할 수 있습니다. 최종 확인 후 실제 고객에게 전달됩니다.';const inquiryId=row.id.split(':').at(-1),replyBy=field(box,'쿠팡 Wing 로그인 ID','text');const wingKey='moaon-harin-wing-reply-id';let savedWing='harinfood';try{savedWing=localStorage.getItem(wingKey)||savedWing;}catch{}replyBy.value=writers.get(row.id)||savedWing;replyBy.readOnly=true;replyBy.oninput=()=>writers.set(row.id,replyBy.value);replyBy.autocomplete='off';replyBy.placeholder='판매자 ID가 아닌 Wing 로그인 ID';const wingNote=node('p','하린식품 답변 ID · 이 PC에서 다음 문의에도 사용합니다.','ops-note');const editWing=button('Wing ID 변경',()=>{replyBy.readOnly=false;saveWing.hidden=false;editWing.hidden=true;});const saveWing=button('Wing ID 저장',()=>{const id=replyBy.value.trim();if(!/^[a-zA-Z0-9@._-]{1,100}$/.test(id)){wingNote.textContent='Wing 로그인 ID 형식을 확인하세요.';return;}try{localStorage.setItem(wingKey,id);writers.set(row.id,id);replyBy.readOnly=true;saveWing.hidden=true;editWing.hidden=false;wingNote.textContent='Wing 로그인 ID를 이 PC에 저장했습니다.';}catch{wingNote.textContent='ID 저장에 실패했습니다. 저장 공간을 확인하세요.';}});saveWing.hidden=true;
    const state=node('p','전송 이력을 확인하세요.','ops-note');state.setAttribute('role','status');let sending=false,job=null;const epoch=generation;const current=()=>epoch===generation&&box.isConnected;const refreshInquiry=button('최신 문의 다시 확인',()=>window.moaonCs.refreshInquiry(row.id));refreshInquiry.hidden=true;const changed=()=>{state.textContent='문의 상태가 변경됐습니다. 작성한 답변은 보관했습니다. 최신 문의를 다시 확인해 주세요.';send.disabled=true;refreshInquiry.hidden=false;};
    let pollTimer=null,checking=false;const started=Date.now();const progress=node('ol','','cs-reply-progress');progress.setAttribute('aria-label','답변 처리 단계');for(const text of ['요청 접수','쿠팡 전송','처리 재확인','답변 완료'])progress.append(node('li',text));const timing=node('p','','ops-note');
    const active=()=>['PENDING','RUNNING','EXECUTING','VERIFYING'].includes(job?.status);
    const schedule=()=>{clearTimeout(pollTimer);if(current()&&active())pollTimer=setTimeout(()=>void check.onclick(),5000);};
    const show=v=>{job=v;const labels={NONE:'서버에 접수된 답변이 없습니다. 답변 보내기를 눌러 최종 확인해 주세요.',PENDING:'전송 대기 · 서버 접수 완료, 고정 IP 실행기를 기다립니다.',RUNNING:'실행기에서 쿠팡 답변 전송을 처리 중입니다. 다시 보내지 마세요.',EXECUTING:'쿠팡 API에 답변 전송 중 · 다시 보내지 마세요.',VERIFYING:'쿠팡 API 전송 성공 · 문의를 다시 조회해 답변 완료 여부를 확인 중입니다. 다시 보내지 마세요.',SUCCESS:'쿠팡 답변 완료 확인 · 쿠팡 문의의 답변 완료 상태를 확인했습니다.',FAILED:'답변 처리 실패 · 아래 안내를 확인하세요. 자동 재전송하지 않습니다.',CANCELLED:'답변 요청 중단 · Wing에서 답변 여부를 확인하세요.'};state.textContent=labels[v.status]||'전송 결과 확인 필요 · Wing에서 답변 여부를 확인하세요.';const reason={EXPIRED:'요청 처리 기한이 지났습니다. 실행기 연결을 확인하세요.',IP_CHECK:'쿠팡 허용 IP와 실행기 연결을 확인하세요.',AUTH_CHECK:'Wing 로그인 ID와 쿠팡 API 권한을 확인하세요.',VERIFY_CHECK:'문의 재조회 연결을 확인하지 못했습니다. 재전송하지 말고 전송 상태 확인을 눌러 주세요.',RESULT_CHECK:'완료 여부를 확정할 수 없습니다. Wing 확인 후 관리자에게 문의하세요.'};if(reason[v.reason])state.textContent+=' '+reason[v.reason];const elapsed=Math.max(0,Math.floor((Date.now()-(Date.parse(v.createdAt)||started))/1000));timing.textContent=(v.status==='NONE'?'':('접수 후 '+Math.floor(elapsed/60)+'분 '+elapsed%60+'초 · '))+'마지막 확인 '+new Date().toLocaleTimeString('ko-KR')+(active()?' · 5초마다 자동 확인':'');if(active()&&elapsed>=120)timing.textContent+=' · '+(v.status==='PENDING'?'실행기 시작 지연 · 실행기 연결 확인이 필요합니다.':'처리가 지연되고 있습니다. 완료로 간주하지 말고 상태를 확인하세요.');const index=({NONE:-1,PENDING:0,RUNNING:1,EXECUTING:1,VERIFYING:2,SUCCESS:3})[v.status]??-1;[...progress.children].forEach((n,i)=>{n.dataset.state=i<index?'done':i===index?'current':'waiting';});send.disabled=v.status!=='NONE'||sending;schedule();};
    const check=button('전송 상태 확인',async()=>{if(checking||!current())return;checking=true;check.disabled=true;try{const r=await request({action:'CS_REPLY_STATUS',inquiryId});if(!current())return;if(r.ok)show(r.value);else{state.textContent='상태 조회 실패 · 완료 여부를 확인하지 못했습니다. 전송 상태 확인을 다시 눌러 주세요.';send.disabled=true;clearTimeout(pollTimer);}}finally{checking=false;check.disabled=false;}});
    const send=button('쿠팡에 답변 보내기',()=>{if(sending||job?.status!=='NONE')return;if(body.value.trim().length<2||body.value.trim().length>1000||!/^[a-zA-Z0-9@._-]{1,100}$/.test(replyBy.value.trim())){state.textContent='답변 2~1,000자와 Wing 로그인 ID를 입력하세요.';return;}const draft=body.value.trim(),writer=replyBy.value.trim(),confirm=node('dialog','','ops-dialog');confirm.append(node('h2','쿠팡 고객에게 답변을 보낼까요?'),node('p',row.details?.product?.name||'상품명 확인 필요'),node('p','문의 번호 '+inquiryId),node('p',draft));const submit=button('확인 · 실제 전송',async()=>{confirm.close();sending=true;send.disabled=true;state.textContent='최신 문의 확인 중 · 아직 서버 접수 전입니다.';try{const latest=await window.moaonHub.readCs();if(!current())return;if(latest?.status!=='READY'){state.textContent='최신 문의를 확인하지 못했습니다. 전송하지 않았습니다. 최신 문의 다시 확인을 눌러 주세요.';refreshInquiry.hidden=false;return;}const fresh=latest.items.find(x=>x.id===row.id);const same=fresh?.details?.reply?.available&&fresh.details.status===row.details.status&&fresh.details.body===row.details.body&&fresh.details.title===row.details.title&&JSON.stringify(fresh.details.product)===JSON.stringify(row.details.product);if(!same){changed();return;}state.textContent='답변 요청을 서버에 접수하고 있습니다…';const r=await request({action:'CS_REPLY_SEND',inquiryId,content:draft,replyBy:writer,sourceUpdatedAt:fresh.details.reply.sourceUpdatedAt,confirm:true});if(!current())return;if(r.ok)show(r.value);else if(r.code==='TEAM_CONFLICT')changed();else{const errors={TEAM_INVALID:'요청 입력값이 거절되어 접수되지 않았습니다. 답변 길이와 Wing ID를 확인해 주세요.',TEAM_AUTH_REQUIRED:'로그인이 만료되어 접수되지 않았습니다. 다시 로그인해 주세요.',TEAM_ACCESS_DENIED:'답변 권한을 확인하지 못해 접수되지 않았습니다.',TEAM_BUSY:'다른 작업이 진행 중이라 접수하지 못했습니다. 잠시 뒤 전송 상태를 확인해 주세요.'};state.textContent=errors[r.code]||'서버 접수 여부 확인 필요 · 전송 상태 확인을 눌러 확인하세요. 중복 전송하지 마세요.';send.disabled=true;}}catch{if(current()){state.textContent='전송 결과 확인 필요 · 전송 상태 확인 후 처리하세요.';send.disabled=true;}}finally{sending=false;if(current()&&job?.status==='NONE'&&!refreshInquiry.hidden)send.disabled=true;}});confirm.append(button('취소',()=>confirm.close()),submit);confirm.onclose=()=>confirm.remove();document.body.append(confirm);confirm.showModal();});send.disabled=true;box.append(replyBy.closest('label'),editWing,saveWing,wingNote,send,progress,state,timing,check,refreshInquiry);queueMicrotask(()=>{if(current())void check.onclick();});
   }
   parent.append(box);
  }
  return {load,render,detail,deadline,matches:r=>filter==='ALL'||deadline(r).state===filter,reset:()=>{filter='ALL';},filtered:()=>filter!=='ALL',clear:()=>{generation++;config=null;revision=0;filter='ALL';drafts.clear();writers.clear();dialog.close();busy=false;render([]);}};
 }
 window.MoaonCsTools={create};
})();
