'use strict';
(()=>{
 const $=id=>document.getElementById(id),el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;},button=(text,fn)=>{const n=el('button','',text);n.type='button';n.onclick=fn;return n;};
 let opened=false,busy=false,loading=false,loaded=false,epoch=0,turns=[],reports=[],selected=[],files=[],draft='',conversationId=null,configuration=null,status='',animation=0,pending='',newAnswer=null;
 const uuid=()=>crypto.randomUUID();
 const errors={DISABLED:'Gemini 사용이 꺼져 있어요. 앱 설정에서 확인해 주세요.',SETUP_REQUIRED:'Gemini 연결 설정을 확인해 주세요.',QUOTA_BLOCKED:'현재 사용 한도에 도달했어요. 잠시 뒤 다시 시도해 주세요.',TIMEOUT:'응답 시간이 길어졌어요. 질문은 유지됩니다.',LOGIN_REQUIRED:'로그인 후 Gemini를 사용할 수 있어요.',FORBIDDEN:'사업장 접근 권한을 확인해 주세요.',BLOCKED:'선택한 자료를 확인할 수 없어요. 선택을 해제하거나 다시 조회해 주세요.',INVALID_OUTPUT:'답변을 받지 못했어요. 질문을 바꿔 다시 시도해 주세요.',CANCELLED:'대기를 취소했어요.',ALREADY_PROCESSED:'이미 처리된 요청입니다. 대화 기록을 다시 확인해 주세요.'};
 const message=r=>errors[r?.status]||'연결을 확인한 뒤 다시 시도해 주세요.';
 const launcher=button('✦ Gemini에게 물어보기',()=>opened?close():open());launcher.id='general-chat-launcher';launcher.className='insight-ai-launcher';launcher.setAttribute('aria-controls','general-chat-panel');document.querySelector('.chrome-actions').prepend(launcher);
 function capture(){const input=$('general-chat-question');if(input&&!busy)draft=input.value;}
 function close(){capture();opened=false;render();launcher.focus({preventScroll:true});}
 function clear(){epoch++;void window.moaonHub.cancelGeneralChat();opened=false;busy=false;loading=false;loaded=false;turns=[];selected=[];reports=[];files=[];draft='';pending='';conversationId=null;configuration=null;status='';render();}
 function open(){window.moaonInsightAI?.closeQuestion();opened=true;render();window.moaonInsights?.ensure();if(!loaded&&!loading)void load();}
 async function load(){if(loading||busy)return;loading=true;const e=epoch;render();try{const r=await window.moaonHub.generalChat({operation:'LIST'});if(e!==epoch)return;if(r.ok){configuration=r.configuration;turns=r.turns;loaded=true;if(!conversationId&&turns.length){conversationId=turns[0].conversationId;selected=[...turns[0].reportIds];}status=configuration.ready&&configuration.enabled?'':message(configuration);}else status=message(r);}catch{if(e===epoch)status=message();}finally{if(e===epoch){loading=false;render();}}}
 async function send(){capture();if(busy||loading||!draft.trim())return;conversationId=conversationId||uuid();const question=draft.trim(),e=epoch,input={requestId:uuid(),conversationId,question,reportIds:[...selected],files:[...files]};busy=true;pending=question;draft='';status='';render();try{const r=await window.moaonHub.generalChat({operation:'GENERATE',input});if(e!==epoch)return;if(r.ok){turns=[r.turn,...turns.filter(t=>t.id!==r.turn.id)];newAnswer=r.turn.id;files=[];status='';}else{draft=question;status=message(r);}}catch{if(e===epoch){draft=question;status=message();}}finally{if(e===epoch){busy=false;pending='';render();}}}
 async function attach(list){capture();const e=epoch;for(const file of Array.from(list)){const ext=file.name.split('.').pop().toLowerCase(),mime=({png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',pdf:'application/pdf',txt:'text/plain',md:'text/plain',csv:'text/plain'})[ext];if(!mime){status='이미지(PNG·JPG), PDF, TXT·MD·CSV 파일을 선택해 주세요.';break;}if(files.length>=3||files.reduce((n,f)=>n+f.data.length*3/4,0)+file.size>2*1024*1024){status='파일은 최대 3개, 합계 2MB까지 첨부할 수 있어요.';break;}if(!file.size){status='빈 파일은 첨부할 수 없어요.';break;}const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file);});if(e!==epoch)return;files.push({name:file.name.slice(0,160),mimeType:mime,data});}render();}
 function newChat(){if(busy)return;conversationId=uuid();draft='';files=[];selected=[];status='';render();}
 function deleteChat(){if(busy||!conversationId)return;const id=conversationId,d=el('dialog','insight-ai');d.setAttribute('aria-label','대화 삭제 확인');d.append(el('h2','','이 대화를 삭제할까요?'),el('p','','이 대화의 질문, 답변과 첨부파일을 삭제합니다.'));const no=button('취소',()=>d.close()),yes=button('대화 삭제',async()=>{d.close();const e=epoch;busy=true;render();try{const r=await window.moaonHub.generalChat({operation:'DELETE',conversationId:id});if(e!==epoch)return;if(r.ok){turns=turns.filter(t=>t.conversationId!==id);busy=false;newChat();}else status=message(r);}catch{if(e===epoch)status=message();}finally{if(e===epoch){busy=false;render();}}});d.append(no,yes);d.onclose=()=>d.remove();document.querySelector('.app-area').append(d);d.showModal();no.focus({preventScroll:true});}
 function greeting(){const name=document.querySelector('.settings-profile-identity strong')?.textContent;return name&&!['내 계정','프로필'].includes(name)?name+'님, 안녕하세요':'안녕하세요';}
 function render(){
  cancelAnimationFrame(animation);launcher.setAttribute('aria-expanded',String(opened));const focused=document.activeElement?.id==='general-chat-question';$('general-chat-panel')?.remove();if(!opened)return;
  const panel=el('aside','insight-ai insight-ai-chat general-chat');panel.id='general-chat-panel';panel.setAttribute('aria-labelledby','general-chat-title');const head=el('header','insight-ai-chat-heading'),title=el('h2','','Gemini와 대화');title.id='general-chat-title';head.append(title,button('닫기',close));panel.append(head);
  const tools=el('div','insight-ai-chat-tools');const fresh=button('새 대화',newChat);fresh.disabled=busy;tools.append(fresh);const history=el('details'),summary=el('summary','','대화 기록');history.append(summary);const seen=new Set();for(const turn of turns){if(seen.has(turn.conversationId))continue;seen.add(turn.conversationId);const choice=button(turn.question.slice(0,50),()=>{conversationId=turn.conversationId;selected=[...turn.reportIds];draft='';files=[];status='';render();});choice.disabled=busy;history.append(choice);}if(!seen.size)history.append(el('p','','저장된 대화가 없어요.'));tools.append(history);if(turns.some(t=>t.conversationId===conversationId)){const del=button('대화 삭제',deleteChat);del.disabled=busy;tools.append(del);}panel.append(tools);
  const picker=el('details','insight-ai-picker');picker.append(el('summary','',selected.length?'참고 자료 '+selected.length+'개 선택':'자료 선택 · 선택하지 않아도 대화할 수 있어요'));const choices=el('fieldset','insight-ai-scope');choices.append(el('legend','','선택한 보고서만 Gemini에 함께 보냅니다'));
  for(const report of reports){const label=el('label','insight-ai-choice'),input=el('input');input.type='checkbox';input.checked=selected.includes(report.id);input.disabled=busy||!input.checked&&selected.length>=2;input.onchange=()=>{capture();selected=input.checked?[...selected,report.id]:selected.filter(id=>id!==report.id);render();};label.append(input,el('span','',report.title+' · '+report.periodStart.slice(0,10)+' — '+report.periodEnd.slice(0,10)));choices.append(label);}if(!reports.length)choices.append(el('p','','선택할 보고서를 조회 중이거나 저장된 보고서가 없습니다.'));const reset=button('자료 선택 해제',()=>{capture();selected=[];render();});reset.disabled=busy;choices.append(reset);picker.append(choices);panel.append(picker);
  const log=el('div','insight-ai-transcript');log.setAttribute('role','log');log.setAttribute('aria-label','Gemini 대화');log.tabIndex=0;const chain=turns.filter(t=>t.conversationId===conversationId).slice().reverse();
  function bubble(role,text){const b=el('article','insight-ai-message is-'+role);b.append(el('strong','',role==='user'?'나':'Gemini'));const content=el('p','',text);b.append(content);log.append(b);return content;}
  if(!chain.length&&!busy){const welcome=el('div','general-chat-welcome');welcome.append(el('h3','general-chat-greeting',greeting()),el('p','','무엇을 도와드릴까요?'));const suggestions=selected.length?['선택한 자료의 핵심 내용을 정리해 줘','이 자료를 보고 어떤 질문을 해보면 좋을까?','다음 행동을 함께 생각해 줘']:['아이디어를 같이 생각해 줘','결정하는 것을 도와줘','새로운 개념을 쉽게 설명해 줘'];for(const text of suggestions)welcome.append(button('✦ '+text,()=>{draft=text;render();$('general-chat-question').focus({preventScroll:true});}));log.append(welcome);}
  let animateNode=null,animateText='';for(const t of chain){const q=bubble('user',t.question);if(t.reportIds.length)q.parentNode.append(el('small','','참고 보고서 '+t.reportIds.length+'개'));for(const f of t.files||[])q.parentNode.append(el('small','','첨부 · '+f.name));const answer=bubble('assistant',t.answer.replace(/\*\*(.+?)\*\*/g,'$1'));if(t.id===newAnswer){animateNode=answer;animateText=answer.textContent;}}
  if(busy&&pending){bubble('user',pending);const thinking=el('div','general-chat-thinking');thinking.setAttribute('role','status');thinking.append(el('span','','Gemini가 생각 중'));for(let i=0;i<3;i++)thinking.append(el('i'));log.append(thinking);}panel.append(log);
  const composer=el('div','insight-ai-composer'),chips=el('div','general-chat-files');for(const [i,f] of files.entries()){const chip=button('첨부 · '+f.name+' ×',()=>{capture();files.splice(i,1);render();});chip.disabled=busy;chips.append(chip);}composer.append(chips);
  const input=el('textarea');input.id='general-chat-question';input.rows=3;input.maxLength=4000;input.placeholder='무엇이든 물어보세요';input.setAttribute('aria-label','Gemini에게 질문');input.value=busy?'':draft;input.disabled=busy;const sendButton=button('보내기',send);sendButton.dataset.generalSend='';const update=()=>{draft=input.value;sendButton.disabled=busy||loading||!draft.trim()||configuration?.ready===false||configuration?.enabled===false;};input.oninput=update;input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();if(!sendButton.disabled)void send();}};
  composer.append(input);const controls=el('div','insight-ai-actions');const upload=el('input');upload.type='file';upload.multiple=true;upload.accept='.png,.jpg,.jpeg,.pdf,.txt,.md,.csv';upload.hidden=true;upload.onchange=()=>void attach(upload.files).catch(()=>{status='파일을 읽지 못했어요.';render();});const add=button('＋ 파일 첨부',()=>upload.click());add.disabled=busy;controls.append(add,sendButton,upload);composer.append(controls);const state=el('p','insight-ai-chat-status',loading?'Gemini 연결과 기록을 확인하고 있어요…':status);state.setAttribute('role','status');composer.append(state);if(status&&!busy&&!loading)composer.append(button('연결·기록 다시 확인',load));composer.append(el('p','general-chat-help','Enter 전송 · Shift+Enter 줄바꿈 · 파일 3개 / 총 2MB'));composer.append(el('p','general-chat-help','질문과 선택한 첨부만 Gemini로 전송됩니다. 민감한 개인정보는 넣지 마세요.'));panel.append(composer);document.querySelector('.app-area').append(panel);update();log.scrollTop=log.scrollHeight;if(focused&&!busy)input.focus({preventScroll:true});
  if(animateNode){newAnswer=null;if(!matchMedia('(prefers-reduced-motion: reduce)').matches){const letters=Array.from(animateText);let count=0;animateNode.textContent='';const step=()=>{if(!animateNode.isConnected)return;const follow=log.scrollHeight-log.scrollTop-log.clientHeight<60;count=Math.min(letters.length,count+Math.max(3,Math.ceil(letters.length/100)));animateNode.textContent=letters.slice(0,count).join('');if(follow)log.scrollTop=log.scrollHeight;if(count<letters.length)animation=requestAnimationFrame(step);};animation=requestAnimationFrame(step);}}
 }
 window.moaonGeneralChat=Object.freeze({open,close,clear,setReports:value=>{if(Array.isArray(value)){capture();reports=value;render();}}});
 new MutationObserver(()=>{const n=document.querySelector('.general-chat-greeting');if(n)n.textContent=greeting();}).observe(document.querySelector('#business-settings-open'),{attributes:true,childList:true,subtree:true});
 window.addEventListener('moaon-ai-keys-changed',e=>{if(e.detail?.provider==='GEMINI'){loaded=false;if(opened)void load();}});document.querySelector('.app-area').addEventListener('keydown',e=>{if(e.key==='Escape'&&opened&&!document.querySelector('dialog[open]')){e.preventDefault();close();}});render();
})();
