'use strict';
(()=>{
 const host=document.createElement('section');host.id='marketing-workbench';host.hidden=true;document.querySelector('#insights-metrics').before(host);
 let value=null,period='WEEK',order='cost',term='',campaign=null,view='trend';
 const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
 const num=(v,d=0)=>typeof v==='number'?v.toLocaleString('ko-KR',{maximumFractionDigits:d}):'확인 필요';
 const fmt=(v,unit='',d=0)=>typeof v==='number'?num(v,d)+unit:'확인 필요';
 const button=(label,action,active=false)=>{const b=el('button','',label);b.type='button';b.setAttribute('aria-pressed',String(active));b.onclick=action;return b;};
 const svgEl=(tag,attrs={})=>{const n=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v]of Object.entries(attrs))n.setAttribute(k,v);return n;};
 const metricNames={cost:'광고비',revenue:'전환매출',conversions:'전환수',roas:'ROAS',cpa:'전환 CPA',cvr:'전환율',impressions:'노출',clicks:'클릭',ctr:'클릭률',cpc:'평균 CPC'};
 function chart(w){
  const box=el('section','marketing-chart'),head=el('header');head.append(el('h2','',view==='trend'?'광고비와 전환매출':'광고비 대비 캠페인 효율'));const tabs=el('div','marketing-switch');tabs.append(button('일별 추이',()=>{view='trend';render();},view==='trend'),button('효율 분포',()=>{view='scatter';render();},view==='scatter'));head.append(tabs);box.append(head);
  const svg=svgEl('svg',{viewBox:'0 0 720 230',role:'img','aria-label':view==='trend'?'일별 광고비와 전환매출, 단위 원':'캠페인 광고비와 ROAS 분포'}),left=64,right=700,top=18,bottom=190;
  const axisText=(x,y,text,anchor='end')=>{const t=svgEl('text',{x,y,'text-anchor':anchor});t.textContent=text;svg.append(t);};
  const points=view==='trend'?w.series:w.campaigns.filter(c=>c.cost!==null&&c.roas!==null),max=Math.max(1,...points.flatMap(p=>view==='trend'?[p.cost||0,p.revenue||0]:[p.roas||0]));
  for(let i=0;i<4;i++){const y=top+(bottom-top)*i/3;svg.append(svgEl('line',{x1:left,x2:right,y1:y,y2:y,class:'chart-grid'}));axisText(left-8,y+4,num(max*(1-i/3),0)+(view==='scatter'?'%':''));}
  if(view==='trend'){
   for(const [key,cls]of [['cost','chart-cost'],['revenue','chart-revenue']]){
    let previous=null;points.forEach((p,i)=>{if(p[key]===null){previous=null;return;}const x=left+i*(right-left)/Math.max(1,points.length-1),y=bottom-p[key]/max*(bottom-top);if(previous)svg.append(svgEl('line',{x1:previous.x,y1:previous.y,x2:x,y2:y,class:cls}));const dot=svgEl('circle',{cx:x,cy:y,r:4,class:cls,tabindex:0});const title=svgEl('title');title.textContent=`${p.date} ${metricNames[key]} ${fmt(p[key],'원')}`;dot.append(title);dot.onfocus=()=>{info.textContent=title.textContent;};dot.onmouseenter=dot.onfocus;svg.append(dot);previous={x,y};});
   }
   for(const i of [0,Math.floor((points.length-1)/2),points.length-1])if(points[i])axisText(left+i*(right-left)/Math.max(1,points.length-1),218,points[i].date.slice(5),'middle');
  }else{
   const maxCost=Math.max(1,...points.map(p=>p.cost));for(const p of points){const dot=svgEl('circle',{cx:left+p.cost/maxCost*(right-left),cy:bottom-p.roas/max*(bottom-top),r:7,class:'chart-revenue',tabindex:0,role:'button','aria-label':`${p.name} 광고비 ${fmt(p.cost,'원')} ROAS ${fmt(p.roas,'%',1)} 상세 보기`});const t=svgEl('title');t.textContent=dot.getAttribute('aria-label');dot.append(t);dot.onclick=()=>{campaign=p.id;render();document.querySelector('#marketing-campaign-detail')?.focus({preventScroll:true});};dot.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();dot.onclick();}};svg.append(dot);}axisText(left,218,'0원','start');axisText(right,218,fmt(maxCost,'원'));
  }
  const info=el('p','marketing-chart-info',view==='trend'?'보라: 전환매출 · 초록: 광고비 · 점을 가리키거나 Tab으로 금액 확인':'점을 선택하면 캠페인 근거를 확인합니다.');
  if(points.some(p=>view==='trend'?p.cost!==null||p.revenue!==null:true))box.append(svg);else box.append(el('p','','표시할 광고 원천 자료가 없습니다. 수집 상태를 확인하세요.'));
  box.append(info);return box;
 }
 function render(){
  host.hidden=!value;document.querySelector('#insights-metrics').hidden=!!value;document.querySelector('#insights-flow').hidden=!!value;if(!value){host.replaceChildren();return;}
  const w=value.windows.find(w=>w.id===period)||value.windows[0];if(!w){host.replaceChildren(el('p','','광고 분석 자료 확인 필요'));return;}
  const toolbar=el('div','marketing-toolbar'),presets=el('div','marketing-switch');presets.setAttribute('aria-label','광고 분석 기간');for(const p of value.windows)presets.append(button(p.label,()=>{period=p.id;campaign=null;render();},p.id===w.id));toolbar.append(presets,el('span','',`${w.start} ~ ${w.end} · 오늘 제외`));
  const source=el('p','marketing-source',`관측일 ${w.coveredDays}/${w.days}일 · ${w.status==='UNAVAILABLE'?'조회 실패':w.status==='PARTIAL'?'일부 자료 확인 필요':w.status==='NO_DATA'?'저장 자료 없음':'저장 실적'} · 원천 갱신 ${value.sourceAt?new Date(value.sourceAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',hour12:false,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'확인 필요'}`);
  const metrics=el('div','marketing-metrics');for(const key of ['cost','revenue','conversions','roas','cpa','cvr']){const card=el('article',''),unit=['cost','revenue','cpa'].includes(key)?'원':['roas','cvr'].includes(key)?'%':'회',v=w.metrics[key],prev=w.previous[key];card.append(el('span','',metricNames[key]),el('strong','',fmt(v,unit,unit==='%'?1:0)));const comparable=w.coveredDays===w.days&&w.previousCoveredDays===w.days&&v!==null&&prev!==null;const change=comparable&&prev>0?(v-prev)/prev*100:null;card.append(el('small','',change!==null?`직전 ${w.days}일 대비 ${change>0?'+':''}${num(change,1)}%`:comparable&&prev===0?'직전 0 · 증감률 계산 불가':'비교 자료 확인 필요'));metrics.append(card);}
  const secondary=el('div','marketing-secondary');for(const key of ['impressions','clicks','ctr','cpc'])secondary.append(el('span','',`${metricNames[key]} ${fmt(w.metrics[key],key==='ctr'?'%':key==='cpc'?'원':'회',key==='ctr'?2:0)}`));
  const diagnosis=el('section','marketing-diagnosis');diagnosis.append(el('h2','','이번 기간 확인할 일'),el('small','','서버 계산값에 따른 규칙 진단 · AI 작성 아님'));
  const findings=[];if(w.coveredDays<w.days||w.status!=='OBSERVED')findings.push(['수집 근거부터 확인','기간 누락이나 원천 값 누락이 있어 성과 변화 판단을 보류합니다.']);const waste=w.campaigns.filter(c=>c.cost>0&&c.conversions===0);if(waste.length)findings.push([`전환이 없는 집행 ${waste.length}개`,`${waste.map(c=>c.name).slice(0,3).join(', ')} · 전환 지연과 표본을 확인한 뒤 검색어·상품 조건을 검토하세요.`]);if(w.metrics.clicks>0&&w.metrics.conversions!==null&&w.metrics.conversions<3)findings.push(['아직 작은 전환 표본','적은 표본의 ROAS만 보고 증액·중지를 결정하지 마세요.']);if(!findings.length)findings.push(['캠페인별 비용과 효율 비교','아래 목록에서 비용이 큰 대상부터 확인하세요. 원가·재고 연결 전에는 수익성이나 증액 가능성을 확정하지 않습니다.']);for(const [title,body]of findings.slice(0,3)){const row=el('article');row.append(el('h3','',title),el('p','',body));diagnosis.append(row);}
  const campaigns=el('section','marketing-campaigns'),heading=el('header');heading.append(el('h2','','캠페인 성과'));const search=el('input');search.type='search';search.placeholder='캠페인 검색';search.setAttribute('aria-label','캠페인 검색');search.value=term;search.onchange=()=>{term=search.value;render();};const sort=el('select');sort.setAttribute('aria-label','캠페인 정렬');for(const [key,label]of [['cost','광고비 높은 순'],['revenue','전환매출 높은 순'],['roas','ROAS 높은 순']]){const op=el('option','',label);op.value=key;sort.append(op);}sort.value=order;sort.onchange=()=>{order=sort.value;render();};heading.append(search,sort);campaigns.append(heading,el('p','',`표시 ${w.campaigns.length}/${w.campaignCount}개 · 비용 상위 50개까지 · 전환은 구매 외 행동을 포함할 수 있습니다.`));
  const table=el('div','marketing-table');table.setAttribute('role','table');table.setAttribute('aria-label','캠페인 광고 실적');const header=el('div','marketing-row is-heading');for(const t of ['캠페인','광고비','전환매출','ROAS','전환'])header.append(el('span','',t));table.append(header);
  for(const c of w.campaigns.filter(c=>c.name.toLocaleLowerCase().includes(term.toLocaleLowerCase())).sort((a,b)=>(b[order]??-1)-(a[order]??-1))){const row=button('',()=>{campaign=campaign===c.id?null:c.id;render();},campaign===c.id);row.className='marketing-row';const name=el('span');name.append(el('strong','',c.name),el('small','',`${c.type} · ${c.decision}`));row.append(name,el('span','',fmt(c.cost,'원')),el('span','',fmt(c.revenue,'원')),el('span','',fmt(c.roas,'%',1)),el('span','',fmt(c.conversions,'회')));table.append(row);}campaigns.append(table);
  const chosen=w.campaigns.find(c=>c.id===campaign);if(chosen){const detail=el('article','marketing-campaign-detail');detail.id='marketing-campaign-detail';detail.tabIndex=-1;detail.append(el('h3','',chosen.name),el('p','',`노출 ${fmt(chosen.impressions,'회')} · 클릭 ${fmt(chosen.clicks,'회')} · CTR ${fmt(chosen.ctr,'%',2)} · CPC ${fmt(chosen.cpc,'원')} · 전환율 ${fmt(chosen.cvr,'%',2)} · CPA ${fmt(chosen.cpa,'원')}`),el('p','','광고 귀속 기준의 관측 실적입니다. 원가·재고·전환 집계 조건을 함께 확인해야 합니다.'));campaigns.append(detail);}
  const keyword=el('details','marketing-keywords');keyword.append(el('summary','',`키워드 비용 상위 자료 · ${value.keywords.start||'기간 미확인'} ~ ${value.keywords.end||'미확인'}`),el('p','','키워드는 저장된 별도 기간의 상위 자료입니다. 위 캠페인 기간과 다를 수 있으며 합산하지 않습니다.'));for(const k of value.keywords.rows){const r=el('article');r.append(el('strong','',k.name),el('span','',`광고비 ${fmt(k.cost,'원')} · 클릭 ${fmt(k.clicks,'회')} · 전환 ${fmt(k.conversions,'회')} · 전환매출 ${fmt(k.revenue,'원')}`));keyword.append(r);}if(!value.keywords.rows.length)keyword.append(el('p','','키워드 자료 확인 필요'));
  const automation=el('section','marketing-automation');const a=value.automation;automation.append(el('h2','','주간 보고서 자동화'),el('p','',a.schedule),el('strong','',({SUCCESS:'최근 실행 완료',PARTIAL:'최근 실행 일부 확인 필요',FAILED:'최근 실행 실패',RUNNING:'생성 중',UNVERIFIED:'실행 이력 확인 필요'})[a.status]||'실행 상태 확인 필요'),el('p','',a.finishedAt?`최근 완료 시각 ${new Date(a.finishedAt).toLocaleString('ko-KR')}`:'서버 예약 설정과 실제 완료 이력을 구분합니다.'),button('저장 보고서 보기',()=>document.querySelector('#insights-reports').scrollIntoView({block:'start'})),el('small','','앱을 닫아도 서버 예약으로 실행됩니다. AI 제공자 연결 전에는 기존 규칙 보고서를 사용합니다.'));
  const notes=el('details','marketing-notes');notes.append(el('summary','','계산식·자료 기준'));for(const t of [...value.notes,'ROAS=전환매출÷광고비×100 · CPA=광고비÷전환수 · CTR=클릭÷노출×100 · CVR=전환÷클릭×100. 분모0은 계산 불가입니다.'])notes.append(el('p','',t));
  host.replaceChildren(toolbar,source,metrics,secondary,chart(w),diagnosis,campaigns,keyword,automation,notes);
 }
 window.moaonMarketing={set:v=>{if(v===value)return;value=v;campaign=null;render();}};
})();
