'use strict';
(()=>{
 const $=id=>document.getElementById(id),el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
 const root=el('section','research-box market-ai');root.id='market-ai';root.setAttribute('aria-labelledby','market-ai-title');$('research-results').after(root);
 const header=el('header'),title=el('div');title.append(el('span','eyebrow','PUBLIC TREND · GEMINI'));const h=el('h3','','공개 검색 추이 해석');h.id='market-ai-title';title.append(h);header.append(title);root.append(header);
 root.append(el('p','research-help','검색어 원문·비교 상품·메모는 Gemini에 전송하지 않습니다. 공개 날짜·상대 지수 자료와 그 계산값만 사용합니다.'));
 const context=el('p','market-ai-context'),actions=el('div','market-ai-actions'),status=el('p','research-help'),output=el('div','market-ai-output');status.id='market-ai-status';status.setAttribute('role','status');status.setAttribute('aria-live','polite');
 const kinds={TREND_EXPLANATION:'검색 관심 추이 설명',SEASONAL_NOTES:'시즌 기획 참고점'};
 const buttons=Object.entries(kinds).map(([kind,label])=>{const b=el('button','',label);b.type='button';b.dataset.marketAiKind=kind;b.onclick=()=>generate(kind);actions.append(b);return b;});
 const cancel=el('button','','해석 취소');cancel.type='button';cancel.hidden=true;cancel.onclick=()=>{invalidate();status.textContent='해석 요청을 취소했습니다.';sync();};actions.append(cancel);
 root.append(context,actions,status,el('p','research-help','관심도는 검색 횟수·판매량·매출이 아닙니다. 최근 30일·90일 자료에는 전년 비교가 없어 매년 반복되는 계절성을 확인할 수 없습니다. 시즌 참고점은 추가 확인이 필요한 가설입니다.'),output);
 let research=null,configuration=null,configPending=false,configEpoch=0,epoch=0,pending=false;
 const date=v=>v&&Number.isFinite(Date.parse(v))?new Date(v).toLocaleString('ko-KR'):'확인 필요';
 function matches(){return research&&$('research-query').value.trim()===research.query&&Number($('research-days').value)===research.days;}
 function sync(){const ready=matches()&&research.trendStatus==='READY'&&configuration?.enabled===true&&configuration?.ready===true;buttons.forEach(b=>b.disabled=!ready||pending);cancel.hidden=!pending;root.setAttribute('aria-busy',String(pending));context.textContent=research?'“'+research.query+'” · 최근 '+research.days+'일 · 조회 '+date(research.checkedAt):'시장 자료를 조회한 뒤 원하는 해석을 선택하세요.';}
 function invalidate(){epoch++;if(pending)Promise.resolve(window.moaonHub.cancelMarketAi()).catch(()=>{});pending=false;output.replaceChildren();}
 function message(){return !research?'시장 조사를 먼저 진행해 주세요.':!matches()?'입력한 키워드·기간으로 시장 조사를 다시 진행해 주세요.':research.trendStatus!=='READY'?'검색 추이를 확인하지 못해 해석을 보류합니다.':configPending?'해석 사용 설정을 확인하고 있어요.':!configuration?'해석 설정을 확인하지 못했습니다. 시장 조사를 다시 진행해 주세요.':!configuration.enabled?'공개 추이 AI 해석이 꺼져 있습니다. 시장조사와 비교 상품은 계속 이용할 수 있습니다.':!configuration.ready?'공개 추이 AI 연결 준비가 필요합니다. 시장조사와 비교 상품은 계속 이용할 수 있습니다.':'버튼을 누를 때만 공개 자료를 다시 조회하고 해석합니다.';}
 async function config(){if(configuration||configPending)return;configPending=true;const token=++configEpoch;status.textContent=message();try{const r=await window.moaonHub.marketAi({operation:'CONFIG'});if(token!==configEpoch)return;configuration=r.ok?r.configuration:null;}catch{if(token!==configEpoch)return;configuration=null;}finally{if(token===configEpoch){configPending=false;status.textContent=message();sync();}}}
 function setResearch(value){invalidate();research={query:value.query,days:value.days,checkedAt:value.checkedAt,trendStatus:value.trendStatus};status.textContent=message();sync();if(matches())void config();}
 function clear(){if(configPending)Promise.resolve(window.moaonHub.cancelMarketAi()).catch(()=>{});invalidate();research=null;configuration=null;configEpoch++;configPending=false;status.textContent=message();sync();}
 const notices={DISABLED:'공개 추이 AI 해석이 꺼져 있습니다.',SETUP_REQUIRED:'공개 추이 AI 연결 준비가 필요합니다.',AUTH_REQUIRED:'사업장 로그인 후 다시 조사해 주세요.',LOGIN_REQUIRED:'사업장 로그인 후 다시 조사해 주세요.',DISCONNECTED:'사업장을 다시 연결해 주세요.',FORBIDDEN:'사업장 연결을 다시 확인해 주세요.',QUOTA_BLOCKED:'현재 해석 사용 한도에 도달했습니다.',TIMEOUT:'응답 시간이 초과됐습니다. 다시 시도해 주세요.',STALE:'원천 자료가 오래되어 판단을 보류합니다.',BLOCKED:'원천 자료가 부족하여 판단을 보류합니다.',INVALID_OUTPUT:'근거 검증을 통과하지 못해 해석을 표시하지 않았습니다.',CANCELLED:'해석 요청을 취소했습니다.'};
 async function generate(kind){if(pending||!matches()||research.trendStatus!=='READY'||!configuration?.enabled||!configuration?.ready)return;invalidate();pending=true;const token=epoch,input={requestId:crypto.randomUUID(),kind,query:research.query,days:research.days};status.textContent='공개 검색 추이를 확인하고 해석하고 있어요…';sync();try{const r=await window.moaonHub.marketAi({operation:'GENERATE',input});if(token!==epoch||!matches())return;if(!r.ok){status.textContent=notices[r.status||r.code]||'해석을 마치지 못했습니다. 잠시 후 다시 시도해 주세요.';return;}render(r.run);status.textContent=(r.run.dataState==='PARTIAL'?'일부 자료 확인 필요 · ':'')+'해석 완료'+(r.run.reused?' · 동일 근거의 기존 해석':'');}catch{if(token===epoch)status.textContent='해석을 마치지 못했습니다. 다시 시도해 주세요.';}finally{if(token===epoch){pending=false;sync();}}}
 function render(run){output.replaceChildren();const lines=[kinds[run.kind]||'공개 검색 추이 해석','기간: '+run.period.start+' — '+run.period.end,'원천 조회: '+date(run.sourceAsOf),'모델: '+run.model,'해석 시각: '+date(run.createdAt)];output.append(el('p','market-ai-meta',lines.slice(1).join(' · ')),el('p','market-ai-answer',run.answer));lines.push(run.answer);const grid=el('div','market-ai-cards');for(const card of run.cards){const box=el('article','market-ai-card');for(const [label,value]of [['관측',card.observation],['가설 · 판단 보류',card.hypothesis],['다음 확인',card.nextCheck]]){box.append(el('h4','',label),el('p','',value));lines.push(label+': '+value);}const refs=el('div','market-ai-metrics');for(const id of card.metricRefs){const m=run.metrics[id];if(!m)continue;const text=m.definition+' · '+(typeof m.value==='number'&&Number.isFinite(m.value)?new Intl.NumberFormat('ko-KR',{maximumFractionDigits:2}).format(m.value)+(m.unit==='INDEX_POINT'?' 지수 포인트':' 지수'):'확인 필요');refs.append(el('p','',text));lines.push(text);}box.append(refs);grid.append(box);}output.append(grid);for(const text of [...run.nextChecks,...run.exclusions]){output.append(el('p','research-help',text));lines.push(text);}if(run.usage)output.append(el('p','research-help','토큰 · 입력 '+(run.usage.promptTokens??'확인 필요')+' / 출력 '+(run.usage.completionTokens??'확인 필요')));
 // Keep links out of provider prose. Source identity is shown as plain text.
 output.append(el('p','research-help','출처: 네이버 검색 관심도 공개 자료 · 전년 비교 없음'));
 lines.push('검색 관심 상대지수이며 실제 검색량·매출이 아닙니다. 전년 비교 없음 · 계절성 판단 보류.');const copy=el('button','','해석 요약 복사'),copyState=el('span','research-help'),text=el('textarea','market-ai-copy');text.readOnly=true;text.setAttribute('aria-label','복사할 AI 해석 요약');text.value=lines.join('\n').slice(0,24000);text.hidden=true;copy.type='button';copy.onclick=()=>{text.hidden=false;text.select();let copied=false;try{copied=document.execCommand('copy');}catch{}copyState.textContent=copied?'해석 요약을 복사했습니다.':'선택된 요약을 Ctrl+C로 복사해 주세요.';if(copied){text.hidden=true;copy.focus();}};output.append(copy,copyState,text);
 }
 for(const id of ['research-query','research-days'])$(id).addEventListener(id==='research-query'?'input':'change',()=>{invalidate();research=null;status.textContent='키워드·기간이 바뀌었습니다. 시장 조사를 다시 진행해 주세요.';sync();});
 window.addEventListener('moaon-ai-keys-changed',event=>{if(event.detail?.provider!=='GEMINI')return;configEpoch++;configPending=false;configuration=null;sync();if(matches())void config();});
 window.moaonMarketAI={setResearch,clear};status.textContent=message();sync();
})();
