'use strict';
(function(root,factory){const api=factory();if(typeof module==='object')module.exports=api;else root.MoaonOperations=api;})(typeof globalThis!=='undefined'?globalThis:this,()=>{
 const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
 const date=v=>typeof v==='string'&&/^20\d{2}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v;
 const text=(v,n,min=0)=>typeof v==='string'&&v.length<=n&&v.trim().length>=min;
 const keys=(v,k)=>v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).length===k.length&&k.every(n=>Object.hasOwn(v,n));
 const frequencies={DAILY:'매일',WEEKLY:'매주',MONTHLY:'매월'};
 function recurrence(v){return keys(v,['frequency','count'])&&Object.hasOwn(frequencies,v.frequency)&&Number.isInteger(v.count)&&v.count>=2&&v.count<=52;}
 function dates(start,rule){if(!date(start)||!recurrence(rule))throw Error('반복 날짜와 횟수(2~52회)를 확인하세요.');const anchor=new Date(start+'T00:00:00Z'),result=[];for(let i=0;i<rule.count;i++){let d=new Date(anchor);if(rule.frequency==='MONTHLY'){d=new Date(Date.UTC(anchor.getUTCFullYear(),anchor.getUTCMonth()+i,1));d.setUTCDate(Math.min(anchor.getUTCDate(),new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate()));}else d.setUTCDate(d.getUTCDate()+i*(rule.frequency==='WEEKLY'?7:1));const key=d.toISOString().slice(0,10);if(!date(key))throw Error('반복 종료일은 2099년 이내여야 합니다.');result.push(key);}return result;}
 const defaults=()=>({hours:{NAVER:24,CAFE24:24,COUPANG:24},templates:[
  {id:'delivery',title:'배송 일정 확인',body:'안녕하세요, 하린식품입니다. 문의하신 주문의 출고 및 배송 상황을 확인한 뒤 안내드리겠습니다.'},
  {id:'exchange',title:'교환·반품 안내',body:'안녕하세요, 하린식품입니다. 교환·반품을 원하시는 상품과 사유를 알려주시면 주문 내역과 접수 조건을 확인해 안내드리겠습니다.'},
  {id:'storage',title:'보관법 확인',body:'안녕하세요, 하린식품입니다. 구매하신 상품명을 알려주시면 제품에 표시된 보관 방법을 확인해 안내드리겠습니다.'}
 ]});
 function csConfig(v){return keys(v,['hours','templates'])&&keys(v.hours,['NAVER','CAFE24','COUPANG'])&&Object.values(v.hours).every(n=>Number.isInteger(n)&&n>=1&&n<=168)&&Array.isArray(v.templates)&&v.templates.length<=30&&new Set(v.templates.map(t=>t?.id)).size===v.templates.length&&v.templates.every(t=>keys(t,['id','title','body'])&&text(t.id,50,1)&&/^[a-zA-Z0-9_-]+$/.test(t.id)&&text(t.title,60,1)&&text(t.body,1500,1));}
 function deadline(row,config,now=Date.now()){const start=Date.parse(row.occurredAt),hours=config?.hours?.[row.platform];if(!row.occurredAt||!Number.isFinite(start)||!Number.isInteger(hours)||start>now)return {state:'UNKNOWN',due:null,label:'접수 시각 확인 필요'};const due=start+hours*3600000,left=due-now;return {due,state:left<=0?'OVERDUE':left<=4*3600000?'SOON':'WAITING',label:left<=0?'목표 기한 '+Math.max(1,Math.ceil(-left/3600000))+'시간 경과':Math.ceil(left/3600000)+'시간 남음'};}
 function validCommand(v){if(v?.action==='CS_READ'||v?.action==='STOCK_PLAN_READ')return keys(v,['action']);if(v?.action==='CS_SAVE')return keys(v,['action','revision','config'])&&Number.isInteger(v.revision)&&v.revision>=0&&csConfig(v.config);if(v?.action==='RESERVE')return keys(v,['action','id','revision','lotId','eventId','quantity'])&&[v.id,v.lotId,v.eventId].every(x=>UUID.test(x||''))&&Number.isInteger(v.revision)&&v.revision>=0&&typeof v.quantity==='number'&&Number.isFinite(v.quantity)&&v.quantity>0&&v.quantity<=1e9&&Math.abs(v.quantity*1000-Math.round(v.quantity*1000))<1e-6;if(v?.action==='RELEASE')return keys(v,['action','id','revision'])&&UUID.test(v.id||'')&&Number.isInteger(v.revision)&&v.revision>0;return false;}
 function stockPlan(lots,reservations,events,today){const liveEvents=new Map(events.filter(e=>e.end>=today).map(e=>[e.id,e]));return lots.map(lot=>{const held=reservations.filter(r=>r.lot_id===lot.id&&!r.released_at&&liveEvents.has(r.event_id));const reserved=Math.round(held.reduce((n,r)=>n+Number(r.quantity),0)*1000)/1000;const known=typeof lot.quantity==='number'&&Number.isFinite(lot.quantity);const state=!date(lot.expires)?'UNKNOWN':lot.expires<today?'EXPIRED':'READY';return {...lot,reserved,held,available:known?Math.round((lot.quantity-reserved)*1000)/1000:null,planState:state};}).sort((a,b)=>({READY:0,UNKNOWN:1,EXPIRED:2}[a.planState]-{READY:0,UNKNOWN:1,EXPIRED:2}[b.planState])||(a.expires||'9999').localeCompare(b.expires||'9999')||a.name.localeCompare(b.name,'ko'));}
 return Object.freeze({UUID,date,keys,text,frequencies,recurrence,dates,defaults,csConfig,deadline,validCommand,stockPlan});
});
