'use strict';
(()=>{const $=id=>document.getElementById(id),fields=['name','lot','manufactured','expires','storage','unit','quantity','note'];let rows=[],editing=null,busy=false,generation=0;
const node=(tag,text,cls)=>{const el=document.createElement(tag);el.textContent=text;if(cls)el.className=cls;return el;};
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(new Date());
function state(row){if(!row.expires)return {key:'unknown',label:'기한 미입력'};const days=Math.round((Date.parse(row.expires)-Date.parse(today()))/86400000);return days<0?{key:'expired',label:'기한 경과'}:days<=30?{key:'soon',label:days===0?'오늘까지':days+'일 남음'}:{key:'normal',label:'기한 여유'};}
function render(){const query=$('stock-search').value.trim().toLowerCase(),filter=$('stock-filter').value;const visible=rows.filter(r=>(r.name+' '+r.lot+' '+r.storage).toLowerCase().includes(query)&&(filter==='all'||state(r).key===filter));$('stock-count').textContent=visible.length+'건 · 전체 '+rows.length+'건';$('stock-list').replaceChildren();
for(const row of visible){const item=node('button','', 'stock-row');item.type='button';const product=node('div','');product.append(node('strong',row.name),node('small',row.lot?'제조번호 '+row.lot:'제조번호 미입력'));const amount=node('strong',row.quantity.toLocaleString('ko-KR')+' '+row.unit);const dates=node('div','');dates.append(node('span','제조 '+(row.manufactured||'미입력')),node('span','유통기한 '+(row.expires||'미입력')));const info=state(row),badge=node('span',info.label,'stock-badge '+info.key);item.append(product,amount,dates,node('span',row.storage||'보관방법 미입력'),badge);item.onclick=()=>open(row);$('stock-list').append(item);}
$('stock-empty').hidden=visible.length>0;}
function open(row){editing=row||{id:crypto.randomUUID(),revision:0};for(const field of fields)$('stock-'+field).value=row?.[field]??(field==='unit'?'개':field==='quantity'?'0':'');$('stock-form-title').textContent=row?'재고 수정':'재고 등록';$('stock-form-status').textContent='';$('stock-dialog').showModal();$('stock-name').focus();}
async function refresh(){if(displayMode!=='live'){$('stock-new').disabled=true;$('stock-status').textContent='사업장에 연결하면 재고 DB를 사용할 수 있습니다.';return;}$('stock-new').disabled=false;if(busy)return;const expected=generation;busy=true;$('stock-status').textContent='재고 기록을 불러오는 중…';try{const result=await window.moaonHub.readStock();if(expected!==generation)return;if(result.status!=='READY')throw Error(result.message);rows=result.value;render();$('stock-status').textContent='사업장 DB에 저장된 재고 · 다른 PC에서도 같은 기록을 사용합니다.';}catch(e){$('stock-status').textContent='조회 실패 · '+e.message;}finally{busy=false;}}
$('stock-form').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;const input=Object.fromEntries(fields.map(k=>[k,$('stock-'+k).value]));input.quantity=Number(input.quantity);input.id=editing.id;input.revision=editing.revision;const expected=generation;busy=true;$('stock-save').disabled=true;$('stock-cancel').disabled=true;try{const result=await window.moaonHub.saveStock(input);if(expected!==generation)return;if(result.status!=='READY')throw Error(result.message);$('stock-dialog').close();busy=false;await refresh();$('stock-status').textContent='저장되었습니다 · '+input.name;}catch(e){$('stock-form-status').textContent=e.message;}finally{busy=false;$('stock-save').disabled=false;$('stock-cancel').disabled=false;}});
$('stock-new').onclick=()=>open();$('stock-cancel').onclick=()=>{if(!busy)$('stock-dialog').close();};$('stock-dialog').addEventListener('cancel',e=>{if(busy)e.preventDefault();});$('stock-refresh').onclick=refresh;$('stock-search').oninput=render;$('stock-filter').onchange=render;window.moaonStock={ensure:refresh,clear:()=>{generation++;rows=[];editing=null;$('stock-dialog').close();$('stock-new').disabled=true;render();}};})();
