'use strict';
(()=>{
 const $=s=>document.querySelector(s),el=(tag,css,text)=>makeElement(tag,css,text);
 let snapshot=null,timer=null,busy=false,generation=0,active=false,filter='MINE',selected=null,creating=false,requestId=null,syncError='',notice='';
 const board=el('section','team-board'),rail=el('section','team-rail');board.id='team-board';rail.id='team-today';$('#month-page').querySelector('header').after(board);$('.daybook-aside').prepend(rail);
 const dialog=el('dialog','team-dialog');dialog.setAttribute('aria-label','업무 등록 및 처리');document.body.append(dialog);
 const profile=el('dialog','team-dialog');profile.setAttribute('aria-label','내 프로필 설정');document.body.append(profile);
 const settings=el('section','team-profile-settings');const settingsButton=el('button','','내 프로필 설정');settingsButton.type='button';settingsButton.onclick=()=>openProfile();settings.append(el('h2','','내 프로필'),el('p','','표시 이름과 알림을 설정합니다. 모두 같은 권한으로 사용합니다.'),settingsButton);$('[data-page="settings"]').querySelector('header').after(settings);
 const name=id=>snapshot?.members.find(m=>m.id===id)?.name||'확인 필요';
 const date=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(new Date());
 const button=(text,action,css='')=>{const b=el('button',css,text);b.type='button';b.onclick=action;b.disabled=busy||!snapshot;return b;};
 function header(title,onClose){const h=el('header','team-heading');h.append(el('h2','',title),button('닫기',onClose));return h;}
 function status(text){let p=dialog.querySelector('[role=status]');if(!p){p=el('p','team-message');p.setAttribute('role','status');dialog.append(p);}p.textContent=text;}
 const message=code=>({TEAM_CONFLICT:'다른 사람이 먼저 수정했습니다. 최신 내용을 확인하고 다시 처리하세요.',TEAM_ASSIGNEE_INVALID:'담당자를 다시 선택해 주세요.',TEAM_AUTH_REQUIRED:'로그인이 만료되었습니다. 다시 로그인해 주세요.',TEAM_RESULT_UNKNOWN:'저장 결과를 확인하지 못했습니다. 새로 조회해 반영 여부를 확인하세요.',TEAM_BUSY:'처리 중입니다. 잠시 후 다시 시도하세요.'})[code]||'연결을 확인하지 못했습니다. 잠시 후 다시 조회해 주세요.';
 async function refresh(){if(!active||busy)return;const expected=generation;busy=true;try{const r=await window.moaonHub.teamCommand({action:'READ'});if(expected!==generation)return;if(r.ok){snapshot=r.value;syncError='';render();if(dialog.open&&selected&&!creating)detail();}else{if(r.code==='TEAM_AUTH_REQUIRED'){stop();return;}syncError=message(r.code);}}catch{syncError='업무 연결 확인 필요';}finally{if(expected===generation){busy=false;render();if(dialog.open&&selected&&!creating)detail();}}}
 async function mutate(input){if(busy)return;const expected=generation;busy=true;render();try{const r=await window.moaonHub.teamCommand(input);if(expected!==generation)return;if(!r.ok){notice=message(r.code);status(notice);return false;}notice='';return true;}catch{notice=message('TEAM_RESULT_UNKNOWN');status(notice);return false;}finally{if(expected===generation){busy=false;await refresh();}}}
 function avatar(id){const m=snapshot?.members.find(m=>m.id===id);const v=el('span','team-avatar',m?.name.slice(0,1)||'?');v.dataset.color=m?.color||'violet';v.setAttribute('aria-hidden','true');if(m?.avatar){const img=el('img','');img.src=m.avatar;img.alt='';v.replaceChildren(img);}return v;}
 function dueLabel(t){return t.due_date===date()?'오늘':t.due_date?.slice(5).replace('-','월 ')+'일';}
 function taskRow(t,compact=false){
  const row=el('article','team-task'+(t.status==='DONE'?' is-done':'')),top=el('div','team-task-top');
  const check=el('input','team-complete');check.type='checkbox';check.checked=t.status==='DONE';check.disabled=busy;check.setAttribute('aria-label',t.title+' 완료');check.onchange=()=>void mutate({action:check.checked?'COMPLETE':'REOPEN',id:t.id,revision:t.revision});
  top.append(check,button(t.title,()=>openDetail(t.id),'team-task-title'));row.append(top);
  const meta=el('div','team-task-meta'),person=el('span','team-person');person.append(avatar(t.assigned_to),el('span','',name(t.assigned_to)));const due=el('span','team-due',dueLabel(t));if(t.status!=='DONE'&&t.due_date<date()){due.classList.add('is-overdue');due.textContent+=' · 기한 지남';}else if(t.due_date===date())due.classList.add('is-today');meta.append(person,due);if(t.status==='DONE')meta.append(el('span','team-done-badge','완료'));row.append(meta);
  if(t.checklist.length){const done=t.checklist.filter(c=>c.done).length,progress=el('div','team-progress'),bar=el('progress','');bar.max=t.checklist.length;bar.value=done;bar.setAttribute('aria-label','체크리스트 진행률');progress.append(el('span','','체크리스트'),bar,el('strong','',done+' / '+t.checklist.length));row.append(progress);}
  const items=el('div','team-check-items');for(const [i,c]of t.checklist.entries()){if(compact&&i>=3)break;const label=el('label','team-check'),input=el('input','');input.type='checkbox';input.checked=c.done;input.disabled=busy||t.status==='DONE';input.onchange=()=>void mutate({action:'CHECK',id:t.id,revision:t.revision,index:i,done:input.checked});label.append(input,el('span','',c.text));items.append(label);}row.append(items);
  if(compact&&t.checklist.length>3)row.append(button('나머지 '+(t.checklist.length-3)+'개 보기',()=>openDetail(t.id),'team-text-button'));return row;
 }
 function render(){
 decorateCalendar();
 const head=el('header','team-heading');head.append(el('div','',null));head.firstChild.append(el('span','team-eyebrow','함께 하는 업무'),el('h2','','우리의 할 일'));head.append(button('+ 업무 지시',openCreate,'primary-action'));const tabs=el('div','team-tabs');for(const [id,label]of [['MINE','나의 업무'],['ASSIGNED','내가 지시한 업무'],['ALL','전체 업무']]){const b=button(label,()=>{filter=id;render();});b.setAttribute('aria-pressed',String(filter===id));tabs.append(b);}const sync=el('p','team-sync',notice||syncError||(snapshot?'자동 동기화 중'+(snapshot.truncated?' · 1,000건까지 표시':''):'로그인 후 업무를 불러옵니다.'));sync.setAttribute('role','status');const list=el('div','team-list');const rows=(snapshot?.tasks||[]).filter(t=>filter==='ALL'||(filter==='MINE'?t.assigned_to===snapshot.me:t.created_by===snapshot.me));if(rows.length)list.append(...rows.map(t=>taskRow(t)));else list.append(el('p','team-empty',snapshot?'등록된 업무가 없습니다. 업무를 추가해 주세요.':'업무를 조회하고 있습니다.'));board.replaceChildren(head,tabs,sync,list);
 const rh=el('header','team-heading');rh.append(el('h2','','나의 업무'),button('+ 업무',openCreate,'team-add-button'));const mine=(snapshot?.tasks||[]).filter(t=>t.assigned_to===snapshot.me&&t.status==='OPEN');rail.replaceChildren(rh,el('p','team-sync',snapshot?`${name(snapshot.me)} · 미완료 ${mine.length}건`:'로그인 후 연결됩니다.'));rail.append(...mine.slice(0,5).map(t=>taskRow(t,true)));if(!mine.length)rail.append(el('p','team-empty',snapshot?'남은 업무가 없어요. 새 할 일을 등록해 보세요.':'업무 연결 확인 중'));rail.append(button('캘린더에서 모두 보기 →',()=>{filter='MINE';showRoute('calendar');board.scrollIntoView({block:'start'});}));settingsButton.disabled=!snapshot;
 if(snapshot){const m=snapshot.members.find(m=>m.id===snapshot.me);$('#business-settings-open').dataset.profileColor=m?.color||'violet';$('#business-settings-open').replaceChildren(avatar(snapshot.me));$('#business-settings-open').title=(m?.name||'나')+' · 프로필 설정';$('#business-settings-open').setAttribute('aria-label',(m?.name||'나')+' 프로필 설정');}
 }
 function openCreate(){
  if(!snapshot)return;selected=null;creating=true;requestId=crypto.randomUUID();dialog.replaceChildren(header('새 업무',()=>dialog.close()));dialog.append(el('p','team-dialog-intro','누가, 언제까지 할 일인지 정해 주세요.'));
  const form=el('form','team-form');const field=(label,element,css='')=>{const wrap=el('label',css);wrap.append(el('span','',label),element);form.append(wrap);return element;};
  const title=field('업무 제목',el('input',''),'team-field-wide');title.required=true;title.maxLength=160;title.placeholder='예: 오늘 출고 수량 확인';
  const assigned=field('담당자',el('select',''));assigned.setAttribute('aria-label','담당자');for(const m of snapshot.members){const o=el('option','');o.value=m.id;o.append(avatar(m.id),el('span','',m.name+(m.title?' · '+m.title:'')));assigned.append(o);}assigned.value=snapshot.me;
  const due=field('기한',el('input',''));due.type='date';due.required=true;due.value=date();
  const notes=field('업무 내용 · 선택',el('textarea',''),'team-field-wide');notes.maxLength=4000;notes.rows=2;notes.placeholder='함께 알아야 할 내용을 적어 주세요.';
  const section=el('section','team-check-editor team-field-wide'),heading=el('div','team-editor-heading'),count=el('span','team-editor-count','0 / 30');heading.append(el('h3','','체크리스트'),count);const rows=el('div','team-editor-rows');
  const add=el('button','team-add-check','+ 항목 추가');add.type='button';
  function addItem(){if(rows.children.length>=30)return;const row=el('div','team-editor-row'),mark=el('span','team-empty-check'),input=el('input',''),remove=el('button','team-remove-check','×');mark.setAttribute('aria-hidden','true');input.maxLength=200;input.placeholder='확인할 내용을 입력하세요';input.setAttribute('aria-label','체크리스트 항목');remove.type='button';remove.setAttribute('aria-label','체크리스트 항목 삭제');remove.onclick=()=>{row.remove();count.textContent=rows.children.length+' / 30';add.disabled=false;add.focus();};input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();addItem();}};row.append(mark,input,remove);rows.append(row);count.textContent=rows.children.length+' / 30';add.disabled=rows.children.length>=30;input.focus();}
  add.onclick=addItem;section.append(heading,rows,add);form.append(section);
  const actions=el('footer','team-form-actions team-field-wide'),cancel=el('button','team-cancel','취소'),save=el('button','primary-action','업무 등록');cancel.type='button';cancel.onclick=()=>dialog.close();save.type='submit';actions.append(cancel,save);form.append(actions);
  form.onsubmit=async e=>{e.preventDefault();const lines=[...rows.querySelectorAll('input')].map(i=>i.value.trim()).filter(Boolean);save.disabled=true;const ok=await mutate({action:'CREATE',id:requestId,title:title.value.trim(),notes:notes.value.trim(),dueDate:due.value,assignedTo:assigned.value,checklist:lines.map(text=>({text,done:false}))});save.disabled=false;if(ok){creating=false;dialog.close();}};
  dialog.append(form);addItem();if(!dialog.open)dialog.showModal();title.focus();
 }
 function detail(){const t=snapshot?.tasks.find(t=>t.id===selected);if(!t){dialog.close();return;}dialog.replaceChildren(header('업무 상세',()=>dialog.close()),el('p','team-task-meta',`${name(t.created_by)} → ${name(t.assigned_to)}`),taskRow(t),el('p','team-notes',t.notes));if(t.completed_at)dialog.append(el('p','team-sync',`${name(t.completed_by)} 완료 · ${new Date(t.completed_at).toLocaleString('ko-KR',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}`));}
 function openDetail(id){creating=false;selected=id;detail();if(snapshot?.tasks.some(t=>t.id===id)&&!dialog.open)dialog.showModal();}
 function openProfile(){
  if(!snapshot)return;const me=snapshot.members.find(m=>m.id===snapshot.me),expected=generation;let draftAvatar=me.avatar||'',photoBusy=false,photoGeneration=0;profile.replaceChildren(header('내 프로필',()=>profile.close()));
  const form=el('form','team-form');const field=(text,node)=>{const l=el('label','');l.append(el('span','',text),node);form.append(l);return node;};
  const photo=el('section','team-photo-editor team-field-wide'),preview=el('div','team-photo-preview'),photoText=el('div','team-photo-text'),file=el('input','team-photo-file'),pick=el('button','team-photo-pick','사진 선택'),remove=el('button','team-photo-remove','삭제');file.type='file';file.accept='image/jpeg,image/png,image/webp';file.setAttribute('aria-label','프로필 사진 파일');pick.type=remove.type='button';pick.onclick=()=>file.click();
  function previewPhoto(){preview.replaceChildren();if(draftAvatar){const img=el('img','');img.src=draftAvatar;img.alt='프로필 사진 미리보기';preview.append(img);}else preview.append(avatar(me.id));remove.disabled=!draftAvatar;}
  remove.onclick=()=>{photoGeneration++;draftAvatar='';preview.replaceChildren(el('span','',me.name.slice(0,1)));remove.disabled=true;file.value='';};photoText.append(el('strong','','프로필 사진'),el('p','','담당자와 내 업무에 함께 표시돼요.'),pick,remove,file);photo.append(preview,photoText);form.append(photo);previewPhoto();
  const nameInput=field('표시 이름',el('input',''));nameInput.value=me.name;nameInput.maxLength=40;nameInput.required=true;const title=field('직함',el('input',''));title.value=me.title;title.maxLength=30;
  const color=field('프로필 색상',el('select',''));color.setAttribute('aria-label','프로필 색상');for(const [v,label]of [['violet','연보라'],['sage','세이지'],['peach','살구'],['blue','파랑']]){const o=el('option','',label);o.value=v;color.append(o);}color.value=me.color;
  const notify=el('input','');notify.type='checkbox';notify.checked=me.notifications;field('Windows 업무 배정 알림 받기',notify);
  const msg=el('p','team-sync','모두 동등하게 전체 기능을 사용할 수 있습니다.');msg.setAttribute('role','status');const save=el('button','primary-action','프로필 저장');save.type='submit';form.append(msg,save);
  file.onchange=async()=>{const f=file.files[0];if(!f)return;const token=++photoGeneration;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>8*1024*1024){msg.textContent='JPG, PNG, WebP 사진을 8MB 이하로 선택해 주세요.';return;}photoBusy=true;save.disabled=true;try{const bitmap=await createImageBitmap(f,{imageOrientation:'from-image'});try{const canvas=document.createElement('canvas');canvas.width=canvas.height=128;const ctx=canvas.getContext('2d');ctx.fillStyle='#ffffff';ctx.fillRect(0,0,128,128);const edge=Math.min(bitmap.width,bitmap.height);ctx.drawImage(bitmap,(bitmap.width-edge)/2,(bitmap.height-edge)/2,edge,edge,0,0,128,128);if(token!==photoGeneration||expected!==generation)return;draftAvatar=canvas.toDataURL('image/jpeg',.85);previewPhoto();msg.textContent='사진을 확인한 뒤 프로필 저장을 눌러 주세요.';}finally{bitmap.close();}}catch{msg.textContent='사진을 읽을 수 없습니다. 다른 사진을 선택해 주세요.';}finally{photoBusy=false;save.disabled=false;file.value='';}};
  form.onsubmit=async e=>{e.preventDefault();if(busy||photoBusy){msg.textContent='처리가 끝나면 다시 저장해 주세요.';return;}busy=true;save.disabled=true;const r=await window.moaonHub.teamCommand({action:'PROFILE',name:nameInput.value.trim(),title:title.value.trim(),color:color.value,notifications:notify.checked,revision:me.revision,avatar:draftAvatar}).catch(()=>({ok:false}));if(expected!==generation)return;busy=false;save.disabled=false;if(r.ok){profile.close();await refresh();}else msg.textContent=message(r.code);};profile.append(form);profile.showModal();
 }
 function decorateToday(){for(const cell of document.querySelectorAll('[data-agenda-date]')){cell.querySelector('.today-agenda-dot')?.remove();const count=(snapshot?.tasks||[]).filter(t=>t.due_date===cell.dataset.agendaDate&&t.status==='OPEN').length;if(count){const dot=el('i','today-agenda-dot');dot.setAttribute('aria-hidden','true');cell.append(dot);cell.title='업무 '+count+'건';}else cell.removeAttribute('title');}}
 function decorateCalendar(){
 decorateToday();
  for(const cell of document.querySelectorAll('[data-calendar-day]')){cell.querySelector('.team-calendar-items')?.remove();cell.querySelector('.team-day-count')?.remove();const rows=(snapshot?.tasks||[]).filter(t=>t.due_date===cell.dataset.calendarDay);if(rows.length){const items=el('span','team-calendar-items');for(const t of rows.slice(0,2)){const chip=el('span','team-calendar-chip'+(t.status==='DONE'?' is-done':''));chip.title=t.title+' · '+name(t.assigned_to);chip.append(avatar(t.assigned_to),el('span','',t.title));items.append(chip);}if(rows.length>2)items.append(el('small','team-calendar-more','+'+(rows.length-2)+'건'));cell.append(items);}}
  const host=document.getElementById('month-entries');if(!host)return;host.querySelector('.team-date-list')?.remove();const selectedDate=document.querySelector('[data-calendar-day][aria-pressed=true]')?.dataset.calendarDay;const rows=(snapshot?.tasks||[]).filter(t=>t.due_date===selectedDate);if(rows.length){const list=el('section','team-date-list');list.append(el('h3','','이 날짜의 업무 · '+rows.length),...rows.map(t=>taskRow(t,true)));host.append(list);}
 }
 function start(){if(active)return;active=true;void refresh();timer=setInterval(()=>void refresh(),10000);}
 function stop(){active=false;generation++;busy=false;clearInterval(timer);timer=null;snapshot=null;dialog.close();profile.close();render();}
 $('#business-settings-open').onclick=()=>snapshot?openProfile():showRoute('settings');
 window.moaonHub.onTeamOpen?.(id=>{if(snapshot){showRoute('calendar');openDetail(id);}});
 window.moaonTeam={start,stop,refresh,decorateCalendar,decorateToday};render();if(!$('.preview-shell').hidden)start();
})();
