'use strict';
(()=>{
 const $=s=>document.querySelector(s),el=(tag,css,text)=>makeElement(tag,css,text);
 let snapshot=null,timer=null,busy=false,generation=0,active=false,filter='MINE',selected=null,creating=false,requestId=null,syncError='',notice='';
 const board=el('section','team-board'),rail=el('section','team-rail');board.id='team-board';rail.id='team-today';$('#month-page').querySelector('header').after(board);$('.daybook-aside').prepend(rail);
 const dialog=el('dialog','team-dialog');dialog.setAttribute('aria-label','업무 등록 및 처리');document.body.append(dialog);
 const profile=el('dialog','team-dialog');profile.setAttribute('aria-label','내 프로필 설정');document.body.append(profile);
 const settings=el('section','team-profile-settings');const settingsButton=el('button','','내 프로필 설정');settingsButton.type='button';settingsButton.onclick=()=>openProfile();settings.append(el('h2','','내 프로필'),el('p','','표시 이름과 알림을 설정합니다. 모두 같은 권한으로 사용합니다.'),settingsButton);$('[data-page="settings"]').querySelector('header').after(settings);
 const name=id=>snapshot?.members.find(m=>m.id===id)?.name||'확인 필요';
 const date=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(new Date());
 const button=(text,action,css='')=>{const b=el('button',css,text);b.type='button';b.onclick=action;b.disabled=busy||!snapshot;return b;};
 function header(title,onClose){const h=el('header','team-heading');h.append(el('h2','',title),button('닫기',onClose));return h;}
 function status(text){let p=dialog.querySelector('[role=status]');if(!p){p=el('p','team-message');p.setAttribute('role','status');dialog.append(p);}p.textContent=text;}
 const message=code=>({TEAM_CONFLICT:'다른 사람이 먼저 수정했습니다. 최신 내용을 확인하고 다시 처리하세요.',TEAM_ASSIGNEE_INVALID:'담당자를 다시 선택해 주세요.',TEAM_AUTH_REQUIRED:'로그인이 만료되었습니다. 다시 로그인해 주세요.',TEAM_RESULT_UNKNOWN:'저장 결과를 확인하지 못했습니다. 새로 조회해 반영 여부를 확인하세요.',TEAM_BUSY:'처리 중입니다. 잠시 후 다시 시도하세요.'})[code]||'연결을 확인하지 못했습니다. 잠시 후 다시 조회해 주세요.';
 async function refresh(){if(!active||busy)return;const expected=generation;busy=true;try{const r=await window.moaonHub.teamCommand({action:'READ'});if(expected!==generation)return;if(r.ok){snapshot=r.value;syncError='';render();if(dialog.open&&selected&&!creating)detail();}else{if(r.code==='TEAM_AUTH_REQUIRED'){stop();return;}syncError=message(r.code);}}catch{syncError='업무 연결 확인 필요';}finally{if(expected===generation){busy=false;render();if(dialog.open&&selected&&!creating)detail();}}}
 async function mutate(input){if(busy)return;const expected=generation;busy=true;render();try{const r=await window.moaonHub.teamCommand(input);if(expected!==generation)return;if(!r.ok){notice=message(r.code);status(notice);return false;}notice='';return true;}catch{notice=message('TEAM_RESULT_UNKNOWN');status(notice);return false;}finally{if(expected===generation){busy=false;await refresh();}}}
 function taskRow(t,compact=false){const row=el('article','team-task'+(t.status==='DONE'?' is-done':'')),top=el('div','team-task-top');const check=el('input','');check.type='checkbox';check.checked=t.status==='DONE';check.disabled=busy;check.setAttribute('aria-label',t.title+' 완료');check.onchange=()=>void mutate({action:check.checked?'COMPLETE':'REOPEN',id:t.id,revision:t.revision});const title=button(t.title,()=>openDetail(t.id),'team-task-title');top.append(check,title);row.append(top);const meta=el('p','team-task-meta',`${t.due_date} · ${name(t.assigned_to)} · ${t.status==='DONE'?'완료':'진행 중'}`);if(t.status!=='DONE'&&t.due_date<date())meta.classList.add('is-overdue');row.append(meta);for(const [i,c]of t.checklist.entries()){if(compact&&i>=3)break;const label=el('label','team-check'),input=el('input','');input.type='checkbox';input.checked=c.done;input.disabled=busy||t.status==='DONE';input.onchange=()=>void mutate({action:'CHECK',id:t.id,revision:t.revision,index:i,done:input.checked});label.append(input,el('span','',c.text));row.append(label);}if(compact&&t.checklist.length>3)row.append(el('small','',`체크리스트 ${t.checklist.filter(c=>c.done).length}/${t.checklist.length}`));return row;}
 function render(){
 decorateCalendar();
 const head=el('header','team-heading');head.append(el('div','',null));head.firstChild.append(el('span','team-eyebrow','함께 하는 업무'),el('h2','','업무와 체크리스트'));head.append(button('+ 업무 지시',openCreate,'primary-action'));const tabs=el('div','team-tabs');for(const [id,label]of [['MINE','나의 업무'],['ASSIGNED','내가 지시한 업무'],['ALL','전체 업무']]){const b=button(label,()=>{filter=id;render();});b.setAttribute('aria-pressed',String(filter===id));tabs.append(b);}const sync=el('p','team-sync',notice||syncError||(snapshot?'10초마다 자동 확인 · 완료 업무 최근 90일'+(snapshot.truncated?' · 1,000건까지 표시':''):'로그인 후 업무를 불러옵니다.'));sync.setAttribute('role','status');const list=el('div','team-list');const rows=(snapshot?.tasks||[]).filter(t=>filter==='ALL'||(filter==='MINE'?t.assigned_to===snapshot.me:t.created_by===snapshot.me));if(rows.length)list.append(...rows.map(t=>taskRow(t)));else list.append(el('p','team-empty',snapshot?'등록된 업무가 없습니다. 업무를 추가해 주세요.':'업무를 조회하고 있습니다.'));board.replaceChildren(head,tabs,sync,list);
 const rh=el('header','team-heading');rh.append(el('h2','','나의 업무'),button('+',openCreate));const mine=(snapshot?.tasks||[]).filter(t=>t.assigned_to===snapshot.me&&t.status==='OPEN');rail.replaceChildren(rh,el('p','team-sync',snapshot?`${name(snapshot.me)} · 미완료 ${mine.length}건`:'로그인 후 연결됩니다.'));rail.append(...mine.slice(0,5).map(t=>taskRow(t,true)));if(!mine.length)rail.append(el('p','team-empty',snapshot?'현재 미완료 업무가 없습니다.':'업무 연결 확인 중'));rail.append(button('캘린더에서 모두 보기 →',()=>{filter='MINE';showRoute('calendar');board.scrollIntoView({block:'start'});}));settingsButton.disabled=!snapshot;
 if(snapshot){const m=snapshot.members.find(m=>m.id===snapshot.me);$('#business-settings-open').dataset.profileColor=m?.color||'violet';$('#business-settings-open').textContent=m?.name.slice(0,1)||'나';$('#business-settings-open').title=(m?.name||'나')+' · 프로필 설정';$('#business-settings-open').setAttribute('aria-label',(m?.name||'나')+' 프로필 설정');}
 }
 function openCreate(){if(!snapshot)return;selected=null;creating=true;requestId=crypto.randomUUID();dialog.replaceChildren(header('업무 지시',()=>dialog.close()));const form=el('form','team-form');const field=(label,element)=>{const wrap=el('label','');wrap.append(el('span','',label),element);form.append(wrap);return element;};const title=field('업무 제목',el('input',''));title.required=true;title.maxLength=160;const assigned=field('담당자',el('select',''));for(const m of snapshot.members){const o=el('option','',m.name+(m.title?' · '+m.title:''));o.value=m.id;assigned.append(o);}assigned.value=snapshot.me;const due=field('기한',el('input',''));due.type='date';due.required=true;due.value=date();const notes=field('업무 내용',el('textarea',''));notes.maxLength=4000;notes.rows=3;const checks=field('체크리스트 · 한 줄에 하나씩',el('textarea',''));checks.rows=4;checks.maxLength=6000;checks.placeholder='포장재 수량 확인\n작수차 출고 준비';const save=el('button','primary-action','업무 등록');save.type='submit';form.append(save);form.onsubmit=async e=>{e.preventDefault();const lines=checks.value.split('\n').map(s=>s.trim()).filter(Boolean);if(lines.length>30||lines.some(s=>s.length>200)){status('체크리스트는 30개까지, 한 항목은 200자까지 입력해 주세요.');return;}save.disabled=true;const ok=await mutate({action:'CREATE',id:requestId,title:title.value.trim(),notes:notes.value.trim(),dueDate:due.value,assignedTo:assigned.value,checklist:lines.map(text=>({text,done:false}))});save.disabled=false;if(ok){creating=false;dialog.close();}};dialog.append(form);if(!dialog.open)dialog.showModal();title.focus();}
 function detail(){const t=snapshot?.tasks.find(t=>t.id===selected);if(!t){dialog.close();return;}dialog.replaceChildren(header('업무 상세',()=>dialog.close()),el('p','team-task-meta',`${name(t.created_by)} → ${name(t.assigned_to)}`),taskRow(t),el('p','team-notes',t.notes));if(t.completed_at)dialog.append(el('p','team-sync',`${name(t.completed_by)} 완료 · ${new Date(t.completed_at).toLocaleString('ko-KR',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}`));}
 function openDetail(id){creating=false;selected=id;detail();if(snapshot?.tasks.some(t=>t.id===id)&&!dialog.open)dialog.showModal();}
 function openProfile(){if(!snapshot)return;const me=snapshot.members.find(m=>m.id===snapshot.me);profile.replaceChildren(header('내 프로필',()=>profile.close()));const form=el('form','team-form');const field=(text,node)=>{const l=el('label','');l.append(el('span','',text),node);form.append(l);return node;};const nameInput=field('표시 이름',el('input',''));nameInput.value=me.name;nameInput.maxLength=40;nameInput.required=true;const title=field('직함 · 권한에는 영향이 없습니다',el('input',''));title.value=me.title;title.maxLength=30;const color=field('프로필 색상',el('select',''));for(const [v,label]of [['violet','연보라'],['sage','세이지'],['peach','살구'],['blue','파랑']]){const o=el('option','',label);o.value=v;color.append(o);}color.value=me.color;const notify=el('input','');notify.type='checkbox';notify.checked=me.notifications;field('Windows 업무 배정 알림 받기',notify);const msg=el('p','team-sync','모두 동등하게 전체 기능을 사용할 수 있습니다.');msg.setAttribute('role','status');const save=el('button','primary-action','프로필 저장');save.type='submit';form.append(msg,save);form.onsubmit=async e=>{e.preventDefault();if(busy)return;save.disabled=true;const r=await window.moaonHub.teamCommand({action:'PROFILE',name:nameInput.value.trim(),title:title.value.trim(),color:color.value,notifications:notify.checked,revision:me.revision}).catch(()=>({ok:false}));save.disabled=false;if(r.ok){profile.close();await refresh();}else msg.textContent=message(r.code);};profile.append(form);profile.showModal();}
 function decorateCalendar(){for(const cell of document.querySelectorAll('[data-calendar-day]')){cell.querySelector('.team-day-count')?.remove();const count=(snapshot?.tasks||[]).filter(t=>t.due_date===cell.dataset.calendarDay&&t.status==='OPEN').length;if(count)cell.append(el('small','team-day-count',`업무 ${count}건`));}const host=document.getElementById('month-entries');if(!host)return;host.querySelector('.team-date-list')?.remove();const selected=document.querySelector('[data-calendar-day][aria-pressed=true]')?.dataset.calendarDay;const rows=(snapshot?.tasks||[]).filter(t=>t.due_date===selected);if(rows.length){const list=el('section','team-date-list');list.append(el('h3','','이 날짜의 업무'),...rows.map(t=>button(t.title,()=>openDetail(t.id))));host.append(list);}}
 function start(){if(active)return;active=true;void refresh();timer=setInterval(()=>void refresh(),10000);}
 function stop(){active=false;generation++;busy=false;clearInterval(timer);timer=null;snapshot=null;dialog.close();profile.close();render();}
 $('#business-settings-open').onclick=()=>snapshot?openProfile():showRoute('settings');
 window.moaonHub.onTeamOpen?.(id=>{if(snapshot){showRoute('calendar');openDetail(id);}});
 window.moaonTeam={start,stop,refresh,decorateCalendar};render();if(!$('.preview-shell').hidden)start();
})();
