'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { HarinBadge, HarinButton, HarinCard, HarinEmptyState, HarinPictogram, HarinProgressiveDetails, HarinSectionHeading, HarinStateCard } from '../../../_design-system/harin-ui.js';

const statusMeta={VERIFIED:['확인 완료','success'],REVIEW_REQUIRED:['검토 필요','warning'],DRAFT:['초안','neutral'],BLOCKED:['사용 중지','danger']};
const platformMeta={NAVER:{label:'네이버',icon:'naver',tone:'mint'},CAFE24:{label:'Cafe24',icon:'store',tone:'blue'},COUPANG:{label:'쿠팡',icon:'coupang',tone:'pink'}};
const severityNames={LOW:'낮음',WATCH:'살펴보기',HIGH:'중요',BLOCKED:'사용 중지'};
const stageNames={AD:'광고',PRODUCT:'상품',CART:'장바구니',ORDER:'주문'};
const areaNames={HERO:'첫 화면',TRUST:'신뢰 근거',BENEFIT:'핵심 장점',USAGE:'먹는 방법',OFFER:'옵션·구성',SHIPPING:'배송',FAQ:'자주 묻는 질문',CTA:'구매 버튼',OTHER:'기타'};
const blankFeedback={area:'HERO',title:'',current_issue:'',recommended_change:'',success_metric:'',source_barrier_ids:[],evidence_ids:[],owner_confirmed:false};
const count=value=>value==null?'판단 보류':`${Math.round(Number(value)).toLocaleString('ko-KR')}회`;
const money=value=>value==null?'확인 필요':`${Math.round(Number(value)).toLocaleString('ko-KR')}원`;
const percent=value=>value==null?'판단 보류':`${Number(value).toLocaleString('ko-KR',{maximumFractionDigits:2})}%`;

function draftFor(type,stored){return stored?{...stored,evidence_ids:stored.evidence_ids||[]}:{barrier_type:type.id,funnel_stage:type.stage,severity:'WATCH',title:type.label,observation:'',recommendation:'',evidence_ids:[],owner_confirmed:false};}

export default function ConversionWorkbench({projectId,productName}){
  const endpoint=`/api/market-intelligence/projects/${projectId}/conversion`;
  const [data,setData]=useState(null),[loading,setLoading]=useState(true),[working,setWorking]=useState(''),[message,setMessage]=useState(''),[activePlatform,setActivePlatform]=useState('NAVER'),[selectedType,setSelectedType]=useState('TARGETING'),[barrierDraft,setBarrierDraft]=useState(null),[feedbackDraft,setFeedbackDraft]=useState(blankFeedback);
  async function load(){setLoading(true);try{const response=await fetch(endpoint,{cache:'no-store'}),result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'구매 전환 자료 조회 실패');setData(result);const available=result.funnels.find(item=>item.status!=='BLOCKED');if(available)setActivePlatform(available.platform);const type=result.barrier_types[0],stored=result.barriers.find(item=>item.barrier_type===type.id);setSelectedType(type.id);setBarrierDraft(draftFor(type,stored));}catch(error){setMessage(`확인 필요 · ${error.message}`);}finally{setLoading(false);}}
  useEffect(()=>{load();},[projectId]);
  async function run(action,payload){setWorking(action);setMessage('');try{const response=await fetch(endpoint,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({action,...payload})}),result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'구매 전환 작업 실패');setData(result);if(action==='SAVE_BARRIER'){const type=result.barrier_types.find(item=>item.id===selectedType),stored=result.barriers.find(item=>item.barrier_type===selectedType);setBarrierDraft(draftFor(type,stored));}if(action==='SAVE_FEEDBACK')setFeedbackDraft(blankFeedback);setMessage(result.message);}catch(error){setMessage(`판단 보류 · ${error.message}`);}finally{setWorking('');}}
  const barrierMap=useMemo(()=>new Map((data?.barriers||[]).map(item=>[item.barrier_type,item])),[data?.barriers]);
  const activeFunnel=data?.funnels?.find(item=>item.platform===activePlatform);
  const selectBarrier=type=>{setSelectedType(type.id);setBarrierDraft(draftFor(type,barrierMap.get(type.id)));};
  const toggle=(draft,setDraft,field,id,checked)=>setDraft(current=>({...current,[field]:checked?[...new Set([...(current[field]||[]),id])]:(current[field]||[]).filter(item=>item!==id)}));
  if(loading)return <HarinCard className="marketConversionLoading"><HarinPictogram icon="target" tone="mint"/><span><b>{productName} 전환 흐름을 연결하는 중이에요…</b><small>상품 매칭과 기간이 같은 자료만 계산합니다.</small></span></HarinCard>;
  if(!data)return <HarinEmptyState icon="target" title="구매 전환 자료를 불러오지 못했어요" description={message||'잠시 뒤 다시 시도해주세요.'}/>;
  const summary=data.summary;
  return <section className="marketConversionWorkbench">
    <HarinSectionHeading eyebrow="AD → PRODUCT → ORDER" title="광고에서 주문까지" description="네이버·Cafe24·쿠팡을 섞지 않고 선택 상품에 연결된 자료만 봐요." icon="target" aside={<HarinBadge tone={summary.readiness==='READY'?'success':'warning'}>{summary.readiness==='READY'?'분석 준비':'판단 보류'}</HarinBadge>}/>
    <section className="marketConversionKpis"><HarinStateCard icon="link" label="전체 단계 연결" value={`${summary.channels_ready}/${summary.channels_total}`} description="같은 상품·기간 기준"/><HarinStateCard icon="warning" label="확인한 장벽" value={`${summary.barriers_verified}/${summary.barriers_total}`} description="검증 Evidence와 사장님 확인"/><HarinStateCard icon="document" label="상세 수정안" value={`${summary.feedback_verified}개`} description="장벽과 성공 지표 연결"/><HarinStateCard tone={summary.readiness==='READY'?'success':'warning'} icon="shield" label="현재 판단" value={summary.readiness==='READY'?'확인 가능':'판단 보류'} description={summary.readiness_message}/></section>
    {message?<div className="marketDataMessage" role="status"><HarinPictogram icon="sparkles" tone="mint" size={18}/><span>{message}</span></div>:null}
    <HarinCard className="marketFunnelBoard"><HarinSectionHeading eyebrow="CHANNEL-SAFE FUNNEL" title="채널별 전환 흐름" description="클릭은 상품 방문의 대리 지표이며, 없는 단계는 0으로 채우지 않아요." icon="growth" aside={<HarinBadge>{activeFunnel?.period_start?`${activeFunnel.period_start} ~ ${activeFunnel.period_end}`:'기간 확인 필요'}</HarinBadge>}/><div className="marketFunnelTabs" role="tablist" aria-label="전환 채널">{data.funnels.map(item=>{const meta=platformMeta[item.platform];return <button className={activePlatform===item.platform?'active':''} role="tab" aria-selected={activePlatform===item.platform} onClick={()=>setActivePlatform(item.platform)} key={item.platform}><HarinPictogram icon={meta.icon} tone={meta.tone} size={18}/><span><b>{meta.label}</b><small>{item.status==='READY'?'전체 연결':item.status==='PARTIAL'?'일부 연결':'연결 필요'}</small></span><HarinBadge tone={item.status==='READY'?'success':item.status==='PARTIAL'?'warning':'neutral'}>{item.status==='READY'?'확인 가능':item.status==='PARTIAL'?'일부 자료':'판단 보류'}</HarinBadge></button>;})}</div>{activeFunnel?<div className={`marketFunnelFlow ${activeFunnel.status.toLowerCase()}`}>{activeFunnel.stages.map((stage,index)=><div className="marketFunnelStepWrap" key={stage.key}><article className={stage.status==='AVAILABLE'?'available':'missing'}><HarinPictogram icon={stage.key==='IMPRESSIONS'?'keyword':stage.key==='VISITS'?'product':'orders'} tone={stage.status==='AVAILABLE'?'lavender':'blue'} size={20}/><span><small>{index+1}. {stage.label}</small><b>{count(stage.value)}</b><em>{stage.status==='AVAILABLE'?(stage.kind==='PROXY'?'대리 지표':'직접 집계'):'수집 안 됨'}</em></span></article>{index<activeFunnel.stages.length-1?<i aria-hidden="true">→</i>:null}</div>)}</div>:null}{activeFunnel?<footer className="marketFunnelSummary"><span><small>노출 → 방문</small><b>{percent(activeFunnel.rates.click_through)}</b></span><span><small>방문 → 주문</small><b>{percent(activeFunnel.rates.visit_to_order)}</b></span><span><small>광고비</small><b>{money(activeFunnel.spend)}</b></span><span><small>기여 매출</small><b>{money(activeFunnel.revenue)}</b></span><p><HarinPictogram icon="shield" tone="blue" size={16}/>{activeFunnel.reason}</p></footer>:null}<div className="marketFunnelActions"><HarinButton as={Link} href="/products" variant="secondary" icon="product">상품 매칭 확인</HarinButton><HarinButton as={Link} href="/keywords?platform=naver" variant="secondary" icon="keyword">광고 연결 확인</HarinButton></div></HarinCard>
    <HarinCard className="marketBarrierBoard"><HarinSectionHeading eyebrow="10 PURCHASE BARRIERS" title="구매 장벽 10개" description="자료가 부족한 장벽은 미확인으로 남기고, 확인한 장벽만 다음 수정안에 사용해요." icon="warning" aside={<HarinBadge tone={summary.barriers_verified?'success':'warning'}>{summary.barriers_verified?`${summary.barriers_verified}개 확인`:'확인 전'}</HarinBadge>}/><div className="marketBarrierGrid">{data.barrier_types.map((type,index)=>{const saved=barrierMap.get(type.id),meta=saved?(statusMeta[saved.status]||statusMeta.DRAFT):['미확인','neutral'];return <button className={selectedType===type.id?'active':''} onClick={()=>selectBarrier(type)} key={type.id}><i>{String(index+1).padStart(2,'0')}</i><HarinPictogram icon={type.stage==='AD'?'keyword':type.stage==='PRODUCT'?'product':type.stage==='CART'?'shoppingBag':'orders'} tone={selectedType===type.id?'lavender':'blue'} size={18}/><span><small>{stageNames[type.stage]}</small><b>{type.label}</b><em>{type.description}</em></span><HarinBadge tone={meta[1]}>{meta[0]}</HarinBadge></button>;})}</div></HarinCard>
    <HarinProgressiveDetails eyebrow="선택 장벽 검수" title={`${data.barrier_types.find(item=>item.id===selectedType)?.label||'구매 장벽'} 기록`} description="관찰 → 영향 → 다음 행동을 Evidence와 함께 저장해요." count={barrierMap.get(selectedType)?'저장됨':'아직 미확인'} defaultOpen><BarrierForm draft={barrierDraft} setDraft={setBarrierDraft} evidence={data.evidence} working={working} onEvidence={(id,checked)=>toggle(barrierDraft,setBarrierDraft,'evidence_ids',id,checked)} onSubmit={()=>run('SAVE_BARRIER',{barrier:barrierDraft})}/></HarinProgressiveDetails>
    <section className="marketFeedbackColumns"><HarinCard><HarinSectionHeading eyebrow="DETAIL PAGE FEEDBACK" title="상세페이지 수정안" description="확인된 장벽을 고객이 보는 화면의 구체적인 수정으로 바꿔요." icon="document" aside={<HarinBadge>{data.feedback.length}개</HarinBadge>}/>{data.feedback.length?<div className="marketFeedbackList">{data.feedback.map(item=>{const meta=statusMeta[item.status]||statusMeta.DRAFT;return <article key={item.id}><HarinPictogram icon={item.area==='SHIPPING'?'truck':item.area==='OFFER'?'price':'document'} tone="lavender" size={18}/><span><small>{areaNames[item.area]}</small><b>{item.title}</b><p>{item.recommended_change||'수정 내용을 더 확인해주세요.'}</p><em>{item.success_metric||'성공 지표 확인 필요'}</em></span><HarinBadge tone={meta[1]}>{meta[0]}</HarinBadge></article>;})}</div>:<HarinEmptyState icon="document" title="저장된 상세페이지 수정안이 없어요" description="구매 장벽을 확인한 뒤 수정 위치와 성공 지표를 연결해주세요."/>}</HarinCard><HarinCard className="marketConversionGuard"><HarinSectionHeading eyebrow="SAFE DECISION" title="계산·쓰기 안전 규칙" description="분석 화면은 운영 API를 직접 변경하지 않아요." icon="shield"/><div><article><HarinPictogram icon="clock" tone="blue"/><span><b>기간 일치</b><p>같은 조회기간이 아니면 전환율을 계산하지 않습니다.</p></span></article><article><HarinPictogram icon="database" tone="mint"/><span><b>상품 격리</b><p>현재 프로젝트의 상품 매칭과 Evidence만 사용합니다.</p></span></article><article><HarinPictogram icon="approvals" tone="lavender"/><span><b>승인 우선</b><p>입찰·상품·상세페이지 변경은 기존 승인 화면에서만 실행합니다.</p></span></article></div></HarinCard></section>
    <HarinProgressiveDetails eyebrow="상세페이지 수정안 추가" title="장벽을 실제 화면 수정으로 연결" description="수정 위치, 바꿀 내용, 성공 확인 지표를 함께 적어요." count={summary.barriers_verified?`확인 장벽 ${summary.barriers_verified}개`:'장벽 확인 먼저 필요'}><FeedbackForm draft={feedbackDraft} setDraft={setFeedbackDraft} barriers={data.barriers.filter(item=>item.status==='VERIFIED')} evidence={data.evidence} working={working} onBarrier={(id,checked)=>toggle(feedbackDraft,setFeedbackDraft,'source_barrier_ids',id,checked)} onEvidence={(id,checked)=>toggle(feedbackDraft,setFeedbackDraft,'evidence_ids',id,checked)} onSubmit={()=>run('SAVE_FEEDBACK',{feedback:feedbackDraft})}/></HarinProgressiveDetails>
  </section>;
}

function EvidenceChoices({evidence,selected,onChange}){return <fieldset className="marketEvidenceChoices"><legend>검증 Evidence</legend><p>현재 상품 프로젝트의 확인 완료 근거만 표시합니다.</p>{evidence.length?<div>{evidence.map(item=><label key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={event=>onChange(item.id,event.target.checked)}/><span><b>{item.label}</b><small>{item.value_text}</small></span></label>)}</div>:<HarinEmptyState icon="database" title="연결할 검증 Evidence가 없어요" description="자료실에서 출처를 확인 완료해주세요."/>}</fieldset>;}
function OwnerCheck({checked,onChange,text}){return <label className="marketOwnerCheck"><input type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)}/><span><b>{text}</b><small>근거가 없으면 확인 완료가 되지 않습니다.</small></span></label>;}
function BarrierForm({draft,setDraft,evidence,working,onEvidence,onSubmit}){if(!draft)return null;const update=(field,value)=>setDraft(current=>({...current,[field]:value}));return <form className="marketProfileForm" onSubmit={event=>{event.preventDefault();onSubmit();}}><div className="marketProfileFields"><label><span>전환 단계</span><select value={draft.funnel_stage} onChange={event=>update('funnel_stage',event.target.value)}>{Object.entries(stageNames).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><label><span>중요도</span><select value={draft.severity} onChange={event=>update('severity',event.target.value)}>{Object.entries(severityNames).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><label className="wide"><span>장벽 이름</span><input maxLength="160" value={draft.title} onChange={event=>update('title',event.target.value)}/></label><label><span>관찰한 내용</span><textarea maxLength="2000" value={draft.observation} onChange={event=>update('observation',event.target.value)} placeholder="예: 광고 클릭은 있지만 옵션 차이를 이해하기 어렵다는 리뷰가 반복됨"/></label><label><span>다음 행동</span><textarea maxLength="2000" value={draft.recommendation} onChange={event=>update('recommendation',event.target.value)} placeholder="예: 첫 화면에 30·90·150티백 차이를 표로 설명"/></label></div><EvidenceChoices evidence={evidence} selected={draft.evidence_ids||[]} onChange={onEvidence}/><OwnerCheck checked={draft.owner_confirmed} onChange={checked=>update('owner_confirmed',checked)} text="관찰 내용과 다음 행동, 연결 근거를 직접 확인했어요"/><HarinButton variant="primary" icon="checklist" type="submit" disabled={Boolean(working)}>{working==='SAVE_BARRIER'?'장벽 저장 중…':'구매 장벽 저장'}</HarinButton></form>;}
function FeedbackForm({draft,setDraft,barriers,evidence,working,onBarrier,onEvidence,onSubmit}){const update=(field,value)=>setDraft(current=>({...current,[field]:value}));return <form className="marketProfileForm" onSubmit={event=>{event.preventDefault();onSubmit();}}><div className="marketProfileFields"><label><span>수정 위치</span><select value={draft.area} onChange={event=>update('area',event.target.value)}>{Object.entries(areaNames).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><label><span>수정안 이름</span><input maxLength="160" value={draft.title} onChange={event=>update('title',event.target.value)}/></label><label><span>현재 문제</span><textarea maxLength="2000" value={draft.current_issue} onChange={event=>update('current_issue',event.target.value)}/></label><label><span>추천 수정</span><textarea maxLength="2000" value={draft.recommended_change} onChange={event=>update('recommended_change',event.target.value)}/></label><label className="wide"><span>성공 확인 지표</span><input maxLength="500" value={draft.success_metric} onChange={event=>update('success_metric',event.target.value)} placeholder="예: 14일 방문→주문 전환율, 옵션 문의 건수"/></label></div><fieldset className="marketReviewChoices"><legend>연결할 구매 장벽</legend>{barriers.length?<div>{barriers.map(item=><label key={item.id}><input type="checkbox" checked={draft.source_barrier_ids.includes(item.id)} onChange={event=>onBarrier(item.id,event.target.checked)}/><span><b>{item.title}</b><small>{stageNames[item.funnel_stage]} · {severityNames[item.severity]}</small></span></label>)}</div>:<HarinEmptyState icon="warning" title="연결할 구매 장벽이 없어요" description="위에서 구매 장벽을 먼저 저장해주세요."/>}</fieldset><EvidenceChoices evidence={evidence} selected={draft.evidence_ids} onChange={onEvidence}/><OwnerCheck checked={draft.owner_confirmed} onChange={checked=>update('owner_confirmed',checked)} text="수정 위치와 성공 확인 지표를 직접 확인했어요"/><HarinButton variant="primary" icon="document" type="submit" disabled={Boolean(working)}>{working==='SAVE_FEEDBACK'?'수정안 저장 중…':'상세페이지 수정안 저장'}</HarinButton></form>;}
