'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{_electron}=require('playwright');
(async()=>{const app=await _electron.launch({executablePath:require('electron'),args:[path.join(__dirname,'isolated-bootstrap.cjs')],env:{...process.env,MOAON_TEST_RUNTIME_ROOT:process.env.MOAON_TEST_RUNTIME_ROOT||path.resolve(__dirname,'..'),MOAON_TEST_PROFILE:fs.mkdtempSync('D:/GPT/tmp/assistant-menu-'),MOAON_TEST_HIDDEN:'0',MOAON_TEST_DISPLAY:'right'}});try{
const p=await app.firstWindow(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.waitForLoadState('domcontentloaded');await app.evaluate(({ipcMain})=>{const defaults={WORK:['briefing','orders','cs','tasks','knowledge','settings'],SOLO:['tasks','memo','reminders','focus','review','settings'],STUDY:['register','knowledge','pending','correct','quiz','settings']};let menus=Object.entries(defaults).map(([slot,items])=>({slot,items,revision:0}));global.menuTestConflict=false;ipcMain.removeHandler('moaon-hub:assistant-automation');ipcMain.handle('moaon-hub:assistant-automation',(_,v)=>{if(v.action==='MENU_SAVE'){if(global.menuTestConflict)return {ok:false,code:'ASSISTANT_CONFLICT'};const r=menus.find(x=>x.slot===v.slot);r.items=v.items;r.revision++;}return {ok:true,value:{menus}};});});
await p.evaluate(async()=>{await returnToSample();document.querySelector('#entry-screen').hidden=true;const shell=document.querySelector('.preview-shell');shell.hidden=false;shell.inert=false;showRoute('assistant');});await p.locator('[data-assistant-tab=menus]').click();await p.locator('#assistant-menu-status').filter({hasText:'불러왔어요'}).waitFor();
const work=p.locator('[data-menu-slot=WORK]');await work.getByRole('checkbox',{name:'📊 업무 브리핑',exact:true}).uncheck();await work.getByRole('button',{name:'💬 고객 문의 위로',exact:true}).click();assert.deepEqual(await work.locator('[data-menu-preview] > div').allTextContents(),['💬 고객 문의','📦 주문·배송','✅ 업무 관리','📚 제품·운영 지식','⚙️ 알림 설정']);await work.locator('[data-menu-save]').click();await p.locator('#assistant-menu-status').filter({hasText:'업무비서 메뉴를 저장했어요'}).waitFor();
await p.getByRole('button',{name:'서버 설정 새로고침',exact:true}).click();await p.locator('#assistant-menu-status').filter({hasText:'불러왔어요'}).waitFor();assert.equal(await work.getByRole('checkbox',{name:'📊 업무 브리핑',exact:true}).isChecked(),false);assert.equal(await p.locator('[data-menu-slot=SOLO] input:checked').count(),6);
await app.evaluate(()=>global.menuTestConflict=true);await work.getByRole('checkbox',{name:'📊 업무 브리핑',exact:true}).check();await work.locator('[data-menu-save]').click();await p.locator('#assistant-menu-status').filter({hasText:'다른 곳에서'}).waitFor();assert.equal(await work.getByRole('checkbox',{name:'📊 업무 브리핑',exact:true}).isChecked(),true);await app.evaluate(()=>global.menuTestConflict=false);
const study=p.locator('[data-menu-slot=STUDY]');for(const label of ['🔎 지식 찾기','🕓 검토 대기','✏️ 지식 수정','🧪 기억 테스트','⚙️ 학습 현황'])await study.getByRole('checkbox',{name:label,exact:true}).uncheck();assert.equal(await study.getByRole('checkbox',{name:'📥 자료 등록',exact:true}).isDisabled(),true);
for(const width of [700,1060,1660]){await app.evaluate(({BrowserWindow,screen},width)=>{const w=BrowserWindow.getAllWindows()[0],d=screen.getAllDisplays().find(d=>d.workArea.x>=screen.getPrimaryDisplay().workArea.x+screen.getPrimaryDisplay().workArea.width);if(!d)throw Error('RIGHT_DISPLAY_UNAVAILABLE');w.setMinimumSize(600,600);w.setBounds({x:d.workArea.x+10,y:d.workArea.y+20,width,height:1040});w.showInactive();},width);for(const theme of ['light','dark']){await p.evaluate(t=>applyTheme(t),theme);const b=await p.locator('[data-page=assistant]').evaluate(n=>({w:n.clientWidth,s:n.scrollWidth}));assert.ok(b.s<=b.w+1,JSON.stringify({width,b}));await p.screenshot({path:'D:/GPT/tmp/p4190-menu-'+width+'-'+theme+'.png'});}}
assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'PASS',orderedSave:true,slotIsolation:true,conflictPreservesEdit:true,minOne:true,layouts:6}));}finally{await app.close();}})().catch(e=>{console.error(e);process.exitCode=1});

