'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{FIELDS,validInput,command}=require('../connections-transport.cjs');
const ai=['CLOVA','GEMINI','OPENAI'];
test('AI complete save, no reveal or extra activation fields and fixed expiry',async()=>{for(const provider of ai){const v={action:'SAVE',provider,revision:0,fields:Object.fromEntries(FIELDS[provider].map(k=>[k,'SYNTHETIC'])),expiresAt:null};assert.equal(validInput(v),true);assert.equal(validInput({...v,enabled:true}),false);assert.equal(validInput({...v,expiresAt:'2027-01-01'}),false);assert.equal(validInput({action:'REVEAL',provider}),false);let calls=0;assert.equal((await command(async()=>{calls++;},{action:'REVEAL',provider})).code,'KEYS_INVALID');assert.equal(calls,0);assert.deepEqual(await command(async()=>Response.json({ok:true,revision:1,status:'KEY_SAVED_DISABLED',fields:{apiKey:'NEVER'}}),v),{ok:true,revision:1,status:'KEY_SAVED_DISABLED',enabled:false,ready:false,reasonCodes:[],checkedAt:null});}});
test('list projects metadata, preserving original four providers and bounds',async()=>{const cards=Object.entries(FIELDS).map(([provider,fields])=>({provider,fields,name:provider,revision:0,editable:true,identity:[],fieldsSecret:'NEVER',collection:{jobs:[]}}));const r=await command(async()=>Response.json({ok:true,cards:cards.slice(0,4),aiCards:cards.slice(4),secret:'NEVER'}),{action:'LIST'});assert.equal(r.cards.length,4);assert.equal(r.aiCards.length,3);assert.doesNotMatch(JSON.stringify(r),/NEVER|fieldsSecret/);assert.equal((await command(async()=>Response.json({ok:true,cards:[...cards,cards[0]]}),{action:'LIST'})).code,'KEYS_UNAVAILABLE');});
test('AI check projects configuration readiness without connected claim; unknown save is retained',async()=>{for(const provider of ai)for(const status of ['READY','DISABLED','KEY_SAVED_DISABLED','SETUP_REQUIRED'])assert.equal((await command(async()=>Response.json({ok:true,status,apiKey:'NEVER'}),{action:'CHECK',provider})).status,status);assert.equal((await command(async()=>Response.json({ok:true,status:'CONNECTED'}),{action:'CHECK',provider:'OPENAI'})).code,'KEYS_UNAVAILABLE');const v={action:'SAVE',provider:'OPENAI',revision:0,fields:{apiKey:'SYNTHETIC'},expiresAt:null};assert.equal((await command(async()=>{throw Error();},v)).code,'KEYS_RESULT_UNKNOWN');});
const legacy=['COUPANG','NAVER','CAFE24','EPOST'];
test('legacy server remains readable without AI metadata',async()=>{const cards=legacy.map(provider=>({provider,name:provider,revision:0,fields:FIELDS[provider],identity:[],editable:true}));const r=await command(async()=>Response.json({ok:true,cards}),{action:'LIST'});assert.equal(r.ok,true);assert.equal(r.cards.length,4);assert.equal(r.aiCards,undefined);});
test('all original providers retain reveal, save and check projection',async()=>{for(const provider of legacy){const fields=Object.fromEntries(FIELDS[provider].map(k=>[k,'SYNTHETIC']));const reveal=await command(async()=>Response.json({ok:true,provider,revision:1,fields,unexpected:'NEVER'}),{action:'REVEAL',provider});assert.deepEqual(reveal.fields,fields);assert.doesNotMatch(JSON.stringify(reveal),/NEVER/);assert.equal((await command(async()=>Response.json({ok:true,revision:2}),{action:'SAVE',provider,revision:1,fields,expiresAt:null})).status,'SAVED_UNVERIFIED');assert.equal((await command(async()=>Response.json({ok:true,status:'QUEUED'}),{action:'CHECK',provider})).status,'QUEUED');}});

test('AI readiness reasons are bounded and secret-free in SAVE/CHECK',async()=>{const r=await command(async()=>Response.json({ok:true,status:'READY',enabled:true,ready:true,reasonCodes:['EMERGENCY_STOP','SECRET'],apiKey:'NEVER'}),{action:'CHECK',provider:'CLOVA'});assert.deepEqual(r,{ok:true,status:'READY',enabled:true,ready:true,reasonCodes:['EMERGENCY_STOP'],checkedAt:null});});
