'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {randomUUID}=require('node:crypto');
const {validCommand,projectResponse}=require('../insight-ai-contract.cjs');const {createInsightAiTransport,INSIGHT_AI_URL}=require('../insight-ai-transport.cjs');const {isAllowedRemoteRequest}=require('../connection-policy.cjs');
const configuration={provider:'CLOVA',model:'HCX-007',enabled:false,ready:false,status:'DISABLED',pricingVersion:null,creditExpiresAt:null};
const command=()=>({operation:'GENERATE',input:{requestId:randomUUID(),reportIds:['report'],kind:'SUMMARY',question:''}});
function run(){return {id:randomUUID(),status:'SUCCEEDED',dataState:'PARTIAL',scope:'NAVER_AD_REPORT',reportIds:['report'],question:'',parentRunId:null,turn:1,createdAt:'2026-09-14T00:00:00Z',provider:'CLOVA',model:'HCX-007',snapshotHash:'a'.repeat(64),period:{start:'2026-09-01',end:'2026-09-07'},metrics:{revenue:{value:null,unit:'KRW',definition:'광고 전환매출',sourceId:'report',reason:'확인 필요'}},cards:[],answer:'매출 확인 필요',nextChecks:[],exclusions:['전체 주문 매출 아님'],usage:null};}
test('commands reject renderer URL/provider/snapshot/oversized question',()=>{assert.equal(validCommand(command()),true);for(const c of [{...command(),url:'https://evil.test'},{...command(),input:{...command().input,provider:'OPENAI'}},{...command(),input:{...command().input,snapshot:{}}},{operation:'LIST',runId:randomUUID()},{operation:'DELETE',runId:'bad'},{operation:'GENERATE',input:{...command().input,kind:'QUESTION',question:'x'.repeat(501)}}])assert.equal(validCommand(c),false);});
test('main request policy requires exact live URL/method permit',()=>{const context={insightAiPermit:{url:INSIGHT_AI_URL,method:'POST'}};assert.equal(isAllowedRemoteRequest({url:INSIGHT_AI_URL,method:'POST',webContentsId:0},context),true);for(const [url,method,webContentsId] of [[INSIGHT_AI_URL,'GET',0],[INSIGHT_AI_URL,'POST',41],[INSIGHT_AI_URL+'?x=1','POST',0],[INSIGHT_AI_URL+'#x','POST',0],[INSIGHT_AI_URL.replace('/insights/ai','/orders'),'POST',0]])assert.equal(isAllowedRemoteRequest({url,method,webContentsId},context),false);assert.equal(isAllowedRemoteRequest({url:INSIGHT_AI_URL,method:'POST',webContentsId:0},{}),false);});
test('GET never includes body and only projected safe configuration survives',async()=>{const read=createInsightAiTransport({fetch:async(url,init)=>{assert.equal(url,INSIGHT_AI_URL);assert.equal(init.method,'GET');assert.equal(init.body,undefined);assert.equal(init.redirect,'error');return Response.json({ok:true,configuration:{...configuration,apiKey:'secret'},runs:[]});}});const result=await read({operation:'LIST'});assert.deepEqual(result,{ok:true,configuration,runs:[]});});
test('POST fixed request and response whitelist preserve missing value',async()=>{let calls=0;const input=command(),fixture=run();const send=createInsightAiTransport({fetch:async(url,init)=>{calls++;assert.equal(init.method,'POST');assert.deepEqual(JSON.parse(init.body),input.input);return Response.json({ok:true,run:{...fixture,validatedOutput:'private',snapshot:'private',tenantId:'private'}});}});const result=await send(input);assert.equal(calls,1);assert.equal(result.run.metrics.revenue.value,null);assert.equal(result.run.validatedOutput,undefined);assert.equal(result.run.tenantId,undefined);assert.equal(result.run.answer,'매출 확인 필요');});
test('DELETE sends only run ID; invalid requests do not fetch',async()=>{let calls=0;const id=randomUUID();const send=createInsightAiTransport({fetch:async(url,init)=>{calls++;assert.equal(init.method,'DELETE');assert.deepEqual(JSON.parse(init.body),{runId:id});return Response.json({ok:true,deleted:true});}});assert.deepEqual(await send({operation:'DELETE',runId:id}),{ok:true,deleted:true});assert.equal((await send({operation:'LIST',url:'evil'})).status,'INVALID_REQUEST');assert.equal(calls,1);});
test('stream bound, wrong target and malformed responses fail closed',async()=>{for(const response of [new Response('x'.repeat(131073)),Response.json({ok:true,run:{...run(),provider:'OPENAI'}}),new Response('{')]){const send=createInsightAiTransport({fetch:async()=>response});assert.equal((await send(command())).status,'UNAVAILABLE');}assert.throws(()=>projectResponse({ok:true,run:{...run(),cards:[{findingId:'fake',metricRefs:['fake'],evidenceRefs:[]}] }},'GENERATE'));});
test('server safe error surfaced; provider raw prose discarded',async()=>{for(const [payload,want] of [[{ok:false,status:'BUDGET_BLOCKED',message:'private'},'BUDGET_BLOCKED'],[{ok:false,status:'secret error'},'UNAVAILABLE']]){const send=createInsightAiTransport({fetch:async()=>Response.json(payload,{status:429})});assert.deepEqual(await send(command()),{ok:false,status:want});}});
test('timeout and cancellation reject late body without retry',async()=>{let calls=0;const send=createInsightAiTransport({fetch:async()=>{calls++;return new Promise(()=>{});},timeoutMs:10});assert.equal((await send(command())).status,'TIMEOUT');assert.equal(calls,1);const c=new AbortController();const pending=send(command(),{signal:c.signal});c.abort();assert.equal((await pending).status,'CANCELLED');assert.equal(calls,2);});
test('actual server public projector roundtrips through independent desktop contract',()=>{const {publicInsightRun}=require('../../lib/ai/insight-public.js');const v=run();const stored={runId:v.id,status:'SUCCEEDED',scope:v.scope,sourceIds:v.reportIds,question:v.question,turn:1,createdAt:v.createdAt,provider:'CLOVA',model:'HCX-007',snapshotHash:v.snapshotHash,snapshot:{period:v.period,metrics:v.metrics,dataState:'PARTIAL',exclusions:v.exclusions},output:{cards:v.cards,answer:v.answer,nextChecks:v.nextChecks},validatedOutput:{secret:'raw'},requester:'private'};const response=projectResponse({ok:true,run:publicInsightRun(stored)},'GENERATE');assert.equal(response.run.id,v.id);assert.equal(response.run.metrics.revenue.value,null);assert.equal(response.run.answer,'매출 확인 필요');assert.equal(response.run.requester,undefined);assert.equal(response.run.validatedOutput,undefined);});
test('server auth/workspace/privacy codes map to safe desktop states',async()=>{for(const [code,status] of [['AUTH_REQUIRED','LOGIN_REQUIRED'],['PERMISSION_DENIED','FORBIDDEN'],['TENANT_ACCESS_DENIED','FORBIDDEN'],['WORKSPACE_CHANGED','CANCELLED'],['QUESTION_PRIVACY_BLOCKED','QUESTION_PRIVACY_BLOCKED']]){const send=createInsightAiTransport({fetch:async()=>Response.json({ok:false,code},{status:403})});assert.equal((await send(command())).status,status);}});
test('public source observation timestamp is preserved or explicitly unknown',()=>{const sourceAsOf='2026-09-13T11:00:00.000Z';assert.equal(projectResponse({ok:true,run:{...run(),sourceAsOf}},'GENERATE').run.sourceAsOf,sourceAsOf);assert.equal(projectResponse({ok:true,run:run()},'GENERATE').run.sourceAsOf,null);assert.throws(()=>projectResponse({ok:true,run:{...run(),sourceAsOf:'invalid'}},'GENERATE'));});
