'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createResearch,metric,shop}=require('../../lib/dashboard/market-research.js'),{valid,project}=require('../research-contract.cjs'),{sendBid}=require('../keyword-bids.cjs');
const input={action:'RESEARCH',query:'작두콩차',days:30,sort:'sim'};
const options={now:()=>new Date('2026-09-14T03:00:00Z'),ads:{request:async(method,path,q)=>{assert.equal(method,'GET');assert.equal(path,'/keywordstool');assert.equal(q.hintKeywords,input.query);return {data:{keywordList:[{relKeyword:'작두콩차',monthlyPcQcCnt:'< 10',monthlyMobileQcCnt:200,compIdx:'높음'}]}};}},hub:{fetchSearchTrend:async q=>{assert.equal(q.startDate,'2026-08-15');assert.equal(q.endDate,'2026-09-13');return {data:{results:[{data:[{period:'2026-09-12',ratio:0},{period:'2026-09-13',ratio:100}]}]}};}},shopping:async()=>({total:120,items:[{productId:'1',title:'<b>작두콩차</b> &amp; 티백',mallName:'테스트',lprice:'0'},{productId:'2',title:'작두콩',lprice:'15000'}]})};
test('research restricts query and parameters at IPC boundary',()=>{assert.ok(valid(input));for(const v of [{...input,url:'https://evil'},{...input,query:'a,b'},{...input,query:'a\n'},{...input,query:' '.repeat(5)},{...input,days:365},{...input,sort:'sales'}])assert.equal(valid(v),false);});
test('real source projection keeps low volume, missing price and relative index distinct',async()=>{const r=await createResearch(options)(input);assert.equal(r.keywords.rows[0].pc,'LT_10');assert.equal(r.products.rows[0].price,null);assert.equal(r.products.rows[0].title,'작두콩차 & 티백');assert.equal(r.products.rows[1].price,15000);assert.equal(r.trend.points[0].ratio,0);assert.equal(r.trend.points[1].ratio,100);assert.equal(r.products.total,120);});
test('provider failures stay partial, not zero; errors and secrets are not exposed',async()=>{const r=await createResearch({...options,shopping:async()=>{throw Object.assign(Error('secret'),{code:'CONFIG_REQUIRED'});}})(input);assert.equal(r.keywords.status,'READY');assert.equal(r.products.status,'SETUP_REQUIRED');assert.equal(r.products.total,null);assert.equal(JSON.stringify(r).includes('secret'),false);});
test('malformed upstream is unavailable; a valid empty query result stays empty',async()=>{const r=await createResearch({...options,ads:{request:async()=>({data:{wrong:[]}})},shopping:async()=>({total:0,items:[]})})(input);assert.equal(r.keywords.status,'UNAVAILABLE');assert.equal(r.products.status,'EMPTY');assert.equal(r.products.total,0);});
test('unavailable count never coerces to zero',()=>{for(const v of [null,undefined,'',NaN,-1,false,true])assert.equal(metric(v),null);assert.equal(metric(0),0);});
test('retired shopping endpoint never makes a network request even with credentials',async()=>{let called=false;await assert.rejects(shop({...input,env:{},fetchImpl:()=>{called=true;}}),{code:'SERVICE_RETIRED'});assert.equal(called,false);});
test('research transport projects safe fields and rejects mismatched or oversized data',async()=>{const r=await createResearch(options)(input);assert.equal((await sendBid(async()=>Response.json({...r,secret:'never'}),input)).secret,undefined);assert.equal((await sendBid(async()=>Response.json({...r,query:'other'}),input)).ok,false);assert.equal((await sendBid(async()=>new Response('x'.repeat(131073)),input)).ok,false);assert.throws(()=>project({...r,trend:{status:'READY',points:[{date:'2026-09-13',ratio:101}]}},input));});

test('research operation is read-only and rechecks access after results arrive',async()=>{const {createKeywordBidOperations}=require('../../lib/dashboard/keyword-bids.js');let reads=0,checks=0;const operate=createKeywordBidOperations({db:{from(){throw Error('Unexpected database mutation');}},research:async()=>{reads++;return {query:input.query};}});const r=await operate(input,{actor:'test',check:async()=>{checks++;}});assert.equal(r.query,input.query);assert.equal(reads,1);assert.equal(checks,1);await assert.rejects(operate(input,{actor:'test',check:async()=>{throw Error('Workspace changed');}}),/Workspace changed/);});

test('retired shopping is distinguished from temporary API failures',async()=>{const r=await createResearch({...options,shopping:shop})(input);assert.equal(r.products.retired,true);assert.equal(r.products.total,null);assert.deepEqual(r.products.rows,[]);assert.equal(r.keywords.status,'READY');});
