'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{EventEmitter}=require('node:events');
const {verifyManifest,assertMetadata,SignedUpdater,readManifest}=require('../signed-updates.cjs');
const keys=crypto.generateKeyPairSync('ed25519'),publicKey=keys.publicKey.export({type:'spki',format:'pem'}),bytes=Buffer.from('test installer');
const payload={appId:'com.moaon.preview',channel:'stable',version:'0.104.0',file:'Moaon-0.104.0-Setup.exe',size:bytes.length,sha512:crypto.createHash('sha512').update(bytes).digest('base64')};
function envelope(value=payload,key=keys.privateKey){const b=Buffer.from(JSON.stringify(value));return {payload:b.toString('base64'),signature:crypto.sign(null,b,key).toString('base64')};}
const info={version:payload.version,files:[{url:payload.file,size:payload.size,sha512:payload.sha512}]};
test('manifest requires pinned key and signed application, channel, version and installer identity',()=>{assert.equal(verifyManifest(envelope(),publicKey).version,payload.version);assert.throws(()=>verifyManifest({...envelope(),payload:Buffer.from(JSON.stringify({...payload,size:1})).toString('base64')},publicKey));assert.throws(()=>verifyManifest(envelope(payload,crypto.generateKeyPairSync('ed25519').privateKey),publicKey));for(const x of [{appId:'other'},{channel:'beta'},{file:'../installer.exe'},{size:Infinity},{version:'bad'}])assert.throws(()=>verifyManifest(envelope({...payload,...x}),publicKey));});
test('unsigned transport metadata cannot change the signed version, digest, size, filename or add web packages',()=>{assertMetadata(info,payload);for(const x of [{version:'0.999.0'},{files:[{...info.files[0],sha512:'x'}]},{files:[{...info.files[0],url:'https://evil.invalid/a.exe'}]},{files:[...info.files,info.files[0]]},{packages:{x64:{path:'other'}}}])assert.throws(()=>assertMetadata({...info,...x},payload));});
test('downloads including cached files and pre-install contents are independently verified before ready or execution',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'moaon-signed-update-')),file=path.join(dir,payload.file);fs.writeFileSync(file,bytes);const backend=new EventEmitter();backend.installerPath=file;backend.checkForUpdates=async()=>({updateInfo:info});backend.downloadUpdate=async()=>{backend.emit('update-downloaded',info);return [file];};let installs=0;backend.quitAndInstall=()=>installs++;const u=new SignedUpdater({backend,config:{url:'https://example.com',publicKey},fetchManifest:async()=>envelope()});let ready=0;u.on('update-downloaded',()=>ready++);await assert.rejects(u.downloadUpdate());await u.checkForUpdates();fs.writeFileSync(file,'tampered');await assert.rejects(u.downloadUpdate());assert.equal(ready,0);fs.writeFileSync(file,bytes);await u.downloadUpdate();assert.equal(ready,1);fs.writeFileSync(file,'tampered');assert.throws(()=>u.quitAndInstall(true,true));assert.equal(installs,0);fs.writeFileSync(file,bytes);u.quitAndInstall(true,true);assert.equal(installs,1);fs.unlinkSync(file);fs.rmdirSync(dir);});
test('unavailable and oversized manifest responses fail closed',async()=>{await assert.rejects(readManifest('https://example.com',async()=>new Response('',{status:404})));await assert.rejects(readManifest('https://example.com',async()=>new Response('x'.repeat(16001))));});
