'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{EventEmitter}=require('node:events');
const fs=require('node:fs'),path=require('node:path');
const {createTrayLifecycle}=require('../tray-lifecycle.cjs');
const {createBackgroundMonitor}=require('../background-monitor.cjs');
function lifecycle(options={}){
 const app=new EventEmitter(),window=new EventEmitter();let tray,stops=0;
 Object.assign(window,{visible:true,skipped:false,isDestroyed:()=>false,isMinimized:()=>true,restore(){this.restored=true;},show(){this.visible=true;},focus(){},hide(){this.visible=false;},setSkipTaskbar(v){this.skipped=v;},webContents:{send(){}}});
 app.quit=()=>app.emit('before-quit');
 class Tray extends EventEmitter{constructor(){super();tray=this;}setToolTip(v){this.tooltip=v;}setContextMenu(v){this.menu=v;}destroy(){this.destroyed=true;}}
 const api=createTrayLifecycle({app,window,Tray,Menu:{buildFromTemplate:x=>x},icon:'icon',onStop:()=>stops++,...options});
 const close=()=>{let prevented=false;window.emit('close',{preventDefault:()=>prevented=true});return prevented;};
 return {app,window,api,tray,close,stops:()=>stops};
}
test('X hides a surviving window; tray restores taskbar and explicit Quit permits close',()=>{const h=lifecycle();assert.equal(h.close(),true);assert.equal(h.window.visible,false);assert.equal(h.window.skipped,true);h.tray.menu[0].click();assert.equal(h.window.visible,true);assert.equal(h.window.skipped,false);h.api.setStatus('로그인 필요');assert.match(h.tray.tooltip,/로그인 필요/);h.tray.menu[3].click();assert.equal(h.close(),false);assert.equal(h.stops(),1);h.api.dispose();assert.equal(h.tray.destroyed,true);});
test('updater and Windows session shutdown cannot be trapped in the tray',()=>{const update=lifecycle({allowClose:()=>true});assert.equal(update.close(),false);for(const event of ['query-session-end','session-end']){const h=lifecycle();h.window.emit(event);assert.equal(h.close(),false);assert.equal(h.stops(),1);h.api.dispose();}});
test('tray failure preserves normal close and modal child prevents hiding',()=>{const h=lifecycle({Tray:class{constructor(){throw Error('no tray');}}});assert.equal(h.api.available,false);assert.equal(h.close(),false);const modal=lifecycle({canHide:()=>false});assert.equal(modal.close(),true);assert.equal(modal.window.visible,true);modal.api.dispose();});
function monitor(t){
 const directory=fs.mkdtempSync('D:/GPT/tmp/moaon-background-test-');t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));
 let clock=Date.parse('2026-09-13T01:00:00Z'),fail=false,created=[],reads=0;const statuses=[];
 const value={me:'one',members:[{id:'one',notifications:true}],tasks:[]};
 const source={orders:[],cs:[],calendar:[],status:'READY'},window={isDestroyed:()=>false,isMinimized:()=>false,setSkipTaskbar(v){this.skipped=v;},show(){this.visible=true;},focus(){},webContents:{send(c,r){window.route=r;}}};
 class Notification extends EventEmitter{static isSupported(){return true;}constructor(v){super();this.options=v;created.push(this);}show(){this.emit(fail?'failed':'show');}close(){this.emit('close');}}
 const connection={teamCommand:async()=>({ok:true,value}),readBackgroundOrders:async()=>{reads++;return {status:source.status,items:source.orders};},readCs:async()=>({status:'READY',items:source.cs}),readTodayCalendar:async()=>({status:'READY',date:'2026-09-13',entries:source.calendar}),collectBackgroundOrders:async()=>({status:'SUCCESS'}),collectBackgroundCs:async()=>({status:'QUEUED'})};
 const api=createBackgroundMonitor({connection,Notification,getWindow:()=>window,directory,now:()=>clock,onStatus:s=>statuses.push(s)});t.after(()=>api.stop());
 return {api,connection,value,source,created,window,directory,statuses,reads:()=>reads,advance:()=>clock+=61000,stamp:()=>new Date(clock).toISOString(),setFail:v=>fail=v};
}
test('first read is silent, new orders/inquiries batch and clicks reopen correct route; retries do not duplicate',async t=>{const h=monitor(t);h.source.orders=[{id:'old',at:h.stamp()}];await h.api.tick();assert.equal(h.created.length,0);h.advance();h.source.orders.push(...['new1','new2'].map(id=>({id,at:h.stamp()})));h.source.cs=[{id:'cs1',kind:'INQUIRY',occurredAt:h.stamp()}];await h.api.tick();assert.equal(h.created.length,2);assert.match(h.created[0].options.title,/2건/);h.created[1].emit('click');assert.equal(h.window.route,'cs');assert.equal(h.window.skipped,false);h.advance();await h.api.tick();assert.equal(h.created.length,2);assert.equal(fs.readFileSync(path.join(h.directory,fs.readdirSync(h.directory)[0]),'utf8').includes('new1'),false);});
test('failed reads do not establish a baseline and unknown dates do not produce alerts',async t=>{const h=monitor(t);h.source.status='UNAVAILABLE';await h.api.tick();h.source.orders=[{id:'previous',at:h.stamp()}];h.source.status='READY';h.advance();await h.api.tick();assert.equal(h.created.length,0);h.source.orders.push({id:'unknown',at:null});h.advance();await h.api.tick();assert.equal(h.created.length,0);});
test('failed native notification retries; disabled profile consumes without notifications',async t=>{const h=monitor(t);await h.api.tick();h.source.orders=[{id:'new',at:h.stamp()}];h.setFail(true);h.advance();await h.api.tick();assert.equal(h.created.length,1);h.setFail(false);h.advance();await h.api.tick();assert.equal(h.created.length,2);h.value.members[0].notifications=false;h.source.orders.push({id:'muted',at:h.stamp()});h.advance();await h.api.tick();h.value.members[0].notifications=true;h.advance();await h.api.tick();assert.equal(h.created.length,2);});
test('due tasks batch; schedule reminder deduplicates; logout invalidates old notification clicks',async t=>{const h=monitor(t);h.value.tasks=['a','b'].map(id=>({id,assigned_to:'one',status:'OPEN',due_date:'2026-09-13',title:'task'}));h.source.calendar=[{id:'s',type:'SCHEDULE',status:'OPEN',time:'10:05',title:'meeting'}];await h.api.tick();assert.equal(h.created.length,2);h.advance();await h.api.tick();assert.equal(h.created.length,2);h.api.identity(null);h.created[0].emit('click');assert.equal(h.window.visible,undefined);});
test('collection never blocks team polling; poll single flight and stop discard late reads',async t=>{const h=monitor(t);let resolveOrder;h.connection.collectBackgroundOrders=()=>new Promise(r=>resolveOrder=r);await h.api.tick();h.advance();await h.api.tick();assert.equal(h.reads(),2);resolveOrder({status:'SUCCESS'});await new Promise(r=>setImmediate(r));let release;h.connection.readBackgroundOrders=()=>new Promise(r=>release=r);h.advance();const pending=h.api.tick();await new Promise(r=>setImmediate(r));await h.api.tick();h.api.stop();release({status:'READY',items:[{id:'late',at:h.stamp()}]});await pending;assert.equal(h.created.length,0);});

test('CS collection failure stays visible after subsequent successful order collection',async t=>{const h=monitor(t);h.connection.collectBackgroundCs=async()=>({status:'CHECK_REQUIRED'});await h.api.tick();await new Promise(r=>setImmediate(r));h.advance();h.advance();await h.api.tick();await new Promise(r=>setImmediate(r));h.advance();await h.api.tick();assert.match(h.statuses.at(-1),/일부 연결 확인 필요/);});
