'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{EventEmitter}=require('node:events');
const {createWorklistPreview}=require('../worklist-preview.cjs');
const {worklistExpectedRows}=require('../local-worklist.cjs');
const orders=[{hubOrderId:'HR-NV-1234ABCD',platform:'NAVER',externalOrderId:'N1',productName:'차',stage:'PREPARING',amount:null,items:[{name:'차',option:'',quantity:1}],packagingInstructions:[],gifts:[],invoice:null}];
function fixture({fit=true,answer=1,validate=async()=>true,mutateText=false}={}){let menu,prints=0,content=[];const windows=[];class Window extends EventEmitter{constructor(options){super();this.options=options;this.dead=false;windows.push(this);this.webContents=Object.assign(new EventEmitter(),{id:9,session:{webRequest:{onBeforeRequest(){}},setPermissionRequestHandler(){}},getURL:()=>this.url,setWindowOpenHandler(){},executeJavaScriptInIsolatedWorld:async(_world,scripts)=>{const code=scripts[0].code;if(code.startsWith('document.open')){content=Array.from(code.matchAll(/data-content-id=\\?"([a-f0-9]{64})/g),m=>m[1]);return;}return {ids:orders.map(x=>x.hubOrderId),texts:worklistExpectedRows({orders,type:'packing'}).map((value,index)=>mutateText&&index===0?value+'변조':value),checks:orders.length,pages:content.map(value=>({width:790,height:1122,fit,content:value,head:true,foot:true}))};},print:(options,done)=>{assert.equal(options.silent,false);assert.equal(options.pageSize,'A4');prints++;done(true,'');}});}isDestroyed(){return this.dead}destroy(){this.dead=true;this.emit('closed')}show(){}setTitle(value){this.title=value}setMenu(value){menu=value}async loadURL(url){this.url=url}}
 const preview=createWorklistPreview({BrowserWindow:Window,Menu:{buildFromTemplate:items=>({getMenuItemById:id=>items.find(x=>x.id===id)})},dialog:{showMessageBox:async()=>({response:answer})},getParent:()=>({isDestroyed:()=>false})});return {preview,windows,prints:()=>prints,open:()=>preview.open({orders,type:'packing',validate}),print:()=>menu.getMenuItemById('print').click()};}
test('A4 preview is memory-only, hardened, opens without auto print and prints non-silently only after confirmation',async()=>{const f=fixture();assert.equal((await f.open()).status,'PREVIEW_OPEN');assert.equal(f.prints(),0);const options=f.windows[0].options.webPreferences;assert.equal(options.javascript,false);assert.equal(options.sandbox,true);assert.equal(options.contextIsolation,true);assert.equal(f.windows[0].url,'about:blank');await f.print();assert.equal(f.prints(),1);assert.match(f.windows[0].title,/실제 출력 확인 필요/);});
test('overflow or failed fresh validation blocks preview and print',async()=>{const overflow=fixture({fit:false});assert.equal((await overflow.open()).status,'DOCUMENT_UNAVAILABLE');assert.equal(overflow.prints(),0);let calls=0;const stale=fixture({validate:async()=>++calls<2});assert.equal((await stale.open()).status,'PREVIEW_OPEN');await stale.print();assert.equal(stale.prints(),0);assert.match(stale.windows[0].title,/문서 확인 실패/);});
test('cancelled confirmation never prints and close destroys native child',async()=>{const f=fixture({answer:0});await f.open();await f.print();assert.equal(f.prints(),0);f.preview.close();assert.equal(f.windows[0].isDestroyed(),true);});
test('mutated rendered row text fails content verification even with unchanged identity attributes',async()=>{const f=fixture({mutateText:true});assert.equal((await f.open()).status,'DOCUMENT_UNAVAILABLE');assert.equal(f.prints(),0);});
