'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createHubConnection,registerConnectionIpc}=require('../hub-connection.cjs');
const base={hubOrderId:'HR-C24-1234ABCD',platform:'CAFE24',externalOrderId:'TEST',fulfillment:'SELLER',stage:'PREPARING',productName:'차',quantity:1,amount:1000,cancelled:false,cancellationRequested:false,items:Array.from({length:9},(_,i)=>({name:`차${i}`,option:'',quantity:1})),packagingInstructions:['밀봉'],gifts:Array.from({length:9},(_,i)=>({giftName:`컵${i}`,quantity:1}))};
function setup(read=()=>[base],extra={}){const opens=[];const remote={setPermissionCheckHandler(){},setPermissionRequestHandler(){},on(){},webRequest:{onBeforeRequest(){}},async clearStorageData(){},async clearCache(){},async clearAuthCache(){},async fetch(){const orders=await read();return Response.json({ok:true,orders,total:orders.length,offset:0,nextOffset:null,snapshot:'a'.repeat(64),partial:false});}};const connection=createHubConnection({BrowserWindow:class{},session:{fromPartition:()=>remote},getMainWindow:()=>({isDestroyed:()=>false}),worklistPreview:{close(){},context(){return{}},open:async value=>{opens.push(value);return {status:'PREVIEW_OPEN'};}},...extra});return {connection,opens};}
test('previewWorklist accepts exact selected all-channel orders and preserves >8 details',async()=>{const rows=[base,{...base,hubOrderId:'HR-NV-1234ABCD',platform:'NAVER'},{...base,hubOrderId:'HR-CP-1234ABCD',platform:'COUPANG'}];const f=setup(()=>rows);await f.connection.refresh();assert.equal((await f.connection.previewWorklist(rows.map(x=>x.hubOrderId),'packing')).status,'PREVIEW_OPEN');assert.equal(f.opens[0].orders[0].items.length,9);assert.equal(f.opens[0].orders[0].gifts.length,9);assert.deepEqual(f.opens[0].orders.map(x=>x.platform),['CAFE24','NAVER','COUPANG']);});
test('worklist fresh validation keeps active server filter conditions',async()=>{const urls=[];const remote={setPermissionCheckHandler(){},setPermissionRequestHandler(){},on(){},webRequest:{onBeforeRequest(){}},async fetch(url){urls.push(url);return Response.json({ok:true,orders:[base],total:1,offset:0,nextOffset:null,snapshot:'a'.repeat(64),partial:false});}};const connection=createHubConnection({BrowserWindow:class{},session:{fromPartition:()=>remote},getMainWindow:()=>({isDestroyed:()=>false}),worklistPreview:{close(){},context(){return{}},open:async()=>({status:'PREVIEW_OPEN'})}});await connection.setOrderFilters({delayOnly:true,giftOnly:false});assert.equal((await connection.previewWorklist([base.hubOrderId],'packing')).status,'PREVIEW_OPEN');assert.ok(urls.length>=2&&urls.slice(-2).every(url=>url.includes('delayOnly=true&giftOnly=false')));});
test('previewWorklist validates ids/type and detects packaging, gifts, items and amount changes',async()=>{let row=base;const f=setup(()=>[row]);await f.connection.refresh();for(const value of [[[], 'packing'],[[base.hubOrderId,base.hubOrderId],'packing'],[['bad'],'packing'],[Array(21).fill(base.hubOrderId),'packing'],[[base.hubOrderId],'wrong']])await assert.rejects(()=>f.connection.previewWorklist(...value));for(const change of [{packagingInstructions:['변경']},{gifts:[{giftName:'변경',quantity:1}]},{items:[{name:'변경',quantity:1}]},{amount:2000}]){row={...base,...change};assert.equal((await f.connection.previewWorklist([base.hubOrderId],'dispatch')).status,'DOCUMENT_CHANGED');row=base;}});
test('worklist IPC rejects untrusted or malformed calls',async()=>{const handlers=new Map(),mainFrame={url:'moaon://app/index.html'},webContents={mainFrame,getURL:()=>mainFrame.url},mainWindow={isDestroyed:()=>false,webContents};registerConnectionIpc({ipcMain:{handle:(key,fn)=>handlers.set(key,fn)},getMainWindow:()=>mainWindow,connection:{previewWorklist:async()=>({status:'PREVIEW_OPEN'})}});const handler=handlers.get('moaon-hub:preview-worklist'),trusted={sender:webContents,senderFrame:mainFrame};assert.ok(handler);await assert.rejects(()=>handler({sender:{id:2}},[base.hubOrderId],'packing'));await assert.rejects(()=>handler(trusted,[base.hubOrderId],'wrong'));assert.equal((await handler(trusted,[base.hubOrderId],'packing')).status,'PREVIEW_OPEN');});
test('an open worklist validation fails while another selected document operation is active',async()=>{let release;const selectedDocuments={save:()=>new Promise(resolve=>{release=()=>resolve({status:'SAVE_CANCELLED'});})};const f=setup(()=>[base],{selectedDocuments});await f.connection.refresh();assert.equal((await f.connection.previewWorklist([base.hubOrderId],'packing')).status,'PREVIEW_OPEN');const pending=f.connection.exportSelectedCsv([base.hubOrderId]);for(let i=0;i<20&&!release;i++)await new Promise(resolve=>setImmediate(resolve));assert.equal(await f.opens[0].validate(),false);release();await pending;});
