'use strict';

const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('moaonHub', Object.freeze({
  collectOrders: () => ipcRenderer.invoke('moaon-hub:collect-orders'),
  checkOrderCollection: () => ipcRenderer.invoke('moaon-hub:check-order-collection'),
  readTracking: (id) => ipcRenderer.invoke('moaon-hub:read-tracking',id),
  refreshTracking: (id) => ipcRenderer.invoke('moaon-hub:refresh-tracking',id),
  readServerShippingHistory: () => ipcRenderer.invoke('moaon-hub:server-shipping-history'),
  findOrder: (id) => ipcRenderer.invoke('moaon-hub:find-order',id),
  restoreShippingHistory: () => ipcRenderer.invoke('moaon-hub:restore-shipping-history'),
  readDelivery: (id) => ipcRenderer.invoke('moaon-hub:read-delivery',id),
  readOverview: () => ipcRenderer.invoke('moaon-hub:read-overview'),
  listBusinesses: () => ipcRenderer.invoke('moaon-hub:list-businesses'),
  appInfo: () => ipcRenderer.invoke('moaon-hub:app-info'),
  inspectPrinters: () => ipcRenderer.invoke('moaon-hub:inspect-printers'),
  previewLabel: (id) => ipcRenderer.invoke('moaon-hub:preview-label',id),
  issueShipment: (id) => ipcRenderer.invoke('moaon-hub:issue-shipment',id),
  issueAndRegister: (ids) => ipcRenderer.invoke('moaon-hub:issue-and-register',ids),
  checkShipment: (id) => ipcRenderer.invoke('moaon-hub:check-shipment',id),
  confirmShipmentReview: (id) => ipcRenderer.invoke('moaon-hub:confirm-shipment-review',id),
  connect: () => ipcRenderer.invoke('moaon-hub:connect'),
  refresh: () => ipcRenderer.invoke('moaon-hub:refresh'),
  recheckPage: () => ipcRenderer.invoke('moaon-hub:recheck-page'),
  nextPage: () => ipcRenderer.invoke('moaon-hub:next-page'),
  previousPage: () => ipcRenderer.invoke('moaon-hub:previous-page'),
  viewActive: () => ipcRenderer.invoke('moaon-hub:view-active'),
  viewChannel: (channel) => ipcRenderer.invoke('moaon-hub:view-channel',channel),
  registerInvoices: (ids) => ipcRenderer.invoke('moaon-hub:register-invoices',ids),
  viewRegistered: () => ipcRenderer.invoke('moaon-hub:view-registered'),
  viewInTransit: () => ipcRenderer.invoke('moaon-hub:view-in-transit'),
  viewCompleted: () => ipcRenderer.invoke('moaon-hub:view-completed'),
  disconnect: () => ipcRenderer.invoke('moaon-hub:disconnect'),
}));
