'use strict';
const fs=require('node:fs'),crypto=require('node:crypto'),{EventEmitter}=require('node:events');
const APP='com.moaon.preview';
function verifyManifest(envelope,publicKey){
 if(!envelope||typeof envelope.payload!=='string'||envelope.payload.length>12000||typeof envelope.signature!=='string'||envelope.signature.length>200)throw Error('Invalid signed manifest');
 const key=crypto.createPublicKey(publicKey);if(key.asymmetricKeyType!=='ed25519')throw Error('Invalid update key');const bytes=Buffer.from(envelope.payload,'base64');if(!crypto.verify(null,bytes,key,Buffer.from(envelope.signature,'base64')))throw Error('Invalid update signature');
 const p=JSON.parse(bytes.toString('utf8'));if(p.appId!==APP||p.channel!=='stable'||!/^\d{1,4}\.\d{1,4}\.\d{1,4}$/.test(p.version)||p.file!==`Moaon-${p.version}-Setup.exe`||!Number.isSafeInteger(p.size)||p.size<1||p.size>1024*1024*1024||typeof p.sha512!=='string'||Buffer.from(p.sha512,'base64').length!==64)throw Error('Invalid update payload');return Object.freeze(p);
}
function assertMetadata(info,p){const file=info?.files?.[0];if(info?.version!==p.version||info.files?.length!==1||file.url!==p.file||file.size!==p.size||file.sha512!==p.sha512||info.packages||file.packageInfo||info.path&&info.path!==p.file||info.sha512&&info.sha512!==p.sha512)throw Error('Unsigned update metadata mismatch');}
function verifyFile(file,p){const stat=fs.lstatSync(file);if(!stat.isFile()||stat.isSymbolicLink()||stat.size!==p.size)throw Error('Invalid installer');const digest=crypto.createHash('sha512').update(fs.readFileSync(file)).digest('base64');if(digest!==p.sha512)throw Error('Installer integrity mismatch');}
async function readManifest(url,fetchImpl=fetch){const response=await fetchImpl(url,{redirect:'follow',cache:'no-store',signal:AbortSignal.timeout(20000)});if(!response.ok)throw Error('Manifest unavailable');const reader=response.body.getReader();let count=0,parts=[];try{for(;;){const {done,value}=await reader.read();if(done)break;count+=value.length;if(count>16000)throw Error('Manifest too large');parts.push(Buffer.from(value));}return JSON.parse(Buffer.concat(parts).toString('utf8'));}finally{await reader.cancel().catch(()=>{});}}
class SignedUpdater extends EventEmitter{
 constructor({backend,config,fetchManifest=readManifest}){super();this.on('error',()=>{});this.backend=backend;this.config=config;this.fetchManifest=fetchManifest;this.expected=null;this.installer=null;backend.autoDownload=false;backend.autoInstallOnAppQuit=false;backend.allowDowngrade=false;backend.allowPrerelease=false;backend.disableWebInstaller=true;backend.disableDifferentialDownload=true;backend.on('download-progress',p=>this.emit('download-progress',p));backend.on('error',()=>this.emit('error',Error('Update transport failed')));}
 async checkForUpdates(){this.installer=null;this.expected=null;const p=verifyManifest(await this.fetchManifest(this.config.url.replace(/\/$/,'')+'/release.json'),this.config.publicKey);const result=await this.backend.checkForUpdates();assertMetadata(result?.updateInfo,p);this.expected=p;return result;}
 async downloadUpdate(){if(!this.expected)throw Error('Signed manifest required');const p=this.expected;const files=await this.backend.downloadUpdate();if(!Array.isArray(files)||files.length!==1||this.expected!==p)throw Error('Invalid downloaded update');verifyFile(files[0],p);this.installer=files[0];this.emit('update-downloaded',{version:p.version});return files;}
 quitAndInstall(silent,forceRun){if(!this.installer||!this.expected)throw Error('Verified installer required');verifyFile(this.installer,this.expected);if(this.backend.installerPath!==this.installer)throw Error('Installer path changed');return this.backend.quitAndInstall(silent,forceRun);}
}
function createSignedUpdater({config,load=require}){const url=new URL(config.url);if(config.mode!=='ed25519'||url.protocol!=='https:'||url.username||url.password||url.search||url.hash)throw Error('Invalid signed update configuration');const key=crypto.createPublicKey(config.publicKey);if(key.asymmetricKeyType!=='ed25519')throw Error('Invalid key');const {NsisUpdater}=load('electron-updater');const backend=new NsisUpdater({provider:'generic',url:config.url});backend.logger={info(){},warn(){},error(){},debug(){}};return new SignedUpdater({backend,config});}
module.exports={verifyManifest,assertMetadata,verifyFile,readManifest,SignedUpdater,createSignedUpdater};
