'use strict';
const {randomUUID}=require('node:crypto');
const {renderWorklist,worklistExpectedRows}=require('./local-worklist.cjs');
async function deadline(promise,ms){let timer;try{return await Promise.race([promise,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('Worklist timeout')),ms);})]);}finally{clearTimeout(timer);}}
function createWorklistPreview({BrowserWindow,Menu,dialog,getParent}){
 let current=null;
 function close(){const old=current;current=null;if(old&&!old.isDestroyed())old.destroy();}
 function context(){return {worklistWebContentsId:current&&!current.isDestroyed()?current.webContents.id:null,worklistUrl:current?.worklistUrl||null};}
 async function open({orders,type,validate}={}){
  if(typeof validate!=='function'||!['packing','dispatch'].includes(type))throw Error('Worklist validation required');
  let html,expectedRows;try{html=renderWorklist({orders,type});expectedRows=worklistExpectedRows({orders,type});}catch{return {status:'DOCUMENT_UNAVAILABLE'};}const expectedContentIds=Array.from(html.matchAll(/data-content-id="([a-f0-9]{64})"/g),match=>match[1]);
  close();const parent=getParent();if(!parent||parent.isDestroyed())return {status:'DOCUMENT_UNAVAILABLE'};const ids=orders.map(row=>row.hubOrderId),url='about:blank';
  const win=new BrowserWindow({parent,width:900,height:900,show:false,title:`모아온 · ${type==='packing'?'포장명세서 A4':'출고 작업표 A4'}`,autoHideMenuBar:false,webPreferences:{partition:'moaon-worklist-'+randomUUID(),nodeIntegration:false,contextIsolation:true,sandbox:true,webSecurity:true,javascript:false,webviewTag:false,devTools:false,spellcheck:false}});
  win.webContents.session?.webRequest.onBeforeRequest({urls:['<all_urls>']},(_r,done)=>done({cancel:true}));win.webContents.session?.setPermissionRequestHandler((_c,_p,done)=>done(false));current=win;win.worklistUrl=url;const alive=()=>current===win&&!win.isDestroyed();let printing=false,attempted=false,timer;
  async function verify(){if(!alive()||win.webContents.getURL()!==url)return false;const data=await win.webContents.executeJavaScriptInIsolatedWorld(999,[{code:`(()=>({ids:Array.from(document.querySelectorAll('.work-row'),x=>x.dataset.orderId),texts:Array.from(document.querySelectorAll('.work-row'),x=>x.textContent),checks:document.querySelectorAll('.order-check').length,pages:Array.from(document.querySelectorAll('.work-page'),page=>{const r=page.getBoundingClientRect(),footer=page.querySelector('footer')?.getBoundingClientRect(),rows=Array.from(page.querySelectorAll('.work-row'),row=>row.getBoundingClientRect());return {width:r.width,height:r.height,fit:page.scrollWidth<=page.clientWidth+1&&page.scrollHeight<=page.clientHeight+1&&!!footer&&rows.every(row=>row.bottom<=footer.top),content:page.dataset.contentId,head:!!page.querySelector('header h1'),foot:!!footer};})}))()`}]);const w=210*96/25.4,h=297*96/25.4;return alive()&&JSON.stringify(data?.ids)===JSON.stringify(ids)&&JSON.stringify(data?.texts)===JSON.stringify(expectedRows)&&data.checks===ids.length&&data.pages?.length===Math.ceil(ids.length/4)&&JSON.stringify(data.pages.map(page=>page.content))===JSON.stringify(expectedContentIds)&&data.pages.every(page=>page.fit&&page.head&&page.foot&&page.width<=w+1&&page.height<=h+1);}
  const menu=Menu.buildFromTemplate([{id:'print',label:'인쇄 설정 열기',enabled:false,click:async()=>{if(printing||!alive())return;printing=true;menu.getMenuItemById('print').enabled=false;win.setTitle('인쇄 준비 · 작업 문서를 다시 확인 중');try{if(!await deadline(validate(),15000)||!await deadline(verify(),15000))throw Error();const answer=await deadline(dialog.showMessageBox(win,{type:'question',title:'A4 작업 문서 인쇄',message:`${type==='packing'?'포장명세서':'출고 작업표'} ${orders.length}건을 확인했나요?`,detail:(attempted?'이 창에서 이미 인쇄를 요청했습니다. 중복 출력되지 않도록 프린터 대기열과 실제 출력물을 먼저 확인하세요.\n\n':'')+'이 문서는 작업 확인용이며 송장등록·출고승인이 아닙니다. 외부 송장을 대신할 수 없습니다.',buttons:['취소','인쇄 설정 열기'],defaultId:0,cancelId:0,noLink:true}),60000);if(answer?.response!==1){if(alive())win.setTitle('인쇄 취소 · 새 인쇄 요청 없음');return;}if(!await deadline(validate(),15000)||!await deadline(verify(),15000))throw Error();attempted=true;await deadline(new Promise(resolve=>win.webContents.print({silent:false,printBackground:true,pageSize:'A4',margins:{marginType:'none'},landscape:false},(success,reason)=>{if(alive())win.setTitle(success?'인쇄 요청 전달됨 · 실제 출력 확인 필요':reason==='Print job canceled'?'인쇄 취소 · 출력 상태 확인':'인쇄 실패 · 프린터와 대기열 확인');resolve();})),60000);}catch{if(alive())win.setTitle('문서 확인 실패 · 창을 닫고 다시 확인하세요');}finally{printing=false;if(alive())menu.getMenuItemById('print').enabled=true;}}},{label:'닫기',click:()=>{if(alive())close();}}]);
  win.setMenu(menu);win.webContents.setWindowOpenHandler(()=>({action:'deny'}));for(const name of ['will-navigate','will-redirect','will-attach-webview'])win.webContents.on(name,event=>{event.preventDefault();if(alive())close();});win.webContents.on('did-navigate',(_e,target)=>{if(target!==url&&alive())close();});win.on('closed',()=>{if(current===win)current=null;});
  try{await Promise.race([(async()=>{await win.loadURL(url);await win.webContents.executeJavaScriptInIsolatedWorld(999,[{code:`document.open();document.write(${JSON.stringify(html)});document.close();`}]);html=null;if(!await validate()||!await verify())throw Error();})(),new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('Worklist timeout')),15000);})]);if(!alive())return {status:'DOCUMENT_UNAVAILABLE'};menu.getMenuItemById('print').enabled=true;win.show();return {status:'PREVIEW_OPEN'};}catch{if(alive())close();return {status:'DOCUMENT_UNAVAILABLE'};}finally{clearTimeout(timer);}
 }
 return Object.freeze({open,close,context});
}
module.exports={createWorklistPreview};
